#  Copyright (C) 2017 Spreadtrum Communications Inc.
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.


ccflags-y := -I$(srctree)/lib/crypto/sw/inc

obj-y += aes_gcm/
obj-y += aes_core.o
obj-y += cbc.o
obj-y += ctr.o
obj-y += mode_wrappers.o
obj-y += aes_test.o
obj-y += pkcs7_padding.o
obj-y += aes256_cbc_pkcs7.o

