
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += autopoweron_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += log_mechanism_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += storage_type_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += nand_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += adc_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += efuse_ITcase.o
obj-$(CONFIG_CMD_UBOOT_IT_FUNCTION_TEST) += adi_ITcase.o
