/******************************************************************************
 ** File Name:      pmu.c                                                     *
 ** Author:         Deven.Sheng                                               *
 ** DATE:           16/11/2018                                                *
 ** Copyright:      2018 Spreatrum, Incoporated. All Rights Reserved.         *
 ** Description:    This file defines the basic information on chip.          *
 ******************************************************************************/
#include <asm/io.h>
#include "adi_hal_internal.h"
#include "asm/arch-qogirn6pro/sprd_reg.h"
#include "asm/arch-qogirn6pro/common.h"


#define AON_IDLE_CLK_RCO_4M	0
#define AON_IDLE_CLK_4M_AON	1
#define AON_IDLE_CLK_13M_AON	2
#define AON_IDLE_CLK_RCO_25M	3
#define AON_IDLE_CLK_26M_AON	4
#define AON_IDLE_CLK_96M	5
#define AON_IDLE_CLK_RCO_100M	6
#define AON_IDLE_CLK_128M	7


// PMU power on/off sequence
void pmu_sequence_config(void)
{
	/* Sharkl6pro_typical_parameter.xls 2020.05.11 rco-4M */
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_0,
		     BIT_PMU_APB_PD_APCPU_CORE1_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE0_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_TOP_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_AP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_1,
		     BIT_PMU_APB_PD_APCPU_CORE5_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE4_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE3_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE2_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_2,
		     BIT_PMU_APB_PD_APCPU_CORE7_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE6_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_4,
		     BIT_PMU_APB_PD_GPU_CORE0_RAM_PWR_DLY(1)|
		     BIT_PMU_APB_PD_GPU_RAM_PWR_DLY(1)|
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_5,
		     BIT_PMU_APB_PD_GPU_CORE3_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_GPU_CORE2_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_GPU_CORE1_RAM_PWR_DLY(1) |
		0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_6,
		     BIT_PMU_APB_PD_CAMERA_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_7,
		     BIT_PMU_APB_PD_ISP_BLK_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_DCAM_BLK_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_8,
		     BIT_PMU_APB_PD_DPU_VSP_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_VDSP_BLK_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_9,
		     BIT_PMU_APB_PD_VDEC_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_VENC1_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_VENC0_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_10,
		     BIT_PMU_APB_PD_AI_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_11,
		     BIT_PMU_APB_PD_PS_CP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_12,
		     BIT_PMU_APB_PD_CR8_PHY_TOP_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_PHY_CP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_13,
		     BIT_PMU_APB_PD_LW_PROC_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_TD_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_14,
		     BIT_PMU_APB_PD_WCE_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_DPFEC_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_LCE_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_15,
		     BIT_PMU_APB_PD_NR_PDS_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_NR_DL_TOP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_16,
		     BIT_PMU_APB_PD_NR_CST_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_NR_SPP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_17,
		     BIT_PMU_APB_PD_UNI_TOP_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_18,
		     BIT_PMU_APB_PD_CDMA_PROC1_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_CDMA_PROC0_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_21,
		     BIT_PMU_APB_PD_AUD_CEVA_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_AUDIO_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_22,
		     BIT_PMU_APB_PD_PCIE_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_DPU_DP_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_IPA_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RAM_PWR_DLY_CFG_23,
		     BIT_PMU_APB_PD_PUB_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_PD_ISE_RAM_PWR_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PWR_DBG_PARAMETER,
		     BIT_PMU_APB_ISO_OFF_DLY(1) |
		     BIT_PMU_APB_CGM_ON_DLY(1) |
		     BIT_PMU_APB_RST_ASSERT_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DCDC_CPU0_PWR_DLY_CFG,
		     BIT_PMU_APB_PD_DCDC_CPU0_PWR_ON_DLY(4) |
		     BIT_PMU_APB_PD_DCDC_CPU0_PWR_OFF_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DCDC_CPU1_PWR_DLY_CFG,
		     BIT_PMU_APB_PD_DCDC_CPU1_PWR_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_DCDC_CPU1_SHUTDOWN_WINDOW(0) |
		     BIT_PMU_APB_PD_DCDC_CPU1_PWR_ON_DLY(4) |
		     BIT_PMU_APB_PD_DCDC_CPU1_PWR_OFF_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DCDC_CPU2_PWR_DLY_CFG,
		     BIT_PMU_APB_PD_DCDC_CPU2_PWR_ON_DLY(4) |
		     BIT_PMU_APB_PD_DCDC_CPU2_PWR_OFF_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_AP_CFG_0,
		     //BIT_PMU_APB_PD_AP_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_AP_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_AP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_AP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_AP_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_AP_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_TOP_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_TOP_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_TOP_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_APCPU_TOP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_TOP_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_TOP_PWR_ON_SEQ_DLY(2) |
		     BIT_PMU_APB_PD_APCPU_TOP_ISO_ON_DLY(9) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE0_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE0_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE0_PD_SEL |
		     //BIT_PMU_APB_PD_APCPU_CORE0_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_APCPU_CORE0_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE0_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE0_PWR_ON_SEQ_DLY(10) |
		     BIT_PMU_APB_PD_APCPU_CORE0_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE1_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE1_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE1_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE1_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE1_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE1_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE1_PWR_ON_SEQ_DLY(9) |
		     BIT_PMU_APB_PD_APCPU_CORE1_ISO_ON_DLY(2) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE2_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE2_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE2_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE2_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE2_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE2_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE2_PWR_ON_SEQ_DLY(8) |
		     BIT_PMU_APB_PD_APCPU_CORE2_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE3_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE3_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE3_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE3_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE3_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE3_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE3_PWR_ON_SEQ_DLY(7) |
		     BIT_PMU_APB_PD_APCPU_CORE3_ISO_ON_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE4_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE4_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE4_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE4_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE4_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE4_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE4_PWR_ON_SEQ_DLY(6) |
		     BIT_PMU_APB_PD_APCPU_CORE4_ISO_ON_DLY(5) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE5_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE5_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE5_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE5_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE5_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE5_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE5_PWR_ON_SEQ_DLY(5) |
		     BIT_PMU_APB_PD_APCPU_CORE5_ISO_ON_DLY(6) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE6_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE6_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE6_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE6_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE6_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE6_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_APCPU_CORE6_PWR_ON_SEQ_DLY(4) |
		     BIT_PMU_APB_PD_APCPU_CORE6_ISO_ON_DLY(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_APCPU_CORE7_CFG_0,
		     //BIT_PMU_APB_PD_APCPU_CORE7_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_APCPU_CORE7_PD_SEL |
		     BIT_PMU_APB_PD_APCPU_CORE7_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_APCPU_CORE7_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_APCPU_CORE7_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_APCPU_CORE7_ISO_ON_DLY(8) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_GPU_CFG_0,
		     //BIT_PMU_APB_PD_GPU_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_GPU_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_GPU_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_GPU_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_GPU_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_CAMERA_CFG_0,
		     //BIT_PMU_APB_PD_CAMERA_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_CAMERA_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_CAMERA_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_CAMERA_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_CAMERA_ISO_ON_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_DCAM_BLK_CFG_0,
		     BIT_PMU_APB_PD_DCAM_BLK_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_DCAM_BLK_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_DCAM_BLK_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_DCAM_BLK_PWR_ON_SEQ_DLY(2) |
		     BIT_PMU_APB_PD_DCAM_BLK_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_ISP_BLK_CFG_0,
		     BIT_PMU_APB_PD_ISP_BLK_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_ISP_BLK_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_ISP_BLK_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_ISP_BLK_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_ISP_BLK_ISO_ON_DLY(2) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_VDSP_BLK_CFG_0,
		     //BIT_PMU_APB_PD_VDSP_BLK_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_VDSP_BLK_PD_SEL |
		     BIT_PMU_APB_PD_VDSP_BLK_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_VDSP_BLK_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_VDSP_BLK_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_VDSP_BLK_PWR_ON_SEQ_DLY(4) |
		     BIT_PMU_APB_PD_VDSP_BLK_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_DPU_VSP_CFG_0,
		     //BIT_PMU_APB_PD_DPU_VSP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_DPU_VSP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_DPU_VSP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_DPU_VSP_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_DPU_VSP_ISO_ON_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_VENC0_CFG_0,
		     BIT_PMU_APB_PD_VENC0_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_VENC0_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_VENC0_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_VENC0_PWR_ON_SEQ_DLY(2) |
		     BIT_PMU_APB_PD_VENC0_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_VENC1_CFG_0,
		     BIT_PMU_APB_PD_VENC1_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_VENC1_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_VENC1_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_VENC1_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_VENC1_ISO_ON_DLY(2) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_VDEC_CFG_0,
		     BIT_PMU_APB_PD_VDEC_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_VDEC_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_VDEC_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_VDEC_PWR_ON_SEQ_DLY(4) |
		     BIT_PMU_APB_PD_VDEC_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_AI_CFG_0,
		     //BIT_PMU_APB_PD_AI_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_AI_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_AI_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_AI_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_AI_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_PS_CP_CFG_0,
		     //BIT_PMU_APB_PD_PS_CP_DBG_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_PS_CP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_PS_CP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_PS_CP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_PS_CP_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_PS_CP_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_PHY_CP_CFG_0,
		     BIT_PMU_APB_PD_PHY_CP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_PHY_CP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_PHY_CP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_PHY_CP_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_PHY_CP_ISO_ON_DLY(14) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_CR8_PHY_TOP_CFG_0,
		     //BIT_PMU_APB_PD_CR8_PHY_TOP_DBG_SHUTDOWN_EN |
		     //IT_PMU_APB_PD_CR8_PHY_TOP_PD_SEL |
		     BIT_PMU_APB_PD_CR8_PHY_TOP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_CR8_PHY_TOP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_CR8_PHY_TOP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_CR8_PHY_TOP_PWR_ON_SEQ_DLY(2) |
		     BIT_PMU_APB_PD_CR8_PHY_TOP_ISO_ON_DLY(13) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_TD_CFG_0,
		     BIT_PMU_APB_PD_TD_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_TD_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_TD_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_TD_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_TD_ISO_ON_DLY(12) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_LW_PROC_CFG_0,
		     BIT_PMU_APB_PD_LW_PROC_FORCE_SHUTDOWN  |
		     //BIT_PMU_APB_PD_LW_PROC_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_LW_PROC_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_LW_PROC_PWR_ON_SEQ_DLY(4) |
		     BIT_PMU_APB_PD_LW_PROC_ISO_ON_DLY(11) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_LCE_CFG_0,
		     BIT_PMU_APB_PD_LCE_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_LCE_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_LCE_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_LCE_PWR_ON_SEQ_DLY(5) |
		     BIT_PMU_APB_PD_LCE_ISO_ON_DLY(10) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_DPFEC_CFG_0,
		     BIT_PMU_APB_PD_DPFEC_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_DPFEC_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_DPFEC_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_DPFEC_PWR_ON_SEQ_DLY(6) |
		     BIT_PMU_APB_PD_DPFEC_ISO_ON_DLY(9) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_WCE_CFG_0,
		     BIT_PMU_APB_PD_WCE_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_WCE_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_WCE_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_WCE_PWR_ON_SEQ_DLY(7) |
		     BIT_PMU_APB_PD_WCE_ISO_ON_DLY(8) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_NR_DL_TOP_CFG_0,
		     BIT_PMU_APB_PD_NR_DL_TOP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_NR_DL_TOP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_NR_DL_TOP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_NR_DL_TOP_PWR_ON_SEQ_DLY(8) |
		     BIT_PMU_APB_PD_NR_DL_TOP_ISO_ON_DLY(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_NR_PDS_CFG_0,
		     BIT_PMU_APB_PD_NR_PDS_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_NR_PDS_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_NR_PDS_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_NR_PDS_PWR_ON_SEQ_DLY(9) |
		     BIT_PMU_APB_PD_NR_PDS_ISO_ON_DLY(6) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_NR_SPP_CFG_0,
		     BIT_PMU_APB_PD_NR_SPP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_NR_SPP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_NR_SPP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_NR_SPP_PWR_ON_SEQ_DLY(10) |
		     BIT_PMU_APB_PD_NR_SPP_ISO_ON_DLY(5) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_NR_CST_CFG_0,
		     BIT_PMU_APB_PD_NR_CST_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_NR_CST_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_NR_CST_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_NR_CST_PWR_ON_SEQ_DLY(11) |
		     BIT_PMU_APB_PD_NR_CST_ISO_ON_DLY(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_UNI_TOP_CFG_0,
		     BIT_PMU_APB_PD_UNI_TOP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_UNI_TOP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_UNI_TOP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_UNI_TOP_PWR_ON_SEQ_DLY(12) |
		     BIT_PMU_APB_PD_UNI_TOP_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_CDMA_PROC0_CFG_0,
		     BIT_PMU_APB_PD_CDMA_PROC0_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_CDMA_PROC0_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_CDMA_PROC0_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_CDMA_PROC0_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_CDMA_PROC0_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_AUDIO_CFG_0,
		     BIT_PMU_APB_PD_AUDIO_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_AUDIO_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_AUDIO_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_AUDIO_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_AUDIO_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_AUD_CEVA_CFG_0,
		     //BIT_PMU_APB_PD_AUD_CEVA_DBG_SHUTDOWN_EN |
		     //BIT_PMU_APB_PD_AUD_CEVA_PD_SEL |
		     BIT_PMU_APB_PD_AUD_CEVA_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_AUD_CEVA_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_AUD_CEVA_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_AUD_CEVA_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_AUD_CEVA_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_IPA_CFG_0,
		     //BIT_PMU_APB_PD_IPA_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_IPA_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_IPA_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_IPA_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_IPA_ISO_ON_DLY(3) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_DPU_DP_CFG_0,
		     BIT_PMU_APB_PD_DPU_DP_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_DPU_DP_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_DPU_DP_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_DPU_DP_PWR_ON_SEQ_DLY(3) |
		     BIT_PMU_APB_PD_DPU_DP_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_PCIE_CFG_0,
		     //BIT_PMU_APB_PD_PCIE_PD_SEL |
		     //BIT_PMU_APB_PD_PCIE_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_PCIE_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_PCIE_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_PCIE_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_PCIE_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_ISE_CFG_0,
		     BIT_PMU_APB_PD_ISE_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_ISE_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_ISE_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_ISE_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_ISE_ISO_ON_DLY(1) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PD_PUB_CFG_0,
		     //BIT_PMU_APB_PD_PUB_FORCE_SHUTDOWN |
		     //BIT_PMU_APB_PD_PUB_AUTO_SHUTDOWN_EN |
		     BIT_PMU_APB_PD_PUB_PWR_ON_DLY(1) |
		     BIT_PMU_APB_PD_PUB_PWR_ON_SEQ_DLY(1) |
		     BIT_PMU_APB_PD_PUB_ISO_ON_DLY(1) |
		     0
	);


	CHIP_REG_SET(REG_PMU_APB_XTL_WAIT_CNT,
		     BIT_PMU_APB_XTL0_WAIT_CNT(70) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_XTLBUF_WAIT_CNT,
		     BIT_PMU_APB_XTLBUF1_WAIT_CNT(2) |
		     BIT_PMU_APB_XTLBUF0_WAIT_CNT(2) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RCO_WAIT_CNT,
		     BIT_PMU_APB_RCO150M_WAIT_CNT(1) |
		     BIT_PMU_APB_RCO6M_WAIT_CNT(1) |
		     BIT_PMU_APB_RCO60M_WAIT_CNT(1) |
		     BIT_PMU_APB_RCO100M_WAIT_CNT(11) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_0,
		     BIT_PMU_APB_MPLLBIG_WAIT_CNT(7) |
		     BIT_PMU_APB_MPLLMID_WAIT_CNT(7) |
		     BIT_PMU_APB_MPLLLIT_WAIT_CNT(7) |
		     BIT_PMU_APB_MPLLSCU_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_1,
		     BIT_PMU_APB_RPLL_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_2,
		     BIT_PMU_APB_GPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_DPLL2_WAIT_CNT(4) |
		     BIT_PMU_APB_DPLL1_WAIT_CNT(4) |
		     BIT_PMU_APB_DPLL0_WAIT_CNT(4) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_3,
		     BIT_PMU_APB_PHYCPR8PLL_WAIT_CNT(7) |
		     BIT_PMU_APB_VDSPPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_AIPLL_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_4,
		     BIT_PMU_APB_TGPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_PSCPR8PLL_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_5,
		     BIT_PMU_APB_AUDPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_V4NRPLL_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_6,
		     BIT_PMU_APB_DDCPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_PIXELPLL_WAIT_CNT(7) |
		     BIT_PMU_APB_USB31PLLV_WAIT_CNT(2) |
		     BIT_PMU_APB_PCIEPLLV_WAIT_CNT(7) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PLL_WAIT_CNT_8,
		     BIT_PMU_APB_CPLL_WAIT_CNT(7) |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_MPLLSCU_RST_CTRL_CFG,
		     //BIT_PMU_APB_MPLLSCU_RST_CTRL_BYPASS |
		     BIT_PMU_APB_MPLLSCU_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_MPLLSCU_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_MPLLSCU_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_MPLLLIT_RST_CTRL_CFG,
		     //BIT_PMU_APB_MPLLLIT_RST_CTRL_BYPASS |
		     BIT_PMU_APB_MPLLLIT_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_MPLLLIT_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_MPLLLIT_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_MPLLMID_RST_CTRL_CFG,
		     //BIT_PMU_APB_MPLLMID_RST_CTRL_BYPASS |
		     BIT_PMU_APB_MPLLMID_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_MPLLMID_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_MPLLMID_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_MPLLBIG_RST_CTRL_CFG,
		     //BIT_PMU_APB_MPLLBIG_RST_CTRL_BYPASS |
		     BIT_PMU_APB_MPLLBIG_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_MPLLBIG_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_MPLLBIG_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_RPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_RPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_RPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_RPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_RPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DPLL0_RST_CTRL_CFG,
		     //BIT_PMU_APB_DPLL0_RST_CTRL_BYPASS |
		     BIT_PMU_APB_DPLL0_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_DPLL0_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_DPLL0_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DPLL1_RST_CTRL_CFG,
		     //BIT_PMU_APB_DPLL1_RST_CTRL_BYPASS |
		     BIT_PMU_APB_DPLL1_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_DPLL1_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_DPLL1_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DPLL2_RST_CTRL_CFG,
		     //BIT_PMU_APB_DPLL2_RST_CTRL_BYPASS |
		     BIT_PMU_APB_DPLL2_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_DPLL2_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_DPLL2_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_AIPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_AIPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_AIPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_AIPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_AIPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_VDSPPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_VDSPPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_VDSPPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_VDSPPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_VDSPPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PHYCPR8PLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_PHYCPR8PLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_PHYCPR8PLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_PHYCPR8PLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_PHYCPR8PLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PSCPR8PLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_PSCPR8PLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_PSCPR8PLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_PSCPR8PLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_PSCPR8PLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_TGPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_TGPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_TGPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_TGPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_TGPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_V4NRPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_V4NRPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_V4NRPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_V4NRPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_V4NRPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_AUDPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_AUDPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_AUDPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_AUDPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_AUDPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PCIEPLLV_RST_CTRL_CFG,
		     //BIT_PMU_APB_PCIEPLLV_RST_CTRL_BYPASS |
		     BIT_PMU_APB_PCIEPLLV_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_PCIEPLLV_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_PCIEPLLV_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_USB31PLLV_RST_CTRL_CFG,
		     //BIT_PMU_APB_USB31PLLV_RST_CTRL_BYPASS |
		     BIT_PMU_APB_USB31PLLV_DELAY_PWR_ON(82) |
		     BIT_PMU_APB_USB31PLLV_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_USB31PLLV_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PIXELPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_PIXELPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_PIXELPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_PIXELPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_PIXELPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_DDCPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_DDCPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_DDCPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_DDCPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_DDCPLL_DELAY_RST_ASSERT(26) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_CPLL_RST_CTRL_CFG,
		     //BIT_PMU_APB_CPLL_RST_CTRL_BYPASS |
		     BIT_PMU_APB_CPLL_DELAY_PWR_ON(52) |
		     BIT_PMU_APB_CPLL_DELAY_EN_OFF(4) |
		     BIT_PMU_APB_CPLL_DELAY_RST_ASSERT(26) |
		     0
	);


	CHIP_REG_SET(REG_PMU_APB_APCPU_MODE_ST_CFG0,
		     BIT_PMU_APB_APCPU_CORINTH_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_APCPU_CORE_RAM_PWR_DLY(1) |
		     BIT_PMU_APB_APCPU_CORE_INITIAL_DLY(10) |
		     BIT_PMU_APB_APCPU_CORINTH_INITIAL_DLY(10) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_APCPU_MODE_ST_CFG1,
		     BIT_PMU_APB_APCPU_CORE_RST_DEASSERT_DLY(2) |
		     BIT_PMU_APB_APCPU_CORE_RST_ASSERT_DLY(2) |
		     BIT_PMU_APB_APCPU_CORINTH_RST_DEASSERT_DLY(2) |
		     BIT_PMU_APB_APCPU_CORINTH_RST_ASSERT_DLY(2) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_APCPU_MODE_ST_CFG2,
		     BIT_PMU_APB_APCPU_CORE_CGM_OFF_DLY(2) |
		     BIT_PMU_APB_APCPU_CORE_CGM_ON_DLY(2) |
		     0
	);


	CHIP_REG_SET(REG_PMU_APB_SP_CLK_GATE_BYP_CFG,
		     //BIT_PMU_APB_SP_PWR_PD_SP_MEM_BYP |
		     BIT_PMU_APB_SP_PWR_PD_AON_MEM_BYP |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_CH_CLK_GATE_BYP_CFG,
		     //BIT_PMU_APB_CH_PWR_PD_CH_MEM_BYP |
		     BIT_PMU_APB_CH_PWR_PD_AON_MEM_BYP |
		     0
	);


	CHIP_REG_SET(REG_PMU_APB_PWR_ST_CLK_DIV_CFG,
		     BIT_PMU_APB_PWR_ST_CLK_DIV_CFG(15) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_SLP_CTRL_CLK_DIV_CFG,
		     BIT_PMU_APB_SLP_CTRL_CLK_DIV_CFG(127) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_MPLL_WAIT_CLK_DIV_CFG,
		     BIT_PMU_APB_MPLL_WAIT_CLK_DIV_CFG(127) |
		     0
	);


	CHIP_REG_SET(REG_PMU_APB_PWR_CNT_WAIT_CFG_0,
		     BIT_PMU_APB_AUDIO_PWR_WAIT_CNT(8) |
		     BIT_PMU_APB_PHY_CP_PWR_WAIT_CNT(40) |
		     BIT_PMU_APB_PS_CP_PWR_WAIT_CNT(40) |
		     BIT_PMU_APB_AP_PWR_WAIT_CNT(8) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PWR_CNT_WAIT_CFG_1,
		     BIT_PMU_APB_ISE_PWR_WAIT_CNT(8) |
		     BIT_PMU_APB_IPA_PWR_WAIT_CNT(8) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PWR_CNT_WAIT_CFG_2,
		     BIT_PMU_APB_CH_PWR_WAIT_CNT(40) |
		     BIT_PMU_APB_SP_PWR_WAIT_CNT(40) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PWR_CNT_WAIT_CFG_4,
		     BIT_PMU_APB_CDMA_PROC0_PWR_WAIT_CNT(8) |
		     0
	);

	CHIP_REG_AND(REG_PMU_APB_PUB_SLEEP_BYPASS_CFG,
		     ~(BIT_PMU_APB_PUB_PD_VOL_DOWN_ENA |
		     BIT_PMU_APB_PUB_VOL_ADJ_ENA |
		     BIT_PMU_APB_PUB_SELF_REFRESH_FLAG_BYPASS |
		     BIT_PMU_APB_PUB_PWR_PD_ACK_BYPASS |
		     BIT_PMU_APB_PUB_DEEP_SLEEP_LOCK_ACK_BYPASS |
		     0)
	);
	CHIP_REG_SET(REG_PMU_APB_DDR_SLEEP_WAIT_CNT,
		     BIT_PMU_APB_PUB_DEEP_SLEEP_WAIT_CNT(0) |
		     BIT_PMU_APB_PUB_SLEEP_WAIT_CNT(16) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_PUB_VOL_DOWN_CFG,
		     BIT_PMU_APB_PUB_VOL_UP_CNT(255) |
		     BIT_PMU_APB_PUB_VOL_DOWN_CNT(255) |
		     0
	);
	CHIP_REG_SET(REG_PMU_APB_ANALOG_PHY_PWR_DLY_CFG,
		     BIT_PMU_APB_PHY_PWR_DLY(4) |
		     0
	);

	/* 0:32K 1:ROC100M/25 2:XTLBUF/4 3:RCO60M/15 */
	CHIP_REG_SET(REG_PMU_APB_CGM_PMU_SEL,
		     BIT_PMU_APB_CGM_PMU_SEL_REG(1) |
		     0
	);

	/* Disable auto switch */
	CHIP_REG_AND(REG_PMU_APB_CGM_PMU_SEL,
		     ~BIT_PMU_APB_PMU_AUTO_SEL_RCO_EN
	);
}

void modules_force_on()
{
	CHIP_REG_AND(REG_PMU_APB_PD_PCIE_CFG_0,
		     ~(BIT_PMU_APB_PD_PCIE_PD_SEL |
		     BIT_PMU_APB_PD_PCIE_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_PCIE_AUTO_SHUTDOWN_EN)
	);

	CHIP_REG_AND(REG_PMU_APB_PD_IPA_CFG_0,
		     ~(BIT_PMU_APB_PD_IPA_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_IPA_AUTO_SHUTDOWN_EN)
	);

	CHIP_REG_AND(REG_PMU_APB_PD_AI_CFG_0,
		     ~(BIT_PMU_APB_PD_AI_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_AI_AUTO_SHUTDOWN_EN)
	);

	CHIP_REG_AND(REG_PMU_APB_PD_DPU_VSP_CFG_0,
		     ~(BIT_PMU_APB_PD_DPU_VSP_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_DPU_VSP_AUTO_SHUTDOWN_EN)
	);

	CHIP_REG_AND(REG_PMU_APB_PD_CAMERA_CFG_0,
		     ~(BIT_PMU_APB_PD_CAMERA_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_CAMERA_AUTO_SHUTDOWN_EN)
	);

	CHIP_REG_AND(REG_PMU_APB_PD_GPU_CFG_0,
		     ~(BIT_PMU_APB_PD_GPU_FORCE_SHUTDOWN |
		     BIT_PMU_APB_PD_GPU_AUTO_SHUTDOWN_EN)
	);
}

//PMU pad out select config
void pad_out_sel_config(void)
{
	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_CHIP_SLEEP_CFG,
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_POL_SEL |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_TOP_DVFS_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_DCDC_CPU2_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_DCDC_CPU1_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_DCDC_CPU0_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_PLL_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_CDMA_AUTO_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_SP_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_ISE_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_AUDIO_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_PHY_CP_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_PS_CP_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_CHIP_SLEEP_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_XTL_EN0_CFG,
		     //BIT_PMU_APB_PAD_OUT_XTL_EN0_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_TOP_DVFS_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_DCDC_CPU2_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_DCDC_CPU1_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_CDMA_PROC0_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_XTL_EN0_CH_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_XTL_EN0_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_AUDIO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_PHY_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN0_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_XTL_EN1_CFG,
		     //BIT_PMU_APB_PAD_OUT_XTL_EN1_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_TOP_DVFS_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_DCDC_CPU2_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_DCDC_CPU1_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_IPA_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_XTL_EN1_AUDIO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_PHY_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_XTL_EN2_CFG,
		     //BIT_PMU_APB_PAD_OUT_XTL_EN2_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_TOP_DVFS_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_DCDC_CPU2_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_DCDC_CPU1_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN1_AUDIO_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_XTL_EN2_PHY_CP_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_XTL_EN2_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_XTL_EN2_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_CFG,
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_TOP_DVFS_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_DCDC_CPU2_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_DCDC_CPU1_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_AUDIO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_PHY_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU0_EN_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_CFG,
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_TOP_DVFS_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_DCDC_CPU2_PD_MASK |
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_DCDC_CPU1_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_AUDIO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_PHY_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU1_EN_AP_DEEP_SLEEP_MASK |
		     0
	);

	CHIP_REG_SET(REG_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_CFG,
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_POL_SEL |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_TOP_DVFS_DEEP_SLEEP_MASK |
		     //BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_DCDC_CPU2_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_DCDC_CPU1_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_DCDC_CPU0_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_PLL_PD_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_PUB_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_CDMA_AUTO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_CDMA_PROC0_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_CH_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_SP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_ISE_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_IPA_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_AUDIO_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_PHY_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_PS_CP_DEEP_SLEEP_MASK |
		     BIT_PMU_APB_PAD_OUT_DCDC_APCPU2_EN_AP_DEEP_SLEEP_MASK |
		     0
	);
}

//AON idle config
void aon_idle_config(void)
{
        //Enable aon idle, 4M clock when aon idle
  	uint32_t value = 0U;
  	value = CHIP_REG_GET(REG_AON_APB_CLK_AON_APB_DFS_CTRL) | BIT_AON_APB_AON_APB_IDLE_EN;
  	value = (value & ~BIT_AON_APB_CGM_AON_APB_DFS_OVERRIDE(~0)) | BIT_AON_APB_CGM_AON_APB_DFS_OVERRIDE(AON_IDLE_CLK_13M_AON);
  	CHIP_REG_SET(REG_AON_APB_CLK_AON_APB_DFS_CTRL,value);
}

//AON lpc config
void aon_lpc_config(void)
{
#if defined(CONFIG_AON_LPC_EN)
	CHIP_REG_OR(REG_AON_APB_APCPU_CLUSTER_SCU_LPC_CTRL,
		    BIT_AON_APB_APCPU_CLUSTER_SCU_LP_EB);
	CHIP_REG_OR(REG_AON_APB_APCPU_CLUSTER_GIC_LPC_CTRL,
		    BIT_AON_APB_APCPU_CLUSTER_GIC_LP_EB);
	CHIP_REG_OR(REG_AON_APB_APCPU_CLUSTER_ATB_LPC_CTRL,
		    BIT_AON_APB_APCPU_CLUSTER_ATB_LP_EB);
	CHIP_REG_OR(REG_AON_APB_APCPU_CLUSTER_APB_LPC_CTRL,
		    BIT_AON_APB_APCPU_CLUSTER_APB_LP_EB);


	CHIP_REG_AND(REG_AON_APB_APCPU_DBG_BLK_LPC_CTRL,
		    ~BIT_AON_APB_APCPU_DBG_BLK_LP_EB);

	CHIP_REG_OR(REG_AON_APB_APCPU_GIC600_GIC_LPC_CTRL,
		    BIT_AON_APB_APCPU_GIC600_GIC_LP_EB);

	CHIP_REG_OR(REG_AON_APB_APCPU_TOP_MTX_LPC_CTRL,
		    BIT_AON_APB_APCPU_MTX_MAIN_LP_EB |
		    BIT_AON_APB_APCPU_MTX_S3_LP_EB |
		    BIT_AON_APB_APCPU_MTX_S2_LP_EB |
		    BIT_AON_APB_APCPU_MTX_S1_LP_EB |
		    BIT_AON_APB_APCPU_MTX_S0_LP_EB |
		    BIT_AON_APB_APCPU_MTX_M4_LP_EB |
		    BIT_AON_APB_APCPU_MTX_M3_LP_EB |
		    BIT_AON_APB_APCPU_MTX_M2_LP_EB |
		    BIT_AON_APB_APCPU_MTX_M1_LP_EB |
		    0);

	CHIP_REG_OR(REG_AON_APB_APCPU_AON_AB_LPC_CTRL,
		    BIT_AON_APB_APCPU_AON_AB_LP_EB);
	CHIP_REG_OR(REG_AON_APB_APCPU_DDR_AB_LPC_CTRL,
		    BIT_AON_APB_APCPU_DDR_AB_LP_EB);
#endif
}

// AP lpc config
void ap_lpc_config(void)
{
#if defined(CONFIG_AP_LPC_EN)
	CHIP_REG_OR(REG_AP_AHB_M0_LPC, BIT_AP_AHB_MAIN_M0_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M1_LPC, BIT_AP_AHB_MAIN_M1_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M2_LPC, BIT_AP_AHB_MAIN_M2_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M3_LPC, BIT_AP_AHB_MAIN_M3_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M4_LPC, BIT_AP_AHB_MAIN_M4_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M5_LPC, BIT_AP_AHB_MAIN_M5_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M6_LPC, BIT_AP_AHB_MAIN_M6_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_M7_LPC, BIT_AP_AHB_MAIN_M7_LP_EB);

	CHIP_REG_OR(REG_AP_AHB_S0_LPC, BIT_AP_AHB_MAIN_S0_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S1_LPC, BIT_AP_AHB_MAIN_S1_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S2_LPC, BIT_AP_AHB_MAIN_S2_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S3_LPC, BIT_AP_AHB_MAIN_S3_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S4_LPC, BIT_AP_AHB_MAIN_S4_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S5_LPC, BIT_AP_AHB_MAIN_S5_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S6_LPC, BIT_AP_AHB_MAIN_S6_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_S7_LPC, BIT_AP_AHB_MAIN_S7_LP_EB);

	CHIP_REG_OR(REG_AP_AHB_AP_ASYNC_BRG_AON,
		    BIT_AP_AHB_AP_ASYNC_BRG_AON_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_AP_ASYNC_BRG_DDR,
		    BIT_AP_AHB_AP_ASYNC_BRG_DDR_LP_EB);
	CHIP_REG_OR(REG_AP_AHB_AP_ASYNC_BRG_APCPU,
		    BIT_AP_AHB_AP_ASYNC_BRG_APCPU_LP_EB);
#endif
}

// Clock auto gate
void clock_auto_gate(void)
{
#if defined(CONFIG_CLOCK_AUTO_GATE_EN)
	unsigned int value;

/*
	//The CPU clock is not turned off until the DVFS is enabled.
	CHIP_REG_OR(REG_AON_APB_AUTO_GATE_CTRL3,
		    BIT_AON_APB_CGM_PERIPH_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_GIC_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_ACP_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_AXI_PERIPH_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_ACE_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_SCU_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE7_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE6_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE5_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE4_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE3_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE2_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE1_AUTO_GATE_EN |
		    BIT_AON_APB_CGM_CORE0_AUTO_GATE_EN |
		    0);
*/

	CHIP_REG_OR(REG_AON_APB_AUTO_GATE_CTRL0,
		    BIT_AON_APB_CGM_AP_AXI_AUTO_GATE_SEL |
		    BIT_AON_APB_CGM_APCPU_PMU_AUTO_GATE_SEL |
		    0);

	value = CHIP_REG_GET(REG_AON_APB_AUTO_GATE_CTRL0) &
		~(BIT_AON_APB_CGM_AP_AXI_FORCE_EN |
		  BIT_AON_APB_CGM_APCPU_PMU_FORCE_EN);
	CHIP_REG_SET(REG_AON_APB_AUTO_GATE_CTRL0, value);

	//TOP DVFS
	value = (CHIP_REG_GET(REG_AON_APB_AUTO_GATE_CTRL1) &
		~BIT_AON_APB_CGM_TOP_DVFS_ROOT_FORCE_EN) |
		  BIT_AON_APB_CGM_TOP_DVFS_ROOT_AUTO_GATE_SEL;
	CHIP_REG_SET(REG_AON_APB_AUTO_GATE_CTRL1, value);

	//RC100M
	value = (CHIP_REG_GET(REG_AON_APB_RC100M_CFG) &
		~BIT_AON_APB_RC100M_FORCE_EN) | BIT_AON_APB_RC100M_AUTO_GATE_EN;
	CHIP_REG_SET(REG_AON_APB_RC100M_CFG, value);

	//RC6M
	value = (CHIP_REG_GET(REG_AON_APB_RC6M_CFG0) &
		~BIT_AON_APB_RC6M_FORCE_EN) | BIT_AON_APB_RC6M_AUTO_GATE_EN;
	CHIP_REG_SET(REG_AON_APB_RC6M_CFG0, value);

	//RC60M
	value = (CHIP_REG_GET(REG_AON_APB_RC60M_CFG0) &
		~BIT_AON_APB_RC60M_FORCE_EN) | BIT_AON_APB_RC60M_AUTO_GATE_EN;
	CHIP_REG_SET(REG_AON_APB_RC60M_CFG0, value);

	//AP MATRIX
	CHIP_REG_OR(REG_AP_AHB_S0_LPC, BIT_AP_AHB_CGM_MTX_S0_AUTO_GATE_EN);
	CHIP_REG_OR(REG_AP_AHB_S1_LPC, BIT_AP_AHB_CGM_MTX_S1_AUTO_GATE_EN);
	CHIP_REG_OR(REG_AP_AHB_S2_LPC, BIT_AP_AHB_CGM_MTX_S2_AUTO_GATE_EN);
	CHIP_REG_OR(REG_AP_AHB_S5_LPC, BIT_AP_AHB_CGM_MTX_S5_AUTO_GATE_EN);
	CHIP_REG_OR(REG_AP_AHB_S6_LPC, BIT_AP_AHB_CGM_MTX_S6_AUTO_GATE_EN);
	CHIP_REG_OR(REG_AP_AHB_S7_LPC, BIT_AP_AHB_CGM_MTX_S7_AUTO_GATE_EN);

	//DDCPLL_PD_EN
	CHIP_REG_OR(REG_PMU_APB_DDC_SLP_CFG, BIT_PMU_APB_DDCPLL_PD_ENA);
#endif
}

void CSP_Init(uint32_t gen_para)
{
	pmu_sequence_config();
	pad_out_sel_config();
	aon_idle_config();
	aon_lpc_config();
	ap_lpc_config();
	clock_auto_gate();
}

