/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

#ifndef __PUB_QOSC_AHB_H____
#define __PUB_QOSC_AHB_H____

/* Some defs, in case these are not defined elsewhere */
#ifndef SCI_IOMAP
#define SCI_IOMAP(_b_) ( (_b_) )
#endif

#ifndef SCI_ADDR
#define SCI_ADDR(_b_, _o_) ( (_b_) + (_o_) )
#endif

#ifndef CTL_PUB_QOSC_AHB_BASE
#define CTL_PUB_QOSC_AHB_BASE           SCI_IOMAP(0x30210000)
#endif

/* registers definitions for CTL_PUB_QOSC_AHB, 0x30210000 */
#define REG_PUB_QOSC_AHB_QOS_CTRL_EB                        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0000)
#define REG_PUB_QOSC_AHB_QOS_CTRL_RESET                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0004)
#define REG_PUB_QOSC_AHB_QOSC_CLK_CTRL                      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0008)
#define REG_PUB_QOSC_AHB_QOSC_PORT_ENABLE                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x000C)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNTER_EN                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0010)
#define REG_PUB_QOSC_AHB_QOSC_AXURGENT_EN                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0014)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_EN                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0018)
#define REG_PUB_QOSC_AHB_QOSC_CFG                           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x001C)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH0      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0020)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH1      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0024)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH2      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0028)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH3      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x002C)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH4      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0030)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH5      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0034)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH6      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0038)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH7      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x003C)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH0      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0050)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH1      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0054)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH2      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0058)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH3      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x005C)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH4      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0060)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH5      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0064)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH6      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0068)
#define REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH7      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x006C)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH0           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0080)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH1           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0084)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH2           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0088)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH3           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x008C)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH4           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0090)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH5           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0094)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH6           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0098)
#define REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH7           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x009C)
#define REG_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW0             SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00B0)
#define REG_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW1             SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00B4)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH0            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00C0)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH1            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00C4)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH2            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00C8)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH3            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00CC)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH4            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00D0)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH5            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00D4)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH6            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00D8)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH7            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00DC)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH8            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00E0)
#define REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH9            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00E4)
#define REG_PUB_QOSC_AHB_QOSC_FORCE_URGENT_HIGH_EN          SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00F0)
#define REG_PUB_QOSC_AHB_QOSC_FORCE_URGENT_ULTRA_EN         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00F4)
#define REG_PUB_QOSC_AHB_QOSC_LATMON_AXURGENT_EN            SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x00F8)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0100)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0104)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0108)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH3                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x010C)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH4                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0110)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH5                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0114)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH6                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0118)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH7                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x011C)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH8                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0120)
#define REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH9                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0124)
#define REG_PUB_QOSC_AHB_QOSC_STATUS0                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0200)
#define REG_PUB_QOSC_AHB_QOSC_STATUS1                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0204)
#define REG_PUB_QOSC_AHB_QOSC_STATUS2                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0208)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH0              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0210)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH1              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0214)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH2              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0218)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH3              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x021C)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH4              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0220)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH5              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0224)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH6              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0228)
#define REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH7              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x022C)
#define REG_PUB_QOSC_AHB_QOSC_DBG_MON                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0280)
#define REG_PUB_QOSC_AHB_QOSC_MON_STATUS                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0284)
#define REG_PUB_QOSC_AHB_M1_QOS_CTRL_EB                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0400)
#define REG_PUB_QOSC_AHB_M1_QOS_CTRL_RESET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0404)
#define REG_PUB_QOSC_AHB_M1_QOSC_CLK_CTRL                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0408)
#define REG_PUB_QOSC_AHB_M1_QOSC_PORT_ENABLE                SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x040C)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNTER_EN              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0410)
#define REG_PUB_QOSC_AHB_M1_QOSC_AXURGENT_EN                SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0414)
#define REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_EN              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0418)
#define REG_PUB_QOSC_AHB_M1_QOSC_CFG                        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x041C)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH0   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0420)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH1   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0424)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH0   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0430)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH1   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0434)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH0        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0440)
#define REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH1        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0444)
#define REG_PUB_QOSC_AHB_M1_QOSC_BW_TIMING_WINDOW0          SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0450)
#define REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_CH0         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0460)
#define REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_CH1         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0464)
#define REG_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_HIGH_EN       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0470)
#define REG_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_ULTRA_EN      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0474)
#define REG_PUB_QOSC_AHB_M1_QOSC_LATMON_AXURGENT_EN         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0478)
#define REG_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_CH0              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0480)
#define REG_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_CH1              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0484)
#define REG_PUB_QOSC_AHB_M1_QOSC_STATUS0                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0500)
#define REG_PUB_QOSC_AHB_M1_QOSC_STATUS1                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0504)
#define REG_PUB_QOSC_AHB_M1_QOSC_STATUS2                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0508)
#define REG_PUB_QOSC_AHB_M1_QOSC_URGENT_COUNT_CH0           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0510)
#define REG_PUB_QOSC_AHB_M1_QOSC_URGENT_COUNT_CH1           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0514)
#define REG_PUB_QOSC_AHB_M2_QOS_CTRL_EB                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0600)
#define REG_PUB_QOSC_AHB_M2_QOS_CTRL_RESET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0604)
#define REG_PUB_QOSC_AHB_M2_QOSC_CLK_CTRL                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0608)
#define REG_PUB_QOSC_AHB_M2_QOSC_PORT_ENABLE                SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x060C)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNTER_EN              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0610)
#define REG_PUB_QOSC_AHB_M2_QOSC_AXURGENT_EN                SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0614)
#define REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_EN              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0618)
#define REG_PUB_QOSC_AHB_M2_QOSC_CFG                        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x061C)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH0   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0620)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH1   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0624)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH2   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0628)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH0   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0630)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH1   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0634)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH2   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0638)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH0        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0640)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH1        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0644)
#define REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH2        SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0648)
#define REG_PUB_QOSC_AHB_M2_QOSC_BW_TIMING_WINDOW0          SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0650)
#define REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH0         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0660)
#define REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH1         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0664)
#define REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH2         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0668)
#define REG_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_HIGH_EN       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0670)
#define REG_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_ULTRA_EN      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0674)
#define REG_PUB_QOSC_AHB_M2_QOSC_LATMON_AXURGENT_EN         SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0678)
#define REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH0              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0680)
#define REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH1              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0684)
#define REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH2              SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0688)
#define REG_PUB_QOSC_AHB_M2_QOSC_STATUS0                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0700)
#define REG_PUB_QOSC_AHB_M2_QOSC_STATUS1                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0704)
#define REG_PUB_QOSC_AHB_M2_QOSC_STATUS2                    SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0708)
#define REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH0           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0710)
#define REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH1           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0714)
#define REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH2           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0718)
#define REG_PUB_QOSC_AHB_LATMON_EB                          SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0800)
#define REG_PUB_QOSC_AHB_LATMON_RESET                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0804)
#define REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0808)
#define REG_PUB_QOSC_AHB_URGENT_RATIO_LM0                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x080C)
#define REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0810)
#define REG_PUB_QOSC_AHB_LATMON_HW_DFS_CFG                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0814)
#define REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0820)
#define REG_PUB_QOSC_AHB_URGENT_RATIO_LM1                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0824)
#define REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0828)
#define REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0830)
#define REG_PUB_QOSC_AHB_URGENT_RATIO_LM2                   SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0834)
#define REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0838)
#define REG_PUB_QOSC_AHB_LATMON_LM0_STATUS0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0900)
#define REG_PUB_QOSC_AHB_LATMON_LM0_STATUS1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0904)
#define REG_PUB_QOSC_AHB_LATMON_LM0_STATUS2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0908)
#define REG_PUB_QOSC_AHB_LATMON_LM0_STATUS3                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x090C)
#define REG_PUB_QOSC_AHB_LATMON_LM1_STATUS0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0910)
#define REG_PUB_QOSC_AHB_LATMON_LM1_STATUS1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0914)
#define REG_PUB_QOSC_AHB_LATMON_LM1_STATUS2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0918)
#define REG_PUB_QOSC_AHB_LATMON_LM1_STATUS3                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x091C)
#define REG_PUB_QOSC_AHB_LATMON_LM2_STATUS0                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0920)
#define REG_PUB_QOSC_AHB_LATMON_LM2_STATUS1                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0924)
#define REG_PUB_QOSC_AHB_LATMON_LM2_STATUS2                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0928)
#define REG_PUB_QOSC_AHB_LATMON_LM2_STATUS3                 SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x092C)
#define REG_PUB_QOSC_AHB_LATMON_STATUS                      SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0940)
#define REG_PUB_QOSC_AHB_BWMON_EB                           SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A00)
#define REG_PUB_QOSC_AHB_BWMON0_UP_WBW_SET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A04)
#define REG_PUB_QOSC_AHB_BWMON0_UP_RBW_SET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A08)
#define REG_PUB_QOSC_AHB_BWMON1_UP_WBW_SET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A0C)
#define REG_PUB_QOSC_AHB_BWMON1_UP_RBW_SET                  SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A10)
#define REG_PUB_QOSC_AHB_BWMON_STATUS                       SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A70)
#define REG_PUB_QOSC_AHB_BWMON0_WBW_CNT                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A80)
#define REG_PUB_QOSC_AHB_BWMON0_RBW_CNT                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A84)
#define REG_PUB_QOSC_AHB_BWMON1_WBW_CNT                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A88)
#define REG_PUB_QOSC_AHB_BWMON1_RBW_CNT                     SCI_ADDR(CTL_PUB_QOSC_AHB_BASE, 0x0A8C)

/* bits definitions for REG_PUB_QOSC_AHB_QOS_CTRL_EB, [0x30210000] */
#define BIT_PUB_QOSC_AHB_QOS_CTRL_ENABLE                    ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_QOS_CTRL_RESET, [0x30210004] */
#define BIT_PUB_QOSC_AHB_QOS_URGENT_COUNT_RESET             ( BIT(1) )
#define BIT_PUB_QOSC_AHB_QOS_CTRL_RESET                     ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_CLK_CTRL, [0x30210008] */
#define BIT_PUB_QOSC_AHB_QOSC_CFG_CLK_AUTO_GATE_EN          ( BIT(9) )
#define BIT_PUB_QOSC_AHB_QOSC_CFG_CLK_EB                    ( BIT(8) )
#define BIT_PUB_QOSC_AHB_QOSC_CLK_TICK_ENABLE               ( BIT(4) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMIT_AUTO_GATE_EN         ( BIT(1) )
#define BIT_PUB_QOSC_AHB_QOSC_PORT_CLK_AUTO_GATE_EN         ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_PORT_ENABLE, [0x3021000C] */
#define BIT_PUB_QOSC_AHB_QOSC_PORT_ENABLE(x)                ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNTER_EN, [0x30210010] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNTER_EN_RD(x)           ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNTER_EN_WR(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_AXURGENT_EN, [0x30210014] */
#define BIT_PUB_QOSC_AHB_QOSC_ARURGENT_EN(x)                ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_AWURGENT_EN(x)                ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_EN, [0x30210018] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_EN_RD(x)           ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_EN_WR(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_CFG, [0x3021001C] */
#define BIT_PUB_QOSC_AHB_QOSC_NO_SV_BW_SLICE_BYPASS         ( BIT(28) )
#define BIT_PUB_QOSC_AHB_QOSC_DFS_FREQ(x)                   ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)) )
#define BIT_PUB_QOSC_AHB_QOSC_DFS_PAUSE_ENABLE              ( BIT(21) )
#define BIT_PUB_QOSC_AHB_QOSC_MODE                          ( BIT(20) )
#define BIT_PUB_QOSC_AHB_QOSC_UG_ULTRA_OSTD_ENABLE          ( BIT(17) )
#define BIT_PUB_QOSC_AHB_QOSC_UG_HIGH_OSTD_ENABLE           ( BIT(16) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_NORM_BYPASS(x)            ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH0, [0x30210020] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH0(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH0(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH1, [0x30210024] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH1(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH1(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH2, [0x30210028] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH2(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH2(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH3, [0x3021002C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH3(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH3(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH4, [0x30210030] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH4(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH4(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH5, [0x30210034] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH5(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH5(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH6, [0x30210038] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH6(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH6(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH7, [0x3021003C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_WR_CH7(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_WR_CH7(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH0, [0x30210050] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH0(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH0(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH1, [0x30210054] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH1(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH1(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH2, [0x30210058] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH2(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH2(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH3, [0x3021005C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH3(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH3(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH4, [0x30210060] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH4(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH4(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH5, [0x30210064] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH5(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH5(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH6, [0x30210068] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH6(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH6(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH7, [0x3021006C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_ULTRA_RD_CH7(x)  ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_QOSC_SV_THRESHOLD_HIGH_RD_CH7(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH0, [0x30210080] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH0(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH1, [0x30210084] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH1(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH2, [0x30210088] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH2(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH3, [0x3021008C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH3(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH4, [0x30210090] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH4(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH5, [0x30210094] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH5(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH6, [0x30210098] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH6(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH7, [0x3021009C] */
#define BIT_PUB_QOSC_AHB_QOSC_SV_COUNT_OFFSET_CH7(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW0, [0x302100B0] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH7(x)       ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH6(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH5(x)       ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH4(x)       ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH3(x)       ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH2(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH1(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW_CH0(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_TIMING_WINDOW1, [0x302100B4] */

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH0, [0x302100C0] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH0(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH0(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH1, [0x302100C4] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH1(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH1(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH2, [0x302100C8] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH2(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH2(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH3, [0x302100CC] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH3(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH3(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH4, [0x302100D0] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH4(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH4(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH5, [0x302100D4] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH5(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH5(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH6, [0x302100D8] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH6(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH6(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH7, [0x302100DC] */
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_RD_CH7(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_WR_CH7(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH8, [0x302100E0] */

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_BW_LIMITER_MAX_CH9, [0x302100E4] */

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_FORCE_URGENT_HIGH_EN, [0x302100F0] */
#define BIT_PUB_QOSC_AHB_QOSC_FORCE_URGENT_HIGH_EN_RD(x)    ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_FORCE_URGENT_HIGH_EN_WR(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_FORCE_URGENT_ULTRA_EN, [0x302100F4] */
#define BIT_PUB_QOSC_AHB_QOSC_FORCE_URGENT_ULTRA_EN_RD(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_FORCE_URGENT_ULTRA_EN_WR(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_LATMON_AXURGENT_EN, [0x302100F8] */
#define BIT_PUB_QOSC_AHB_QOSC_LATMON_ARURGENT_EN(x)         ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_LATMON_AWURGENT_EN(x)         ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH0, [0x30210100] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH0(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH0(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH0(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH0(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH0(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH0(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH0(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH0(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH1, [0x30210104] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH1(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH1(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH1(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH1(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH1(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH1(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH1(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH1(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH2, [0x30210108] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH2(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH2(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH2(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH2(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH2(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH2(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH2(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH2(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH3, [0x3021010C] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH3(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH3(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH3(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH3(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH3(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH3(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH3(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH3(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH4, [0x30210110] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH4(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH4(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH4(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH4(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH4(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH4(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH4(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH4(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH5, [0x30210114] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH5(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH5(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH5(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH5(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH5(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH5(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH5(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH5(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH6, [0x30210118] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH6(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH6(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH6(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH6(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH6(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH6(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH6(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH6(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH7, [0x3021011C] */
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_RD_CH7(x)     ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_ULTRA_WR_CH7(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_RD_CH7(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_HIGH_WR_CH7(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_RD_CH7(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_NORM_WR_CH7(x)      ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_RD_CH7(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOSC_QOS_VALUE_LOW_WR_CH7(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH8, [0x30210120] */

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_QOS_VALUE_CH9, [0x30210124] */

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_STATUS0, [0x30210200] */
#define BIT_PUB_QOSC_AHB_QOSC_STATUS0(x)                    ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_STATUS1, [0x30210204] */
#define BIT_PUB_QOSC_AHB_QOSC_STATUS1(x)                    ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_STATUS2, [0x30210208] */
#define BIT_PUB_QOSC_AHB_QOSC_STATUS2(x)                    ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH0, [0x30210210] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH0(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH0(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH0(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH0(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH1, [0x30210214] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH1(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH1(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH1(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH1(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH2, [0x30210218] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH2(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH2(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH2(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH2(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH3, [0x3021021C] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH3(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH3(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH3(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH3(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH4, [0x30210220] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH4(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH4(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH4(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH4(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH5, [0x30210224] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH5(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH5(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH5(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH5(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH6, [0x30210228] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH6(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH6(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH6(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH6(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_URGENT_COUNT_CH7, [0x3021022C] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_RD_CH7(x)       ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_RD_CH7(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_COUNT_WR_CH7(x)       ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_COUNT_WR_CH7(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_DBG_MON, [0x30210280] */
#define BIT_PUB_QOSC_AHB_QOS_DBG_MON_SEL(x)                 ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_QOS_DBG_MON_EB                     ( BIT(1) )
#define BIT_PUB_QOSC_AHB_QOS_DBG_MON_START                  ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_QOSC_MON_STATUS, [0x30210284] */
#define BIT_PUB_QOSC_AHB_QOSC_MON_STATUS(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOS_CTRL_EB, [0x30210400] */
#define BIT_PUB_QOSC_AHB_M1_QOS_CTRL_ENABLE                 ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOS_CTRL_RESET, [0x30210404] */
#define BIT_PUB_QOSC_AHB_M1_QOS_CTRL_RESET                  ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_CLK_CTRL, [0x30210408] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_CFG_CLK_EB                 ( BIT(8) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_CLK_TICK_ENABLE(x)         ( (x) << 4  & (BIT(4)|BIT(5)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMIT_AUTO_GATE_EN      ( BIT(1) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_PORT_CLK_AUTO_GATE_EN      ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_PORT_ENABLE, [0x3021040C] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_PORT_ENABLE(x)             ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNTER_EN, [0x30210410] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_COUNTER_EN_RD(x)        ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_COUNTER_EN_WR(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_AXURGENT_EN, [0x30210414] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_ARURGENT_EN(x)             ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_AWURGENT_EN(x)             ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_EN, [0x30210418] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_EN_RD(x)        ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_EN_WR(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_CFG, [0x3021041C] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_NO_SV_BW_SLICE_BYPASS      ( BIT(28) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_DFS_PAUSE_ENABLE           ( BIT(21) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_MODE                       ( BIT(20) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_UG_ULTRA_OSTD_ENABLE       ( BIT(17) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_UG_HIGH_OSTD_ENABLE        ( BIT(16) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_NORM_BYPASS(x)         ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH0, [0x30210420] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_ULTRA_WR_CH0(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH0(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH1, [0x30210424] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_ULTRA_WR_CH1(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_WR_CH1(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH0, [0x30210430] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_ULTRA_RD_CH0(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH0(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH1, [0x30210434] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_ULTRA_RD_CH1(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_THRESHOLD_HIGH_RD_CH1(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH0, [0x30210440] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH0(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH1, [0x30210444] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_SV_COUNT_OFFSET_CH1(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_BW_TIMING_WINDOW0, [0x30210450] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_TIMING_WINDOW_CH1(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_TIMING_WINDOW_CH0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_CH0, [0x30210460] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_RD_CH0(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_WR_CH0(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_CH1, [0x30210464] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_RD_CH1(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_BW_LIMITER_MAX_WR_CH1(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_HIGH_EN, [0x30210470] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_HIGH_EN_RD(x) ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_HIGH_EN_WR(x) ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_ULTRA_EN, [0x30210474] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_ULTRA_EN_RD(x) ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_FORCE_URGENT_ULTRA_EN_WR(x) ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_LATMON_AXURGENT_EN, [0x30210478] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_LATMON_ARURGENT_EN(x)      ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_LATMON_AWURGENT_EN(x)      ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_CH0, [0x30210480] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_ULTRA_RD_CH0(x)  ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_ULTRA_WR_CH0(x)  ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_HIGH_RD_CH0(x)   ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_HIGH_WR_CH0(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_NORM_RD_CH0(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_NORM_WR_CH0(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_LOW_RD_CH0(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_LOW_WR_CH0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_CH1, [0x30210484] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_ULTRA_RD_CH1(x)  ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_ULTRA_WR_CH1(x)  ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_HIGH_RD_CH1(x)   ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_HIGH_WR_CH1(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_NORM_RD_CH1(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_NORM_WR_CH1(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_LOW_RD_CH1(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_M1_QOSC_QOS_VALUE_LOW_WR_CH1(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_STATUS0, [0x30210500] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_STATUS0(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_STATUS1, [0x30210504] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_STATUS1(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_STATUS2, [0x30210508] */
#define BIT_PUB_QOSC_AHB_M1_QOSC_STATUS2(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_URGENT_COUNT_CH0, [0x30210510] */
#define BIT_PUB_QOSC_AHB_M1_URGENT_ULTRA_COUNT_RD_CH0(x)    ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_HIGH_COUNT_RD_CH0(x)     ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_ULTRA_COUNT_WR_CH0(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_HIGH_COUNT_WR_CH0(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M1_QOSC_URGENT_COUNT_CH1, [0x30210514] */
#define BIT_PUB_QOSC_AHB_M1_URGENT_ULTRA_COUNT_RD_CH1(x)    ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_HIGH_COUNT_RD_CH1(x)     ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_ULTRA_COUNT_WR_CH1(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M1_URGENT_HIGH_COUNT_WR_CH1(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOS_CTRL_EB, [0x30210600] */
#define BIT_PUB_QOSC_AHB_M2_QOS_CTRL_ENABLE                 ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOS_CTRL_RESET, [0x30210604] */
#define BIT_PUB_QOSC_AHB_M2_QOS_CTRL_RESET                  ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_CLK_CTRL, [0x30210608] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_CFG_CLK_EB                 ( BIT(8) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_CLK_TICK_ENABLE(x)         ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMIT_AUTO_GATE_EN      ( BIT(1) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_PORT_CLK_AUTO_GATE_EN      ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_PORT_ENABLE, [0x3021060C] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_PORT_ENABLE(x)             ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNTER_EN, [0x30210610] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_COUNTER_EN_RD(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_COUNTER_EN_WR(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_AXURGENT_EN, [0x30210614] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_ARURGENT_EN(x)             ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_AWURGENT_EN(x)             ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_EN, [0x30210618] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_EN_RD(x)        ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_EN_WR(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_CFG, [0x3021061C] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_NO_SV_BW_SLICE_BYPASS      ( BIT(28) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_DFS_PAUSE_ENABLE           ( BIT(21) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_MODE                       ( BIT(20) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_UG_ULTRA_OSTD_ENABLE       ( BIT(17) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_UG_HIGH_OSTD_ENABLE        ( BIT(16) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_NORM_BYPASS(x)         ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH0, [0x30210620] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_WR_CH0(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH0(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH1, [0x30210624] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_WR_CH1(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH1(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH2, [0x30210628] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_WR_CH2(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_WR_CH2(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH0, [0x30210630] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_RD_CH0(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH0(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH1, [0x30210634] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_RD_CH1(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH1(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH2, [0x30210638] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_ULTRA_RD_CH2(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_THRESHOLD_HIGH_RD_CH2(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH0, [0x30210640] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH0(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH1, [0x30210644] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH1(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH2, [0x30210648] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_SV_COUNT_OFFSET_CH2(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_BW_TIMING_WINDOW0, [0x30210650] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_TIMING_WINDOW_CH2(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_TIMING_WINDOW_CH1(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_TIMING_WINDOW_CH0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH0, [0x30210660] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_RD_CH0(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_WR_CH0(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH1, [0x30210664] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_RD_CH1(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_WR_CH1(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_CH2, [0x30210668] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_RD_CH2(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_BW_LIMITER_MAX_WR_CH2(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_HIGH_EN, [0x30210670] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_HIGH_EN_RD(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_HIGH_EN_WR(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_ULTRA_EN, [0x30210674] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_ULTRA_EN_RD(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_FORCE_URGENT_ULTRA_EN_WR(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_LATMON_AXURGENT_EN, [0x30210678] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_LATMON_ARURGENT_EN(x)      ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_LATMON_AWURGENT_EN(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH0, [0x30210680] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_RD_CH0(x)  ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_WR_CH0(x)  ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_RD_CH0(x)   ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_WR_CH0(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_RD_CH0(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_WR_CH0(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_RD_CH0(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_WR_CH0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH1, [0x30210684] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_RD_CH1(x)  ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_WR_CH1(x)  ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_RD_CH1(x)   ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_WR_CH1(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_RD_CH1(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_WR_CH1(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_RD_CH1(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_WR_CH1(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_CH2, [0x30210688] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_RD_CH2(x)  ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_ULTRA_WR_CH2(x)  ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_RD_CH2(x)   ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_HIGH_WR_CH2(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_RD_CH2(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_NORM_WR_CH2(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_RD_CH2(x)    ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_PUB_QOSC_AHB_M2_QOSC_QOS_VALUE_LOW_WR_CH2(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_STATUS0, [0x30210700] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_STATUS0(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_STATUS1, [0x30210704] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_STATUS1(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_STATUS2, [0x30210708] */
#define BIT_PUB_QOSC_AHB_M2_QOSC_STATUS2(x)                 ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH0, [0x30210710] */
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_RD_CH0(x)    ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_RD_CH0(x)     ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_WR_CH0(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_WR_CH0(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH1, [0x30210714] */
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_RD_CH1(x)    ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_RD_CH1(x)     ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_WR_CH1(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_WR_CH1(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_M2_QOSC_URGENT_COUNT_CH2, [0x30210718] */
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_RD_CH2(x)    ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_RD_CH2(x)     ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_ULTRA_COUNT_WR_CH2(x)    ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_PUB_QOSC_AHB_M2_URGENT_HIGH_COUNT_WR_CH2(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_EB, [0x30210800] */
#define BIT_PUB_QOSC_AHB_LATMON_SW_TIMER_EN(x)              ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)) )
#define BIT_PUB_QOSC_AHB_LATMON_TIMER_SEL(x)                ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_PUB_QOSC_AHB_LATMON2_SEL                        ( BIT(16) )
#define BIT_PUB_QOSC_AHB_LATMON_AUTO_GATE_EN(x)             ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)) )
#define BIT_PUB_QOSC_AHB_LATMON_CLK_TICK_ENABLE(x)          ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)) )
#define BIT_PUB_QOSC_AHB_LATMON_ENABLE(x)                   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_RESET, [0x30210804] */
#define BIT_PUB_QOSC_AHB_LATMON_COUNT_RESET(x)              ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)) )
#define BIT_PUB_QOSC_AHB_LATMON_RESET(x)                    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM0, [0x30210808] */
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_RD_LM0(x)           ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_WR_LM0(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_URGENT_RATIO_LM0, [0x3021080C] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_RD_LM0(x)       ( (x) << 12 & (BIT(12)|BIT(13)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_WR_LM0(x)       ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_RD_LM0(x)        ( (x) << 4  & (BIT(4)|BIT(5)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_WR_LM0(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM0, [0x30210810] */
#define BIT_PUB_QOSC_AHB_LATMON_INIT_URGENT_DEB_LM0(x)      ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_SEL_LM0(x)           ( (x) << 26 & (BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_VALUE_LM0(x)         ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_LAT_SUB_ALL_RATIO_LM0(x)           ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_PERIOD_LM0(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_HW_DFS_CFG, [0x30210814] */
#define BIT_PUB_QOSC_AHB_LATMON_HW_DFS_TRIGGER_SEL_LM2(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)) )
#define BIT_PUB_QOSC_AHB_LATMON_HW_DFS_TRIGGER_SEL_LM1(x)   ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_PUB_QOSC_AHB_LATMON_HW_DFS_TRIGGER_SEL_LM0(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)) )
#define BIT_PUB_QOSC_AHB_LATMON_HW_DFS_TRIGGER_EN(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM1, [0x30210820] */
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_RD_LM1(x)           ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_WR_LM1(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_URGENT_RATIO_LM1, [0x30210824] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_RD_LM1(x)       ( (x) << 12 & (BIT(12)|BIT(13)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_WR_LM1(x)       ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_RD_LM1(x)        ( (x) << 4  & (BIT(4)|BIT(5)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_WR_LM1(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM1, [0x30210828] */
#define BIT_PUB_QOSC_AHB_LATMON_INIT_URGENT_DEB_LM1(x)      ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_SEL_LM1(x)           ( (x) << 26 & (BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_VALUE_LM1(x)         ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_LAT_SUB_ALL_RATIO_LM1(x)           ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_PERIOD_LM1(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_TAR_LAT_OFFSET_LM2, [0x30210830] */
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_RD_LM2(x)           ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_TAR_LAT_OFFSET_WR_LM2(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_PUB_QOSC_AHB_URGENT_RATIO_LM2, [0x30210834] */
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_RD_LM2(x)       ( (x) << 12 & (BIT(12)|BIT(13)) )
#define BIT_PUB_QOSC_AHB_URGENT_ULTRA_RATIO_WR_LM2(x)       ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_RD_LM2(x)        ( (x) << 4  & (BIT(4)|BIT(5)) )
#define BIT_PUB_QOSC_AHB_URGENT_HIGH_RATIO_WR_LM2(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_SUB_CFG_LM2, [0x30210838] */
#define BIT_PUB_QOSC_AHB_LATMON_INIT_URGENT_DEB_LM2(x)      ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_SEL_LM2(x)           ( (x) << 26 & (BIT(26)|BIT(27)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_VALUE_LM2(x)         ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_PUB_QOSC_AHB_LAT_SUB_ALL_RATIO_LM2(x)           ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_TIMER_LAT_SUB_PERIOD_LM2(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM0_STATUS0, [0x30210900] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_WR_LM0(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM0_STATUS1, [0x30210904] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_WR_LM0(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM0_STATUS2, [0x30210908] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_RD_LM0(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM0_STATUS3, [0x3021090C] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_RD_LM0(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM1_STATUS0, [0x30210910] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_WR_LM1(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM1_STATUS1, [0x30210914] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_WR_LM1(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM1_STATUS2, [0x30210918] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_RD_LM1(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM1_STATUS3, [0x3021091C] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_RD_LM1(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM2_STATUS0, [0x30210920] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_WR_LM2(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM2_STATUS1, [0x30210924] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_WR_LM2(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM2_STATUS2, [0x30210928] */
#define BIT_PUB_QOSC_AHB_LATENCY_ACTUAL_RD_LM2(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_LM2_STATUS3, [0x3021092C] */
#define BIT_PUB_QOSC_AHB_LATENCY_TARGET_RD_LM2(x)           ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_LATMON_STATUS, [0x30210940] */
#define BIT_PUB_QOSC_AHB_LATMON2_UPDATE_FLAG_CLR            ( BIT(22) )
#define BIT_PUB_QOSC_AHB_LATMON1_UPDATE_FLAG_CLR            ( BIT(21) )
#define BIT_PUB_QOSC_AHB_LATMON0_UPDATE_FLAG_CLR            ( BIT(20) )
#define BIT_PUB_QOSC_AHB_LATMON2_UPDATE_FLAG                ( BIT(18) )
#define BIT_PUB_QOSC_AHB_LATMON1_UPDATE_FLAG                ( BIT(17) )
#define BIT_PUB_QOSC_AHB_LATMON0_UPDATE_FLAG                ( BIT(16) )
#define BIT_PUB_QOSC_AHB_LATMON_COUNTER_OV_ST(x)            ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON_EB, [0x30210A00] */
#define BIT_PUB_QOSC_AHB_BWMON_F_UP_REQ_EN(x)               ( (x) << 12 & (BIT(12)|BIT(13)) )
#define BIT_PUB_QOSC_AHB_BWMON_RBW_EN(x)                    ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_PUB_QOSC_AHB_BWMON_WBW_EN(x)                    ( (x) << 4  & (BIT(4)|BIT(5)) )
#define BIT_PUB_QOSC_AHB_BWMON_ENABLE(x)                    ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON0_UP_WBW_SET, [0x30210A04] */
#define BIT_PUB_QOSC_AHB_BWMON0_UP_WBW_SET(x)               ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON0_UP_RBW_SET, [0x30210A08] */
#define BIT_PUB_QOSC_AHB_BWMON0_UP_RBW_SET(x)               ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON1_UP_WBW_SET, [0x30210A0C] */
#define BIT_PUB_QOSC_AHB_BWMON1_UP_WBW_SET(x)               ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON1_UP_RBW_SET, [0x30210A10] */
#define BIT_PUB_QOSC_AHB_BWMON1_UP_RBW_SET(x)               ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON_STATUS, [0x30210A70] */
#define BIT_PUB_QOSC_AHB_BWMON1_UPDATE_FLAG_CLR             ( BIT(9) )
#define BIT_PUB_QOSC_AHB_BWMON0_UPDATE_FLAG_CLR             ( BIT(8) )
#define BIT_PUB_QOSC_AHB_BWMON1_UPDATE_FLAG                 ( BIT(1) )
#define BIT_PUB_QOSC_AHB_BWMON0_UPDATE_FLAG                 ( BIT(0) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON0_WBW_CNT, [0x30210A80] */
#define BIT_PUB_QOSC_AHB_BWMON0_WBW_CNT(x)                  ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON0_RBW_CNT, [0x30210A84] */
#define BIT_PUB_QOSC_AHB_BWMON0_RBW_CNT(x)                  ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON1_WBW_CNT, [0x30210A88] */
#define BIT_PUB_QOSC_AHB_BWMON1_WBW_CNT(x)                  ( (x) )

/* bits definitions for REG_PUB_QOSC_AHB_BWMON1_RBW_CNT, [0x30210A8C] */
#define BIT_PUB_QOSC_AHB_BWMON1_RBW_CNT(x)                  ( (x) )

/* vars definitions for controller CTL_PUB_QOSC_AHB */


#endif /* __PUB_QOSC_AHB_H____ */
