#
# (C) Copyright 2000-2007
# linhua.xu, SPRD Software Engineering.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_SPRD_PINCTRL) += sprd_pinctrl.o
obj-$(CONFIG_SHARKL5PRO_PINCTRL) += sprd_pinctrl_sharkl5pro.o
obj-$(CONFIG_QOGIRL6_PINCTRL) += sprd_pinctrl_qogirl6.o
