/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

/*
 * SVN URL      : http://shsvn06/svn/CHIP/Interface/SharkL6/Autoreg/SHARKL6_RTL_0.5_DV_00/Analog/Analog_G3 Control Register.xls;Analog_G3
 *     Revision : 208573
 *     Author   : {author}
 *     Date     : {date}
 */

#ifndef __ANLG_PHY_G3_H____
#define __ANLG_PHY_G3_H____

/* Some defs, in case these are not defined elsewhere */
#ifndef SCI_IOMAP
#define SCI_IOMAP(_b_) ( (_b_) )
#endif

#ifndef SCI_ADDR
#define SCI_ADDR(_b_, _o_) ( (_b_) + (_o_) )
#endif

#ifndef CTL_ANLG_PHY_G3_BASE
#define CTL_ANLG_PHY_G3_BASE            SCI_IOMAP(0x64580000)
#endif

/* registers definitions for CTL_ANLG_PHY_G3, 0x64580000 */
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL0            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0000)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL1            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0004)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_PLL_CLK_CTRL          SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0008)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_PERFOR           SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x000C)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL2            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0010)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_RESERVED         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0014)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_BIST_CTRL        SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0018)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_PWR_CTRL       SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x001C)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_26M_BUF        SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0020)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_EN_CTRL        SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0024)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANALOG_TEST           SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0028)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_CTRL1            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x002C)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_CTRL2            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0030)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_RSVD           SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0034)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_CTRL          SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0038)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_TEST_CLK_CTRL         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x003C)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_BB_TOP_TEST_0         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0040)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_BB_TOP_TEST_1         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0044)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_ISPPLL_CTRL0          SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0048)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_REG_SEL_CFG_0         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x004C)
#define REG_ANLG_PHY_G3_ANALOG_BB_TOP_REG_SEL_CFG_1         SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0050)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL0            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0054)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL1            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0058)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL2            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x005C)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL3            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0060)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL4            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0064)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL5            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0068)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL6            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x006C)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL7            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0070)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL8            SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0074)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX0 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0078)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX1 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x007C)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX2 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0080)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX3 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0084)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX4 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0088)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX5 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x008C)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX6 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0090)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX7 SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0094)
#define REG_ANLG_PHY_G3_ANALOG_MPLL1_REG_SEL_CFG_0          SCI_ADDR(CTL_ANLG_PHY_G3_BASE, 0x0098)

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL0, [0x64580000] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_LOCK_DONE        ( BIT(18) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_REF_SEL(x)       ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_N(x)             ( (x) << 5  & (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_ICP(x)           ( (x) << 2  & (BIT(2)|BIT(3)|BIT(4)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_SDM_EN           ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_DIV_S            ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL1, [0x64580004] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_NINT(x)          ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_KINT(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_PLL_CLK_CTRL, [0x64580008] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_SINEO_RPLL_CLKOUT_EN  ( BIT(25) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_26M_SEL          ( BIT(24) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_VSET(x)          ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_26M_DIV(x)       ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_DIV_EN           ( BIT(14) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_POSTDIV          ( BIT(13) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_FREQ_DOUBLE_EN   ( BIT(12) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_SSC_CTRL(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_MOD_EN           ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CLKOUT_EN        ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_RST              ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_PD               ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_PERFOR, [0x6458000C] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CP_EN            ( BIT(8) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_LDO_TRIM(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_VCO_TEST_EN      ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_FBDIV_EN         ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CP_OFFSET(x)     ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_CTRL2, [0x64580010] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_IBIAS(x)         ( (x) << 3  & (BIT(3)|BIT(4)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_LPF(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_RESERVED, [0x64580014] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_RESERVED(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_BIST_CTRL, [0x64580018] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_BIST_CTRL(x)     ( (x) << 17 & (BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_BIST_EN          ( BIT(16) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_BIST_CNT(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_PWR_CTRL, [0x6458001C] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_AAPC_PD             ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_AAPC_PD             ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_26M_BUF, [0x64580020] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_REC_26MHZ_0_BUF_PD    ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_EN_CTRL, [0x64580024] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_CLK26MHZ_AUD_EN       ( BIT(20) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_PROBE_SEL(x)          ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_SINDRV_ENA            ( BIT(13) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_SINDRV_ENA_SQUARE     ( BIT(12) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_REC_26MHZ_SR_TRIM(x)  ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_REC_26MHZ_0_CUR_SEL(x) ( (x) << 6  & (BIT(6)|BIT(7)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_CLK26M_RESERVED(x)    ( (x) << 2  & (BIT(2)|BIT(3)|BIT(4)|BIT(5)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_SINE_DRV_SEL          ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_BB_CON_BG             ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANALOG_TEST, [0x64580028] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_ANALOG_TESTMUX(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_CTRL1, [0x6458002C] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_G0(x)            ( (x) << 24 & (BIT(24)|BIT(25)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_G1(x)            ( (x) << 22 & (BIT(22)|BIT(23)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_G2(x)            ( (x) << 20 & (BIT(20)|BIT(21)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_AAPC_LOW_V_CON      ( BIT(19) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_AAPC_D(x)           ( (x) << 5  & (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_AAPC_BPRES          ( BIT(4) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_APCOUT_SEL(x)       ( (x) << 2  & (BIT(2)|BIT(3)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_S_AAPC_RESERVED(x)    ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_CTRL2, [0x64580030] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_AAPC_D(x)           ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_AAPC_LOW_V_CON      ( BIT(5) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_AAPC_BPRES          ( BIT(4) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_APCOUT_SEL(x)       ( (x) << 2  & (BIT(2)|BIT(3)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_M_AAPC_RESERVED(x)    ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_RSVD, [0x64580034] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_ANA_BB_RESERVED(x)    ( (x) << 2  & (BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_TO_LVDS_SEL(x)        ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_CTRL, [0x64580038] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_RSTB          ( BIT(22) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_EN            ( BIT(21) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_RESERVED(x)   ( (x) << 13 & (BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_LDO_EN        ( BIT(12) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_LDO_BYPASS    ( BIT(11) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_LDO_VOLTAGE_SEL(x) ( (x) << 9  & (BIT(9)|BIT(10)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_LDO_BIAS_SEL(x) ( (x) << 7  & (BIT(7)|BIT(8)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RTC100M_RC_C(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_TEST_CLK_CTRL, [0x6458003C] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_TEST_CLK_EN           ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_TEST_CLK_DIV(x)       ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_BB_TOP_TEST_0, [0x64580040] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_MAX_RANGE(x)     ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_MIN_RANGE(x)     ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_RSTN             ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_BB_TOP_TEST_1, [0x64580044] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_STEP_SEL(x)      ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)|BIT(9)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_AAPC_RAMP_GEN_SEL     ( BIT(5) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_PD_SEL_RFTI_OR_PMU ( BIT(4) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RPLL_RST_SEL_RFTI_OR_PMU ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_DBG_SEL_RTC100M_LDO_EN ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_DBG_SEL_RTC100M_LDO_BYPASS ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_RCO100M_POWER_MODE_SEL ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_ISPPLL_CTRL0, [0x64580048] */
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_TO_26MLINE_N_SEL(x)   ( (x) << 3  & (BIT(3)|BIT(4)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_TO_26MLINE_S_SEL(x)   ( (x) << 1  & (BIT(1)|BIT(2)) )
#define BIT_ANLG_PHY_G3_ANALOG_BB_TOP_BB_BG_RBIAS_MODE      ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_REG_SEL_CFG_0, [0x6458004C] */
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_REF_SEL  ( BIT(31) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_N        ( BIT(30) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_SDM_EN   ( BIT(29) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_DIV_S    ( BIT(28) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_NINT     ( BIT(27) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_KINT     ( BIT(26) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_26M_DIV  ( BIT(25) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_DIV_EN   ( BIT(24) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_MOD_EN   ( BIT(23) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_CLKOUT_EN ( BIT(22) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_RST      ( BIT(21) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_PD       ( BIT(20) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_IBIAS    ( BIT(19) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_LPF      ( BIT(18) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_RESERVED ( BIT(17) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_BIST_CTRL ( BIT(16) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RPLL_BIST_EN  ( BIT(15) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_AAPC_PD     ( BIT(14) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_AAPC_PD     ( BIT(13) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_REC_26MHZ_0_BUF_PD ( BIT(12) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_CLK26MHZ_AUD_EN ( BIT(11) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_SINDRV_ENA    ( BIT(10) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_SINDRV_ENA_SQUARE ( BIT(9) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_AAPC_G0       ( BIT(8) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_AAPC_G1       ( BIT(7) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_AAPC_G2       ( BIT(6) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_AAPC_LOW_V_CON ( BIT(5) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_AAPC_D      ( BIT(4) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_AAPC_BPRES  ( BIT(3) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_APCOUT_SEL  ( BIT(2) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_S_AAPC_RESERVED ( BIT(1) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_AAPC_D      ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_BB_TOP_REG_SEL_CFG_1, [0x64580050] */
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_AAPC_LOW_V_CON ( BIT(6) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_AAPC_BPRES  ( BIT(5) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_APCOUT_SEL  ( BIT(4) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_M_AAPC_RESERVED ( BIT(3) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RTC100M_RSTB  ( BIT(2) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RTC100M_EN    ( BIT(1) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_BB_TOP_RTC100M_RC_C  ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL0, [0x64580054] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_LOCK_DONE        ( BIT(17) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CLKIN_SEL        ( BIT(16) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N(x)             ( (x) << 5  & (BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP(x)           ( (x) << 2  & (BIT(2)|BIT(3)|BIT(4)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_SDM_EN           ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_DIV_S            ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL1, [0x64580058] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_NINT(x)          ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_KINT(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL2, [0x6458005C] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_DIV32_EN         ( BIT(14) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV          ( BIT(13) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_FREQ_DOUBLE_EN   ( BIT(12) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CCS_CTRL(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_MOD_EN           ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CLKOUT_EN        ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_RST              ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_PD               ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL3, [0x64580060] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_R2_SEL(x)        ( (x) << 22 & (BIT(22)|BIT(23)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_R3_SEL(x)        ( (x) << 20 & (BIT(20)|BIT(21)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_C1_SEL(x)        ( (x) << 18 & (BIT(18)|BIT(19)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_C2_SEL(x)        ( (x) << 16 & (BIT(16)|BIT(17)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_KVCO_SEL(x)      ( (x) << 14 & (BIT(14)|BIT(15)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCO_TEST_INTSEL(x) ( (x) << 11 & (BIT(11)|BIT(12)|BIT(13)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCO_TEST_INT     ( BIT(10) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CP_EN            ( BIT(9) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_LDO_TRIM(x)      ( (x) << 5  & (BIT(5)|BIT(6)|BIT(7)|BIT(8)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCO_TEST_EN      ( BIT(4) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_FBDIV_EN         ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CP_OFFSET(x)     ( (x) << 1  & (BIT(1)|BIT(2)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCOBUF_EN        ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL4, [0x64580064] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_RESERVED(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL5, [0x64580068] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_BIST_CTRL(x)     ( (x) << 17 & (BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_BIST_EN          ( BIT(16) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_BIST_CNT(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL6, [0x6458006C] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_26MBUFFER_PD     ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL7, [0x64580070] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_MODE(x)     ( (x) << 17 & (BIT(17)|BIT(18)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_INI(x)      ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_TRIG        ( BIT(11) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_FREQ_DIFF_EN     ( BIT(10) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_WAITCNT(x)  ( (x) << 8  & (BIT(8)|BIT(9)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_POLARITY    ( BIT(7) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_DONE        ( BIT(6) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_OUT(x)      ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_CPPD        ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CTRL8, [0x64580074] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCTRLH_SEL(x)    ( (x) << 17 & (BIT(17)|BIT(18)|BIT(19)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCTRLL_SEL(x)    ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_RG_CLOSELOOP_EN  ( BIT(13) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCO_BANK_SEL(x)  ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_VCTRL_HIGH  ( BIT(7) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_CALI_VCTRL_LOW   ( BIT(6) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_VCO_BANK_SEL_OFFSET ( BIT(5) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ADJ_MANUAL_PD    ( BIT(4) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ISO_SW_EN        ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_TEST_CLK_EN            ( BIT(2) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_TEST_SEL               ( BIT(1) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_26MBUFFER_CLKOUT_EN ( BIT(0) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX0, [0x64580078] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX0(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX0   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX1, [0x6458007C] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX1(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX1   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX1(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX2, [0x64580080] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX2(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX2   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX2(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX3, [0x64580084] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX3(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX3   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX3(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX4, [0x64580088] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX4(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX4   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX4(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX5, [0x6458008C] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX5(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX5   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX5(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX6, [0x64580090] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX6(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX6   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX6(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_PROMETHEUS_DVFS_INDEX7, [0x64580094] */
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_N_INDEX7(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_POSTDIV_INDEX7   ( BIT(3) )
#define BIT_ANLG_PHY_G3_ANALOG_MPLL1_MPLL1_ICP_INDEX7(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_ANLG_PHY_G3_ANALOG_MPLL1_REG_SEL_CFG_0, [0x64580098] */
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_N        ( BIT(7) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_ICP      ( BIT(6) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_DIV32_EN ( BIT(5) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_POSTDIV  ( BIT(4) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_CLKOUT_EN ( BIT(3) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_RST      ( BIT(2) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_PD       ( BIT(1) )
#define BIT_ANLG_PHY_G3_DBG_SEL_ANALOG_MPLL1_MPLL1_26MBUFFER_PD ( BIT(0) )

/* vars definitions for controller CTL_ANLG_PHY_G3 */


#endif /* __ANLG_PHY_G3_H____ */
