/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

/*
 * SVN URL      : http://shsvn06/svn/CHIP/Interface/SharkL6/Autoreg/DVFS/SharkL6 TOP DVFS Control Register.xlsx;Sheet1
 *     Revision : 228583
 *     Author   : {author}
 *     Date     : {date}
 */

#ifndef __TOP_DVFS_APB_H____
#define __TOP_DVFS_APB_H____

/* Some defs, in case these are not defined elsewhere */
#ifndef SCI_IOMAP
#define SCI_IOMAP(_b_) ( (_b_) )
#endif

#ifndef SCI_ADDR
#define SCI_ADDR(_b_, _o_) ( (_b_) + (_o_) )
#endif

#ifndef CTL_TOP_DVFS_APB_BASE
#define CTL_TOP_DVFS_APB_BASE           SCI_IOMAP(0x64014000)
#endif

/* registers definitions for CTL_TOP_DVFS_APB, 0x64014000 */
#define REG_TOP_DVFS_APB_DCDC_MM_FIX_VOLTAGE_CTRL           SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0000)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_WAIT_WINDOW_CFG       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0004)
#define REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY_CFG0      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0008)
#define REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY_CFG1      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x000C)
#define REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY_CFG0    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0010)
#define REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY_CFG1    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0014)
#define REG_TOP_DVFS_APB_DCDC_MM_SW_DVFS_CTRL               SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0018)
#define REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_JUDGE_BYPASS       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x001C)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_STATE_DBG             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0020)
#define REG_TOP_DVFS_APB_DCDC_MODEM_FIX_VOLTAGE_CTRL        SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0024)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_WAIT_WINDOW_CFG    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0028)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY_CFG0   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x002C)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY_CFG1   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0030)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY_CFG0 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0034)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY_CFG1 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0038)
#define REG_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_CTRL            SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x003C)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_JUDGE_BYPASS    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0040)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_STATE_DBG          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0044)
#define REG_TOP_DVFS_APB_DCDC_CPU0_FIX_VOLTAGE_CTRL         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0048)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_WAIT_WINDOW_CFG     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x004C)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG2    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0050)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG1    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0054)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG0    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0058)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG2  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x005C)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG1  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0060)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG0  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0064)
#define REG_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_CTRL             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0068)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_JUDGE_BYPASS     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x006C)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_STATE_DBG           SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0070)
#define REG_TOP_DVFS_APB_DCDC_CPU1_FIX_VOLTAGE_CTRL         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0074)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_WAIT_WINDOW_CFG     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0078)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG2    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x007C)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG1    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0080)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG0    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0084)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG2  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0088)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG1  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x008C)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG0  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0090)
#define REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0094)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_JUDGE_BYPASS     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0098)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG           SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x009C)
#define REG_TOP_DVFS_APB_DCDC_STEP_TUNE_CFG                 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00A0)
#define REG_TOP_DVFS_APB_TOP_DVFS_CLK_CTRL                  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00A4)
#define REG_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL               SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00A8)
#define REG_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL            SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00AC)
#define REG_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00B0)
#define REG_TOP_DVFS_APB_DCDC_MM_VOL_TUNE_UP_CFG            SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00B4)
#define REG_TOP_DVFS_APB_DCDC_MM_VOL_TUNE_DOWN_CFG          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00B8)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOL_TUNE_UP_CFG         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00BC)
#define REG_TOP_DVFS_APB_DCDC_MODEM_VOL_TUNE_DOWN_CFG       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00C0)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_UP_CFG0         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00C4)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_UP_CFG1         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00C8)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_DOWN_CFG0       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00CC)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_DOWN_CFG1       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00D0)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_UP_CFG0         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00D4)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_UP_CFG1         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00D8)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_DOWN_CFG0       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00DC)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_DOWN_CFG1       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00E0)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_VOLTAGE_VALUE0        SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00E4)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_VOLTAGE_VALUE1        SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00E8)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_VOLTAGE_VALUE0     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00EC)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_VOLTAGE_VALUE1     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00F0)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE0      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00F4)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE1      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00F8)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE2      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x00FC)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE0      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0100)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE1      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0104)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE2      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0108)
#define REG_TOP_DVFS_APB_DCDC_CPU_STEP_TUNE_VOL             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x010C)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG3    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0110)
#define REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG3  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0114)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG3    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0118)
#define REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG3  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x011C)
#define REG_TOP_DVFS_APB_DCDC_CPU1_TYPE_SEL_CFG             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0120)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_DVFS_VOLTAGE_VALUE0 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x012C)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_DVFS_VOLTAGE_VALUE1 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0130)
#define REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_ADI         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0134)
#define REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_I2C         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0138)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_STATE_DBG1            SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x013C)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_STATE_DBG1         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0140)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_STATE_DBG1          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0144)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG1          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0148)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG2          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x014C)
#define REG_TOP_DVFS_APB_SUBSYS_SW_DVFS_EN_CFG              SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0150)
#define REG_TOP_DVFS_APB_WTLCP_DVFS_URGENCY_CFG             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0154)
#define REG_TOP_DVFS_APB_DCDC_DVFS_CNT_CFG                  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0158)
#define REG_TOP_DVFS_APB_DCDC_MM_DVFS_CNT                   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x015C)
#define REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_CNT                SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0160)
#define REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_CNT                 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0164)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_CNT                 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0168)
#define REG_TOP_DVFS_APB_DVFS_IDLE_VOL_CFG                  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x016C)
#define REG_TOP_DVFS_APB_SHARE_DCDC_CFG                     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0170)
#define REG_TOP_DVFS_APB_DCDC_TOP_FIX_VOLTAGE_CTRL          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0174)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_WAIT_WINDOW_CFG      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0178)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY_CFG0     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x017C)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY_CFG1     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0180)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY_CFG0   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0184)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY_CFG1   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0188)
#define REG_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_CTRL              SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x018C)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_JUDGE_BYPASS      SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0190)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_STATE_DBG            SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0194)
#define REG_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL              SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x0198)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOL_TUNE_UP_CFG           SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x019C)
#define REG_TOP_DVFS_APB_DCDC_TOP_VOL_TUNE_DOWN_CFG         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01A0)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_VOLTAGE_VALUE0       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01A4)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_VOLTAGE_VALUE1       SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01A8)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_STATE_DBG1           SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01AC)
#define REG_TOP_DVFS_APB_DCDC_TOP_DVFS_CNT                  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01B0)
#define REG_TOP_DVFS_APB_DVFS_IDLE_VOL_EN                   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01B4)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_UP_CFG0 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01B8)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_UP_CFG1 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01BC)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_DOWN_CFG0 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01C0)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_DOWN_CFG1 SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01C4)
#define REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_CFG             SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01C8)
#define REG_TOP_DVFS_APB_DVFS_TOP_IRQ_EN                    SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01CC)
#define REG_TOP_DVFS_APB_DVFS_TOP_IRQ_CLR                   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01D0)
#define REG_TOP_DVFS_APB_DVFS_TOP_IRQ_RAW                   SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01D4)
#define REG_TOP_DVFS_APB_DVFS_TOP_IRQ_MASK                  SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01D8)
#define REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG3          SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01DC)
#define REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_ADI_2ND     SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01E0)
#define REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG0         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01F0)
#define REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG1         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01F4)
#define REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG2         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01F8)
#define REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG3         SCI_ADDR(CTL_TOP_DVFS_APB_BASE, 0x01FC)

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_FIX_VOLTAGE_CTRL, [0x64014000] */
#define BIT_TOP_DVFS_APB_DCDC_MM_FIX_VOLTAGE(x)             ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_FIX_VOLTAGE_EN             ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_WAIT_WINDOW_CFG, [0x64014004] */
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_UP_WINDOW(x)          ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_DOWN_WINDOW(x)        ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY_CFG0, [0x64014008] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY_BAK(x)    ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY2(x)       ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY_CFG1, [0x6401400C] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY1(x)       ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_DELAY0(x)       ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY_CFG0, [0x64014010] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY_BAK(x)  ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY2(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY_CFG1, [0x64014014] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY1(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_DELAY0(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_SW_DVFS_CTRL, [0x64014018] */
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_ACK                   ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_TUNE_EN                 ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_VOLTAGE_SW(x)         ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_JUDGE_VOLTAGE_SW(x)        ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_REQ_SW                ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOLTAGE_JUDGE_BYPASS, [0x6401401C] */
#define BIT_TOP_DVFS_APB_REG_AUDCP_SYS_VOLTAGE_MEET_BYP     ( BIT(2) )
#define BIT_TOP_DVFS_APB_REG_GPU_TOP_VOLTAGE_MEET_BYP       ( BIT(1) )
#define BIT_TOP_DVFS_APB_REG_MM_SYS_VOLTAGE_MEET_BYP        ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_STATE_DBG, [0x64014020] */
#define BIT_TOP_DVFS_APB_DCDC_MM_JUDGE_VOLTAGE(x)           ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_CURRENT_VOLTAGE(x)         ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_CNT(x)                ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_STATE(x)              ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_FIX_VOLTAGE_CTRL, [0x64014024] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_FIX_VOLTAGE(x)          ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_FIX_VOLTAGE_EN          ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_WAIT_WINDOW_CFG, [0x64014028] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_UP_WINDOW(x)       ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_DOWN_WINDOW(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY_CFG0, [0x6401402C] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY_BAK(x) ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY2(x)    ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY_CFG1, [0x64014030] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY1(x)    ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_DELAY0(x)    ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY_CFG0, [0x64014034] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY_BAK(x) ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY2(x)  ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY_CFG1, [0x64014038] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY1(x)  ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_DELAY0(x)  ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_CTRL, [0x6401403C] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_ACK                ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_TUNE_EN              ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_VOLTAGE_SW(x)      ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_JUDGE_VOLTAGE_SW(x)     ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_REQ_SW             ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_JUDGE_BYPASS, [0x64014040] */
#define BIT_TOP_DVFS_APB_REG_AP_SYS_VOLTAGE_MEET_BYP        ( BIT(2) )
#define BIT_TOP_DVFS_APB_REG_PUBCP_SYS_VOLTAGE_MEET_BYP     ( BIT(1) )
#define BIT_TOP_DVFS_APB_REG_WTLCP_SYS_VOLTAGE_MEET_BYP     ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_STATE_DBG, [0x64014044] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_JUDGE_VOLTAGE(x)        ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_CURRENT_VOLTAGE(x)      ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_CNT(x)             ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_STATE(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_FIX_VOLTAGE_CTRL, [0x64014048] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_FIX_VOLTAGE(x)           ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_FIX_VOLTAGE_EN           ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_WAIT_WINDOW_CFG, [0x6401404C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_UP_WINDOW(x)        ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_DOWN_WINDOW(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG2, [0x64014050] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY5(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY4(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG1, [0x64014054] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY3(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY2(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG0, [0x64014058] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY1(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY0(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG2, [0x6401405C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY5(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY4(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG1, [0x64014060] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY3(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY2(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG0, [0x64014064] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY1(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY0(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_CTRL, [0x64014068] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_ACK                 ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_TUNE_EN               ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_VOLTAGE_SW(x)       ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_JUDGE_VOLTAGE_SW(x)      ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_REQ_SW              ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_JUDGE_BYPASS, [0x6401406C] */
#define BIT_TOP_DVFS_APB_REG_APCPU_TOP_VOLTAGE_MEET_BYP     ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_STATE_DBG, [0x64014070] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_JUDGE_VOLTAGE(x)         ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_CURRENT_VOLTAGE(x)       ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_CNT(x)              ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_STATE(x)            ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_FIX_VOLTAGE_CTRL, [0x64014074] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_FIX_VOLTAGE(x)           ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_FIX_VOLTAGE_EN           ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_WAIT_WINDOW_CFG, [0x64014078] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_UP_WINDOW(x)        ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DOWN_WINDOW(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG2, [0x6401407C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY5(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY4(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG1, [0x64014080] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY3(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY2(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG0, [0x64014084] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY1(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY0(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG2, [0x64014088] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY5(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY4(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG1, [0x6401408C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY3(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY2(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG0, [0x64014090] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY1(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY0(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL, [0x64014094] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_SW_TUNE_EN               ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_JUDGE_BYPASS, [0x64014098] */
#define BIT_TOP_DVFS_APB_REG_PROMETHEUS_VOLTAGE_MEET_BYP    ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG, [0x6401409C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_JUDGE_VOLTAGE(x)         ( (x) << 28 & (BIT(28)|BIT(29)|BIT(30)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_CURRENT_VOLTAGE(x)       ( (x) << 25 & (BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_CNT(x)              ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_I2C(x)        ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_ADI(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_STEP_TUNE_CFG, [0x640140A0] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_STEP_TUNE_EN              ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_STEP_TUNE_EN             ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_STEP_TUNE_EN             ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_STEP_TUNE_EN            ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_MM_STEP_TUNE_EN               ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_TOP_DVFS_CLK_CTRL, [0x640140A4] */
#define BIT_TOP_DVFS_APB_TOP_DVFS_AUTO_SEL_RCO_EN           ( BIT(2) )
#define BIT_TOP_DVFS_APB_CGM_TOP_DVFS_FORCE_EN              ( BIT(1) )
#define BIT_TOP_DVFS_APB_CGM_TOP_DVFS_AUTO_GATE_SEL         ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL, [0x640140A8] */
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL7(x)           ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL6(x)           ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL5(x)           ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL4(x)           ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL3(x)           ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL2(x)           ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL1(x)           ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_SW_DVFS_POLL0(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL, [0x640140AC] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL7(x)        ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL6(x)        ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL5(x)        ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL4(x)        ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL3(x)        ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL2(x)        ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL1(x)        ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_SW_DVFS_POLL0(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL, [0x640140B0] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL7(x)         ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL6(x)         ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL5(x)         ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL4(x)         ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL3(x)         ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL2(x)         ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL1(x)         ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_SW_DVFS_POLL0(x)         ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOL_TUNE_UP_CFG, [0x640140B4] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_CFG_BAK(x)      ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_CFG2(x)         ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_CFG1(x)         ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_UP_CFG0(x)         ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_VOL_TUNE_DOWN_CFG, [0x640140B8] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_CFG_BAK(x)    ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_CFG2(x)       ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_CFG1(x)       ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_DOWN_CFG0(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOL_TUNE_UP_CFG, [0x640140BC] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_CFG_BAK(x)   ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_CFG2(x)      ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_CFG1(x)      ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_UP_CFG0(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_VOL_TUNE_DOWN_CFG, [0x640140C0] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_CFG_BAK(x) ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_CFG2(x)    ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_CFG1(x)    ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_DOWN_CFG0(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_UP_CFG0, [0x640140C4] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG3(x)       ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG2(x)       ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG1(x)       ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG0(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_UP_CFG1, [0x640140C8] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG7(x)       ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG6(x)       ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG5(x)       ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_CFG4(x)       ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_DOWN_CFG0, [0x640140CC] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG3(x)     ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG2(x)     ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG1(x)     ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG0(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOL_TUNE_DOWN_CFG1, [0x640140D0] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG7(x)     ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG6(x)     ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG5(x)     ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_CFG4(x)     ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_UP_CFG0, [0x640140D4] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG3_ADI(x)   ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG2_ADI(x)   ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG1_ADI(x)   ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG0_ADI(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_UP_CFG1, [0x640140D8] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG7_ADI(x)   ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG6_ADI(x)   ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG5_ADI(x)   ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG4_ADI(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_DOWN_CFG0, [0x640140DC] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG3_ADI(x) ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG2_ADI(x) ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG1_ADI(x) ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG0_ADI(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOL_TUNE_DOWN_CFG1, [0x640140E0] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG7_ADI(x) ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG6_ADI(x) ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG5_ADI(x) ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG4_ADI(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_VOLTAGE_VALUE0, [0x640140E4] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE2(x)                ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE1(x)                ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE0(x)                ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_VOLTAGE_VALUE1, [0x640140E8] */
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE_BAK(x)             ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOLTAGE3(x)                ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_VOLTAGE_VALUE0, [0x640140EC] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE2(x)             ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE1(x)             ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE0(x)             ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_VOLTAGE_VALUE1, [0x640140F0] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE_BAK(x)          ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOLTAGE3(x)             ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE0, [0x640140F4] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE2(x)              ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE1(x)              ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE0(x)              ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE1, [0x640140F8] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE5(x)              ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE4(x)              ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE3(x)              ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE_VALUE2, [0x640140FC] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE7(x)              ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE6(x)              ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE0, [0x64014100] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE2_ADI(x)          ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE1_ADI(x)          ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE0_ADI(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE1, [0x64014104] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE5_ADI(x)          ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE4_ADI(x)          ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE3_ADI(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE_VALUE2, [0x64014108] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE7_ADI(x)          ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE6_ADI(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU_STEP_TUNE_VOL, [0x6401410C] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_STEP_VOLTAGE(x)           ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_STEP_VOLTAGE(x)            ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_STEP_VOLTAGE(x)         ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_STEP_VOLTAGE(x)          ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_STEP_VOLTAGE(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY_CFG3, [0x64014110] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY7(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_UP_DELAY6(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY_CFG3, [0x64014114] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY7(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOLTAGE_DOWN_DELAY6(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY_CFG3, [0x64014118] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY7(x)     ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_DELAY6(x)     ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY_CFG3, [0x6401411C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY7(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_DELAY6(x)   ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_TYPE_SEL_CFG, [0x64014120] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_SEL(x)                   ( (x) << 0  & (BIT(0)|BIT(1)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_DVFS_VOLTAGE_VALUE0, [0x6401412C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE3_I2C(x)          ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE2_I2C(x)          ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE1_I2C(x)          ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE0_I2C(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_DVFS_VOLTAGE_VALUE1, [0x64014130] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE7_I2C(x)          ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE6_I2C(x)          ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE5_I2C(x)          ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE4_I2C(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_ADI, [0x64014134] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_ACK_ADI             ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_SW_ADI(x)   ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_JUDGE_VOLTAGE_SW_ADI(x)  ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_REQ_SW_ADI          ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_I2C, [0x64014138] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_NACK1_I2C           ( BIT(24) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_NACK0_I2C           ( BIT(23) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_ACK1_I2C            ( BIT(22) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_ACK0_I2C            ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_JUDGE_VOLTAGE_SW_I2C(x)  ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_SW_I2C(x)   ( (x) << 10 & (BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_REQ1_SW_I2C         ( BIT(9) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_CFG_SW_I2C(x)       ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_REQ0_SW_I2C         ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_STATE_DBG1, [0x6401413C] */
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_VOLTAGE(x)            ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)) )
#define BIT_TOP_DVFS_APB_AUDCP_SYS_VOLTAGE_MEET             ( BIT(14) )
#define BIT_TOP_DVFS_APB_GPU_SYS_VOLTAGE_MEET               ( BIT(13) )
#define BIT_TOP_DVFS_APB_MM_SYS_VOLTAGE_MEET                ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MM_PRE_CURRENT_VOLTAGE(x)     ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_VOLTAGE(x)            ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_PRE_VOTE_VOLTAGE(x)        ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_MM_VOTE_VOLTAGE(x)            ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_STATE_DBG1, [0x64014140] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_VOLTAGE(x)         ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_AP_SYS_VOLTAGE_MEET                ( BIT(14) )
#define BIT_TOP_DVFS_APB_PUBCP_SYS_VOLTAGE_MEET             ( BIT(13) )
#define BIT_TOP_DVFS_APB_WTLCP_SYS_VOLTAGE_MEET             ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_PRE_CURRENT_VOLTAGE(x)  ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_VOLTAGE(x)         ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_PRE_VOTE_VOLTAGE(x)     ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_VOTE_VOLTAGE(x)         ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_STATE_DBG1, [0x64014144] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_VOLTAGE(x)          ( (x) << 13 & (BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)) )
#define BIT_TOP_DVFS_APB_APCPU_TOP_VOLTAGE_MEET             ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_PRE_CURRENT_VOLTAGE(x)   ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_VOLTAGE(x)          ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_PRE_VOTE_VOLTAGE(x)      ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_VOTE_VOLTAGE(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG1, [0x64014148] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_ADI(x)      ( (x) << 13 & (BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)) )
#define BIT_TOP_DVFS_APB_PROMETHUES_VOLTAGE_MEET            ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_PRE_CURRENT_VOLTAGE(x)   ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_VOLTAGE(x)          ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_PRE_VOTE_VOLTAGE(x)      ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOTE_VOLTAGE(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG2, [0x6401414C] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_CFG_I2C(x)          ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_I2C(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_SUBSYS_SW_DVFS_EN_CFG, [0x64014150] */
#define BIT_TOP_DVFS_APB_PUB_SW_DVFS_EN                     ( BIT(8) )
#define BIT_TOP_DVFS_APB_APCPU_DCDC_CPU1_SW_DVFS_EN         ( BIT(7) )
#define BIT_TOP_DVFS_APB_APCPU_DCDC_CPU0_SW_DVFS_EN         ( BIT(6) )
#define BIT_TOP_DVFS_APB_AUDCP_SW_DVFS_EN                   ( BIT(5) )
#define BIT_TOP_DVFS_APB_PUBCP_SW_DVFS_EN                   ( BIT(4) )
#define BIT_TOP_DVFS_APB_WTLCP_SW_DVFS_EN                   ( BIT(3) )
#define BIT_TOP_DVFS_APB_MM_SYS_SW_DVFS_EN                  ( BIT(2) )
#define BIT_TOP_DVFS_APB_GPU_SYS_SW_DVFS_EN                 ( BIT(1) )
#define BIT_TOP_DVFS_APB_AP_SYS_SW_DVFS_EN                  ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_WTLCP_DVFS_URGENCY_CFG, [0x64014154] */
#define BIT_TOP_DVFS_APB_WTLCP_DVFS_URGENCY_EN              ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_DVFS_CNT_CFG, [0x64014158] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_CNT_CLR              ( BIT(9) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_CNT_EN               ( BIT(8) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_CNT_CLR             ( BIT(7) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_CNT_CLR             ( BIT(6) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_CNT_CLR            ( BIT(5) )
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_CNT_CLR               ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_CNT_EN              ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_CNT_EN              ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_CNT_EN             ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_CNT_EN                ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MM_DVFS_CNT, [0x6401415C] */
#define BIT_TOP_DVFS_APB_DCDC_MM_TUNE_CNT(x)                ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_MODEM_DVFS_CNT, [0x64014160] */
#define BIT_TOP_DVFS_APB_DCDC_MODEM_TUNE_CNT(x)             ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU0_DVFS_CNT, [0x64014164] */
#define BIT_TOP_DVFS_APB_DCDC_CPU0_TUNE_CNT(x)              ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_CNT, [0x64014168] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_CNT(x)              ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_IDLE_VOL_CFG, [0x6401416C] */
#define BIT_TOP_DVFS_APB_PUB_SYS_DVFS_IDLE_VOLTAGE(x)       ( (x) << 27 & (BIT(27)|BIT(28)|BIT(29)) )
#define BIT_TOP_DVFS_APB_AUDCP_SYS_DVFS_IDLE_VOLTAGE(x)     ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_GPU_TOP_DVFS_IDLE_VOLTAGE(x)       ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_MM_SYS_DVFS_IDLE_VOLTAGE(x)        ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_WTLCP_SYS_DVFS_IDLE_VOLTAGE(x)     ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_PUBCP_SYS_DVFS_IDLE_VOLTAGE(x)     ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_AP_SYS_DVFS_IDLE_VOLTAGE(x)        ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_APCPU_TOP_DVFS_IDLE_VOLTAGE(x)     ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_PROMETHEUS_DVFS_IDLE_VOLTAGE(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_SHARE_DCDC_CFG, [0x64014170] */
#define BIT_TOP_DVFS_APB_MM_MODEM_SHARE_DCDC_EN             ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_FIX_VOLTAGE_CTRL, [0x64014174] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_FIX_VOLTAGE(x)            ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_FIX_VOLTAGE_EN            ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_WAIT_WINDOW_CFG, [0x64014178] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_UP_WINDOW(x)         ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_DOWN_WINDOW(x)       ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY_CFG0, [0x6401417C] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY_BAK(x)   ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY2(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY_CFG1, [0x64014180] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY1(x)      ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_DELAY0(x)      ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY_CFG0, [0x64014184] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY_BAK(x) ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY2(x)    ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY_CFG1, [0x64014188] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY1(x)    ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_DELAY0(x)    ( (x) << 0  & (0x0000FFFF) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_CTRL, [0x6401418C] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_ACK                  ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_TUNE_EN                ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_VOLTAGE_SW(x)        ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_JUDGE_VOLTAGE_SW(x)       ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_REQ_SW               ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_JUDGE_BYPASS, [0x64014190] */
#define BIT_TOP_DVFS_APB_REG_PUB_SYS_VOLTAGE_MEET_BYP       ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_STATE_DBG, [0x64014194] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_JUDGE_VOLTAGE(x)          ( (x) << 23 & (BIT(23)|BIT(24)|BIT(25)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_CURRENT_VOLTAGE(x)        ( (x) << 20 & (BIT(20)|BIT(21)|BIT(22)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_CNT(x)               ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_STATE(x)             ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL, [0x64014198] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL7(x)          ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL6(x)          ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL5(x)          ( (x) << 15 & (BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL4(x)          ( (x) << 12 & (BIT(12)|BIT(13)|BIT(14)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL3(x)          ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL2(x)          ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL1(x)          ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_SW_DVFS_POLL0(x)          ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOL_TUNE_UP_CFG, [0x6401419C] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_CFG_BAK(x)     ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_CFG2(x)        ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_CFG1(x)        ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_UP_CFG0(x)        ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_VOL_TUNE_DOWN_CFG, [0x640141A0] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_CFG_BAK(x)   ( (x) << 21 & (BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)|BIT(27)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_CFG2(x)      ( (x) << 14 & (BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_CFG1(x)      ( (x) << 7  & (BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_DOWN_CFG0(x)      ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_VOLTAGE_VALUE0, [0x640141A4] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE2(x)               ( (x) << 18 & (BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)|BIT(24)|BIT(25)|BIT(26)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE1(x)               ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE0(x)               ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_VOLTAGE_VALUE1, [0x640141A8] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE_BAK(x)            ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOLTAGE3(x)               ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_STATE_DBG1, [0x640141AC] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_VOLTAGE(x)           ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_PUB_SYS_VOLTAGE_MEET               ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_PRE_CURRENT_VOLTAGE(x)    ( (x) << 9  & (BIT(9)|BIT(10)|BIT(11)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_VOLTAGE(x)           ( (x) << 6  & (BIT(6)|BIT(7)|BIT(8)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_PRE_VOTE_VOLTAGE(x)       ( (x) << 3  & (BIT(3)|BIT(4)|BIT(5)) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_VOTE_VOLTAGE(x)           ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_TOP_DVFS_CNT, [0x640141B0] */
#define BIT_TOP_DVFS_APB_DCDC_TOP_TUNE_CNT(x)               ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_IDLE_VOL_EN, [0x640141B4] */
#define BIT_TOP_DVFS_APB_PUB_SYS_DVFS_IDLE_VOL_EN           ( BIT(9) )
#define BIT_TOP_DVFS_APB_AUDCP_SYS_DVFS_IDLE_VOL_EN         ( BIT(8) )
#define BIT_TOP_DVFS_APB_GPU_TOP_DVFS_IDLE_VOL_EN           ( BIT(7) )
#define BIT_TOP_DVFS_APB_MM_SYS_DVFS_IDLE_VOL_EN            ( BIT(6) )
#define BIT_TOP_DVFS_APB_WTLCP_SYS_DVFS_IDLE_VOL_EN         ( BIT(5) )
#define BIT_TOP_DVFS_APB_PUBCP_SYS_DVFS_IDLE_VOL_EN         ( BIT(4) )
#define BIT_TOP_DVFS_APB_AP_SYS_DVFS_IDLE_VOL_EN            ( BIT(3) )
#define BIT_TOP_DVFS_APB_APCPU_TOP_DVFS_IDLE_VOL_EN         ( BIT(1) )
#define BIT_TOP_DVFS_APB_PROMETHEUS_DVFS_IDLE_VOL_EN        ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_UP_CFG0, [0x640141B8] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG3_I2C(x)   ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG2_I2C(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG1_I2C(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG0_I2C(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_UP_CFG1, [0x640141BC] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG7_I2C(x)   ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG6_I2C(x)   ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG5_I2C(x)   ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_UP_CFG4_I2C(x)   ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_DOWN_CFG0, [0x640141C0] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG3_I2C(x) ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG2_I2C(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG1_I2C(x) ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG0_I2C(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_VOL_TUNE_DOWN_CFG1, [0x640141C4] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG7_I2C(x) ( (x) << 24 & (BIT(24)|BIT(25)|BIT(26)|BIT(27)|BIT(28)|BIT(29)|BIT(30)|BIT(31)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG6_I2C(x) ( (x) << 16 & (BIT(16)|BIT(17)|BIT(18)|BIT(19)|BIT(20)|BIT(21)|BIT(22)|BIT(23)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG5_I2C(x) ( (x) << 8  & (BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_VOLTAGE_DOWN_CFG4_I2C(x) ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(6)|BIT(7)) )

/* bits definitions for REG_TOP_DVFS_APB_PMIC_3RD_DCDC_CPU1_CFG, [0x640141C8] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_SLEW_CFG_BYPASS_I2C      ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_TOP_IRQ_EN, [0x640141CC] */
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_DONE_IRQ_EN           ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_DONE_IRQ_EN        ( BIT(10) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_DONE_IRQ_EN          ( BIT(8) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_DONE_IRQ_EN         ( BIT(6) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_EN_ADI     ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_EN_ADI_2ND ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_EN_ADI_2ND ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_EN_I2C     ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_EN_I2C     ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_TOP_IRQ_CLR, [0x640141D0] */
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_DONE_IRQ_CLR          ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_DONE_IRQ_CLR       ( BIT(10) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_DONE_IRQ_CLR         ( BIT(8) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_DONE_IRQ_CLR        ( BIT(6) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_CLR_ADI    ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_CLR_ADI_2ND ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_CLR_ADI_2ND ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_CLR_I2C    ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_CLR_I2C    ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_TOP_IRQ_RAW, [0x640141D4] */
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_DONE_IRQ_RAW          ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_DONE_IRQ_RAW       ( BIT(10) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_DONE_IRQ_RAW         ( BIT(8) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_DONE_IRQ_RAW        ( BIT(6) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_RAW_ADI    ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_RAW_ADI_2ND ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_RAW_ADI_2ND ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_RAW_I2C    ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_RAW_I2C    ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DVFS_TOP_IRQ_MASK, [0x640141D8] */
#define BIT_TOP_DVFS_APB_DCDC_MM_DVFS_DONE_IRQ_MASK         ( BIT(12) )
#define BIT_TOP_DVFS_APB_DCDC_MODEM_DVFS_DONE_IRQ_MASK      ( BIT(10) )
#define BIT_TOP_DVFS_APB_DCDC_TOP_DVFS_DONE_IRQ_MASK        ( BIT(8) )
#define BIT_TOP_DVFS_APB_DCDC_CPU0_DVFS_DONE_IRQ_MASK       ( BIT(6) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_MASK_ADI   ( BIT(4) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_MASK_ADI_2ND ( BIT(3) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_MASK_ADI_2ND ( BIT(2) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_NACK_IRQ_MASK_I2C   ( BIT(1) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_DONE_IRQ_MASK_I2C   ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_DBG3, [0x640141DC] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_ADI_2ND(x)  ( (x) << 16 & (0xFFFF0000) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_DVFS_STATE_ADI_2ND(x)    ( (x) << 0  & (BIT(0)|BIT(1)|BIT(2)|BIT(3)) )

/* bits definitions for REG_TOP_DVFS_APB_DCDC_CPU1_SW_DVFS_CTRL_ADI_2ND, [0x640141E0] */
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_NACK_ADI_2ND        ( BIT(21) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_ACK_ADI_2ND         ( BIT(20) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_VOLTAGE_SW_ADI_2ND(x) ( (x) << 4  & (BIT(4)|BIT(5)|BIT(6)|BIT(7)|BIT(8)|BIT(9)|BIT(10)|BIT(11)|BIT(12)|BIT(13)|BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_JUDGE_VOLTAGE_SW_ADI_2ND(x) ( (x) << 1  & (BIT(1)|BIT(2)|BIT(3)) )
#define BIT_TOP_DVFS_APB_DCDC_CPU1_TUNE_REQ_SW_ADI_2ND      ( BIT(0) )

/* bits definitions for REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG0, [0x640141F0] */
#define BIT_TOP_DVFS_APB_DVFS_RES_REG0(x)                   ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG1, [0x640141F4] */
#define BIT_TOP_DVFS_APB_DVFS_RES_REG1(x)                   ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG2, [0x640141F8] */
#define BIT_TOP_DVFS_APB_DVFS_RES_REG2(x)                   ( (x) )

/* bits definitions for REG_TOP_DVFS_APB_TOP_DVFS_RESERVED_REG_CFG3, [0x640141FC] */
#define BIT_TOP_DVFS_APB_DVFS_RES_REG3(x)                   ( (x) )

/* vars definitions for controller CTL_TOP_DVFS_APB */


#endif /* __TOP_DVFS_APB_H____ */
