# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2015 Google, Inc
# Written by Simon Glass <sjg@chromium.org>

obj-y += led-uclass.o
obj-$(CONFIG_$(SPL_)LED_GPIO) += led_gpio.o
obj-$(CONFIG_LED_SC27XX) += sc27xx_led.o
