#include <asm/arch-sc9630/sci_types.h>
#include <adi_hal_internal.h>
#include <asm/arch/common.h>
#include <asm/arch/sprd_reg.h>
#include "asm/arch-qogirn6pro/sprd_reg.h"
#include "asm/arch-qogirn6pro/common.h"



#define REFOUT0_ON				BIT(0)
#define REFOUT1_ON				BIT(1)
#define REFOUT2_ON				BIT(2)
#define REFOUT3_ON				BIT(3)

#define CALIBRATION_DCDCSRAM			(0)
#define CALIBRATION_DCDCMODEM			(0)
#define CALIBRATION_DCDCGPU			(0)
#define CALIBRATION_DCDCCORE			(-2)

static uint32_t boot_mod;
#define BOOT_MOD_MASK				0x3

void dcdc_ldo_power_on(void)
{
#if defined(CONFIG_ADIE_9620)
	/* In UMP9620 this DCDCs/LDOs are on by default */
	//regulator_enable("vddsram0");
	//regulator_enable("vddmemq");
	//regulator_enable("vddmem");
	//regulator_enable("vddcore");
	//regulator_enable("vddpub");
	//regulator_enable("vddgen0");
	//regulator_enable("vddgen1");
	//regulator_enable("vddemmccore");
	//regulator_enable("vddsdcore");
	//regulator_enable("vddsdio");
	//regulator_enable("vdd28");
	//regulator_enable("vdddcxo");
	//regulator_enable("vddusb33");
	//regulator_enable("vddldo1");
	//regulator_enable("avdd18");
	//regulator_enable("vddufs1v2"); //Keep power on temporarily in -2 board
	//regulator_enable("avdd12");

	/* In UMP9620 this DCDCs/LDOs are off by default */
	//regulator_enable("vddcpu1");
	//regulator_enable("vddcpu2");
	regulator_enable("vddgpu");
	//regulator_enable("vddwpa");
	//regulator_enable("vddrf1v8");
	//regulator_enable("vddwcn");
	//regulator_enable("vddcamd2");
	//regulator_enable("avdcamd1");
	//regulator_enable("vddcamd0");
	//regulator_enable("vddrf0v9");
	//regulator_enable("vddrf1v1");
	//regulator_enable("vddcamio");
	//regulator_enable("vddcama0");
	//regulator_enable("vddcama1");
	//regulator_enable("vddcama2");
	//regulator_enable("vddcammot0");
	//regulator_enable("vddcammot1");
	//regulator_enable("vddsim0");
	//regulator_enable("vddsim1");
	//regulator_enable("vddsim2");
	//regulator_enable("vddwifipa");
	//regulator_enable("vddldo0");
	//regulator_enable("vddldo2");
	//regulator_enable("vddldo3");
	//regulator_enable("vddldo4");
	//regulator_enable("vddvib");
	//regulator_enable("vddkpled");

	/* In UMP9621 this DCDCs/LDOs are on by default */
	//regulator_enable("vddcpu0");
	//regulator_enable("vddmodem");
	//regulator_enable("vddsram2");
	//regulator_enable("vddsram1");
	//regulator_enable("vddmm");

	/* In UMP9621 this DCDCs/LDOs are off by default */
	regulator_enable("vddai");
#endif
}

void pmic_lowpower_config(uint32_t ddie_id,uint32_t adie_id)
{
	unsigned int drop_val;

	ANA_REG_SET(ANA_REG_GLB_DCDC_WR_PROT_VALUE, 0x2017);
	while((ANA_REG_GET(ANA_REG_GLB_PWR_WR_PROT_VALUE) & 0x8000) != 0x8000);
	ANA_REG_OR(ANA_REG_GLB_DCDC_CLK_CTRL, BIT_DCDC_6MCLKOUT_AUTOGATE_EN);
	ANA_REG_AND(ANA_REG_GLB_DCDC_CLK_CTRL, ~BIT_DCDC_6MCLKOUT_EN);
	ANA_REG_SET(ANA_REG_GLB_DCDC_WR_PROT_VALUE, 0x0000);

	ANA_REG_SET(REG_ANA_UMP9621_DCDC_WR_PROT_VALUE, 0x2017);
	while((ANA_REG_GET(ANA_REG_GLB_PWR_WR_PROT_VALUE) & 0x8000) != 0x8000);
	ANA_REG_OR(REG_ANA_UMP9621_DCDC_CLK_CTRL,
		   BIT_ANA_UMP9621_DCDC_6MCLKOUT_AUTOGATE_EN);
	ANA_REG_AND(REG_ANA_UMP9621_DCDC_CLK_CTRL,
		    ~BIT_ANA_UMP9621_DCDC_6MCLKOUT_EN);
	ANA_REG_SET(REG_ANA_UMP9621_DCDC_WR_PROT_VALUE, 0x0000);

	/* UMP9620 ADIE sleep globle control */
	ANA_REG_SET(ANA_REG_GLB_SLP_CTRL,
		    BIT_LDO_XTL_EN |	//DCDC and LDO can control by EXT_XTL pin
		    BIT_SLP_IO_EN |	//ADIE io can into sleep mode when CHIP_SLEEP high
		    BIT_SLP_LDO_PD_EN |	//DCDC and LDO can pd in sleep mode
		    0);

	/* UMP9621 ADIE sleep globle control */
	ANA_REG_SET(REG_ANA_UMP9621_SLP_CTRL,
		    BIT_ANA_UMP9621_SLP_IO_EN |	    //ADIE io can into sleep mode when CHIP_SLEEP high
		    BIT_ANA_UMP9621_SLP_LDO_PD_EN | //DCDC and LDO can pd in sleep mode
		    0);

	/* UMP9622 ADIE sleep globle control */
	ANA_REG_SET(REG_ANA_UMP9622_SLP_CTRL,
		    BIT_ANA_UMP9622_SLP_IO_EN |	    //ADIE io can into sleep mode when CHIP_SLEEP high
		    BIT_ANA_UMP9622_SLP_LDO_PD_EN | //DCDC and LDO can pd in sleep mode
		    0);

	if (boot_mod == 0x1) {	/* UFS */
	/* DCDC pd an drop config in sleep mode */
	ANA_REG_SET(ANA_REG_GLB_SLP_DCDC_PD_CTRL,
		    //BIT_SLP_DCDCPUB_PD_EN |
		    BIT_SLP_DCDCMEMQ_PD_EN |
		    //BIT_SLP_DCDCSRAM0_PD_EN |
#if CONFIG_DCDCSRAM0_DEEP_DROP_EN
		    BIT_SLP_DCDCSRAM0_DROP_EN |
#endif
#if CONFIG_DCDCPUB_DEEP_DROP_EN
		    BIT_SLP_DCDCPUB_DROP_EN |
#endif
		    //BIT_SLP_DCDCGPU_DROP_EN |
#if CONFIG_DCDCCORE_DEEP_DROP_EN
		   // BIT_SLP_DCDCCORE_DROP_EN |
#endif
		    //BIT_SLP_DCDCWPA_PD_EN |
		    //BIT_SLP_DCDCGPU_PD_EN |
		    //BIT_SLP_DCDCGEN1_PD_EN |	// ufs need on
		    0
		    );
	} else {	/* not UFS */
	/* DCDC pd an drop config in sleep mode */
	ANA_REG_SET(ANA_REG_GLB_SLP_DCDC_PD_CTRL,
		    //BIT_SLP_DCDCPUB_PD_EN |
		    BIT_SLP_DCDCMEMQ_PD_EN |
		    //BIT_SLP_DCDCSRAM0_PD_EN |
#if CONFIG_DCDCSRAM0_DEEP_DROP_EN
		    BIT_SLP_DCDCSRAM0_DROP_EN |
#endif
#if CONFIG_DCDCPUB_DEEP_DROP_EN
		    BIT_SLP_DCDCPUB_DROP_EN |
#endif
		    //BIT_SLP_DCDCGPU_DROP_EN |
#if CONFIG_DCDCCORE_DEEP_DROP_EN
		    BIT_SLP_DCDCCORE_DROP_EN |
#endif
		    //BIT_SLP_DCDCWPA_PD_EN |
		    //BIT_SLP_DCDCGPU_PD_EN |
		    BIT_SLP_DCDCGEN1_PD_EN |	// PD in deep -2 board
		    0
		    );
	}

#if CONFIG_DCDCSRAM0_DEEP_DROP_EN
	ANA_REG_OR(ANA_REG_GLB_STEP_CLK_CTRL, BIT_SRAM0_STEP_CLK_SEL);
	drop_val = (CONFIG_DCDCSRAM0_DEEP_DROP_VOL * 1000U) / 3125U;
	ANA_REG_SET(ANA_REG_GLB_DCDC_SRAM0_SLP_CTRL1,
		    BIT_DCDC_SRAM0_CTRL_DS_SW(drop_val));
#endif

#if CONFIG_DCDCPUB_DEEP_DROP_EN
	ANA_REG_OR(ANA_REG_GLB_STEP_CLK_CTRL, BIT_PUB_STEP_CLK_SEL);
	drop_val = (CONFIG_DCDCPUB_DEEP_DROP_VOL * 1000U) / 3125U;
	ANA_REG_SET(ANA_REG_GLB_DCDC_PUB_SLP_CTRL1,
		    BIT_DCDC_PUB_CTRL_DS_SW(drop_val));
#endif

#if CONFIG_DCDCCORE_DEEP_DROP_EN
	ANA_REG_OR(ANA_REG_GLB_STEP_CLK_CTRL, BIT_CORE_STEP_CLK_SEL);
	drop_val = (CONFIG_DCDCCORE_DEEP_DROP_VOL * 1000U) / 3125U;
	ANA_REG_SET(ANA_REG_GLB_DCDC_CORE_SLP_CTRL1,
		    BIT_DCDC_CORE_CTRL_DS_SW(drop_val));
#endif

	/*CONFIG_DCDC_CPU1_STB_OP*/
	ANA_REG_SET(ANA_REG_GLB_DCDC_WR_PROT_VALUE, 0x2017);
	while((ANA_REG_GET(ANA_REG_GLB_PWR_WR_PROT_VALUE) & 0x8000) != 0x8000);
	ANA_REG_BIC(ANA_REG_GLB_DCDC_CPU1_REG2,
			BIT(9) |
			BIT(10) |
			0);
	ANA_REG_SET(ANA_REG_GLB_DCDC_WR_PROT_VALUE, 0x0000);

	ANA_REG_SET(REG_ANA_UMP9621_SLP_DCDC_PD_CTRL,
		    //BIT_ANA_UMP9621_SLP_DCDCSRAM1_DROP_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCSRAM2_DROP_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCAI_DROP_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCMODEM_DROP_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCMM_DROP_EN |
		    BIT_ANA_UMP9621_SLP_DCDCSRAM1_PD_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCBUCKBOOST_PD_EN |
		    //BIT_ANA_UMP9621_SLP_DCDCAI_PD_EN |
		    BIT_ANA_UMP9621_SLP_DCDCMODEM_PD_EN |
		    BIT_ANA_UMP9621_SLP_DCDCSRAM2_PD_EN |
		    BIT_ANA_UMP9621_SLP_DCDCMM_PD_EN |
		    0);

	/* DCDC LP config */
	ANA_REG_SET(ANA_REG_GLB_SLP_DCDC_LP_CTRL,
		    BIT_SLP_DCDCSRAM0_LP_EN |
		    BIT_SLP_DCDCPUB_LP_EN |
		    //BIT_SLP_DCDCMEMQ_LP_EN |
		    BIT_SLP_DCDCMEM_LP_EN |
		    //BIT_SLP_DCDCGPU_LP_EN |
		    BIT_SLP_DCDCCORE_LP_EN |
		    BIT_SLP_DCDCGEN1_LP_EN |
		    BIT_SLP_DCDCGEN0_LP_EN |
		    //BIT_SLP_DCDCWPA_LP_EN |
		    0
		    );

	/* LDO PD Config */
	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_PD_CTRL0,
		    //BIT_SLP_LDO_VDDRF1V1_PD_EN |
		    //BIT_SLP_LDO_VDDRF1V8_PD_EN |
		    //BIT_SLP_LDO_VDDRF0V9_PD_EN |
		    BIT_SLP_LDO_VDDEMMCCORE_PD_EN |
		    BIT_SLP_LDO_VDD18_DCXO_PD_EN |
		    //BIT_SLP_LDO_VDDWIFIPA_PD_EN |
		    //BIT_SLP_LDO_VDD28_PD_EN |
		    //BIT_SLP_LDO_VDDSDCORE_PD_EN |
		    //BIT_SLP_LDO_VDDSDIO_PD_EN |
		    //BIT_SLP_LDO_VDDUSB33_PD_EN |
		    //BIT_SLP_LDO_VDDCAMMOT0_PD_EN |
		    //BIT_SLP_LDO_VDDCAMIO_PD_EN |
		    //BIT_SLP_LDO_VDDCAMD0_PD_EN |
		    //BIT_SLP_LDO_VDDCAMA0_PD_EN |
		    //BIT_SLP_LDO_VDDSIM2_PD_EN |
		    //BIT_SLP_LDO_VDDSIM1_PD_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_PD_CTRL1,
		    //BIT_SLP_LDO_VDDUFS1V2_PD_EN |
		    //BIT_SLP_LDO_VDDLDO4_PD_EN |
		    //BIT_SLP_LDO_VDDLDO3_PD_EN |
		    //BIT_SLP_LDO_VDDCAMMOT1_PD_EN |
		   // BIT_SLP_LDO_VDDLDO2_PD_EN |
		    BIT_SLP_LDO_AVDD12_PD_EN |
		    //BIT_SLP_LDO_VDDWCN_PD_EN |
		    //BIT_SLP_LDO_VDDLDO0_PD_EN |
		    //BIT_SLP_LDO_VDDCAMD1_PD_EN |
		    //BIT_SLP_LDO_VDDCAMA1_PD_EN
		    //BIT_SLP_LDO_VDDSIM0_PD_EN |
		    BIT_SLP_LDO_AVDD18_PD_EN |
		    //BIT_SLP_LDO_VDDLDO1_PD_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_PD_CTRL2,
		    //BIT_SLP_LDO_VDDCAMD2_PD_EN |
		    //BIT_SLP_LDO_VDDCAMA2_PD_EN |
		    0);

	/* LDO LP Config */
	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_LP_CTRL0,
		    BIT_SLP_LDO_VDDUFS1V2_LP_EN |	//No use in -2 board
		    //BIT_SLP_LDO_VDDRF1V8_LP_EN |
		    //BIT_SLP_LDO_VDDRF0V9_LP_EN |
		    //BIT_SLP_LDO_VDDEMMCCORE_LP_EN |
		    //BIT_SLP_LDO_VDD18_DCXO_LP_EN |
		    //BIT_SLP_LDO_VDDWIFIPA_LP_EN |
		    //BIT_SLP_LDO_VDD28_LP_EN |
		    //BIT_SLP_LDO_VDDSDCORE_LP_EN |
		    //BIT_SLP_LDO_VDDSDIO_LP_EN |
		    //BIT_SLP_LDO_VDDUSB33_LP_EN |
		    //BIT_SLP_LDO_VDDCAMMOT0_LP_EN |
		    //BIT_SLP_LDO_VDDRF1V1_LP_EN |
		    //BIT_SLP_LDO_VDDCAMD0_LP_EN |
		    //BIT_SLP_LDO_VDDCAMA0_LP_EN  |
		    //BIT_SLP_LDO_VDDSIM2_LP_EN  |
		    //BIT_SLP_LDO_VDDSIM1_LP_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_LP_CTRL1,
		    //BIT_SLP_LDO_VDDLDO4_LP_EN |
		    //BIT_SLP_LDO_VDDLDO3_LP_EN |
		    //BIT_SLP_LDO_VDDCAMMOT1_LP_EN |
		    //BIT_SLP_LDO_VDDLDO2_LP_EN |
		    //BIT_SLP_LDO_AVDD12_LP_EN |
		    //BIT_SLP_LDO_VDDWCN_LP_EN |
		    //BIT_SLP_LDO_VDDCAMD1_LP_EN |
		    //BIT_SLP_LDO_VDDCAMA1_LP_EN |
		    //BIT_SLP_LDO_VDDLDO0_LP_EN |
		    //BIT_SLP_LDO_VDDSIM0_LP_EN |
		    //BIT_SLP_LDO_AVDD18_LP_EN |
		    BIT_SLP_LDO_VDDLDO1_LP_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_SLP_LDO_LP_CTRL2,
		    //BIT_SLP_LDO_VDDCAMD2_LP_EN |
		    //BIT_SLP_LDO_VDDCAMA2_LP_EN |
		    0);

	/* EXT_XTL_EN Config */
	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN,
		    //BIT_DCDC_CORE_EXT_XTL6_EN |
		    //BIT_DCDC_CORE_EXT_XTL5_EN |
		    //BIT_DCDC_CORE_EXT_XTL4_EN |
		    //BIT_DCDC_CORE_EXT_XTL3_EN |
		    //BIT_DCDC_CORE_EXT_XTL2_EN |
		    //BIT_DCDC_CORE_EXT_XTL1_EN |
		    BIT_DCDC_CORE_EXT_XTL0_EN |
		    //BIT_DCDC_WPA_EXT_XTL6_EN |
		    //BIT_DCDC_WPA_EXT_XTL5_EN |
		    //BIT_DCDC_WPA_EXT_XTL4_EN |
		    //BIT_DCDC_WPA_EXT_XTL3_EN |
		    //BIT_DCDC_WPA_EXT_XTL2_EN |
		    //BIT_DCDC_WPA_EXT_XTL1_EN |
		    //BIT_DCDC_WPA_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN0,
		    //BIT_DCDC_GEN0_EXT_XTL6_EN |
		    //BIT_DCDC_GEN0_EXT_XTL5_EN |
		    //BIT_DCDC_GEN0_EXT_XTL4_EN |
		    //BIT_DCDC_GEN0_EXT_XTL3_EN |
		    //BIT_DCDC_GEN0_EXT_XTL2_EN |
		    //BIT_DCDC_GEN0_EXT_XTL1_EN |
		    //BIT_DCDC_GEN0_EXT_XTL0_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL6_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL5_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL4_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL3_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL2_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL1_EN |
		    //BIT_DCDC_SRAM0_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN1,
		    //BIT_DCDC_GPU_EXT_XTL6_EN |
		    //BIT_DCDC_GPU_EXT_XTL5_EN |
		    //BIT_DCDC_GPU_EXT_XTL4_EN |
		    //BIT_DCDC_GPU_EXT_XTL3_EN |
		    //BIT_DCDC_GPU_EXT_XTL2_EN |
		    //BIT_DCDC_GPU_EXT_XTL1_EN |
		    //BIT_DCDC_GPU_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN2,
		    //BIT_DCDC_MEM_EXT_XTL6_EN |
		    //BIT_DCDC_MEM_EXT_XTL5_EN |
		    //BIT_DCDC_MEM_EXT_XTL4_EN |
		    //BIT_DCDC_MEM_EXT_XTL3_EN |
		    //BIT_DCDC_MEM_EXT_XTL2_EN |
		    //BIT_DCDC_MEM_EXT_XTL1_EN |
		    //BIT_DCDC_MEM_EXT_XTL0_EN |
		    //BIT_DCDC_GEN1_EXT_XTL6_EN |
		    //BIT_DCDC_GEN1_EXT_XTL5_EN |
		    //BIT_DCDC_GEN1_EXT_XTL4_EN |
		    BIT_DCDC_GEN1_EXT_XTL3_EN |
		    BIT_DCDC_GEN1_EXT_XTL2_EN |
		    //BIT_DCDC_GEN1_EXT_XTL1_EN |
		    //BIT_DCDC_GEN1_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN3,
		    //BIT_DCDC_MEMQ_EXT_XTL6_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL5_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL4_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL3_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL2_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL1_EN |
		    //BIT_DCDC_MEMQ_EXT_XTL0_EN |
		    //BIT_DCDC_PUB_EXT_XTL6_EN |
		    //BIT_DCDC_PUB_EXT_XTL5_EN |
		    //BIT_DCDC_PUB_EXT_XTL4_EN |
		    //BIT_DCDC_PUB_EXT_XTL3_EN |
		    //BIT_DCDC_PUB_EXT_XTL2_EN |
		    //BIT_DCDC_PUB_EXT_XTL1_EN |
		    //BIT_DCDC_PUB_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN5,
		    //BIT_DCDC_AI_EXT_XTL6_EN |
		    //BIT_DCDC_AI_EXT_XTL5_EN |
		    //BIT_DCDC_AI_EXT_XTL4_EN |
		    //BIT_DCDC_AI_EXT_XTL3_EN |
		    //BIT_DCDC_AI_EXT_XTL2_EN |
		    //BIT_DCDC_AI_EXT_XTL1_EN |
		    //BIT_DCDC_AI_EXT_XTL0_EN |
		    //BIT_DCDC_MODEM_EXT_XTL6_EN |
		    //BIT_DCDC_MODEM_EXT_XTL5_EN |
		    //BIT_DCDC_MODEM_EXT_XTL4_EN |
		    //BIT_DCDC_MODEM_EXT_XTL3_EN |
		    //BIT_DCDC_MODEM_EXT_XTL2_EN |
		    //BIT_DCDC_MODEM_EXT_XTL1_EN |
		    //BIT_DCDC_MODEM_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN6,
		    //BIT_DCDC_MM_EXT_XTL6_EN |
		    //BIT_DCDC_MM_EXT_XTL5_EN |
		    //BIT_DCDC_MM_EXT_XTL4_EN |
		    //BIT_DCDC_MM_EXT_XTL3_EN |
		    //BIT_DCDC_MM_EXT_XTL2_EN |
		    BIT_DCDC_MM_EXT_XTL1_EN |
		    //BIT_DCDC_MM_EXT_XTL0_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL6_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL5_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL4_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL3_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL2_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL1_EN |
		    //BIT_DCDC_SRAM2_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_DCDC_XTL_EN7,
		    //BIT_DCDC_BUCKBOOST_EXT_XTL6_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL5_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL4_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL3_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL2_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL1_EN |
		    //BIT_DCDC_BUCKBOOST_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN0,
		    //BIT_LDO_VDDRF0V9_EXT_XTL6_EN |
		    //BIT_LDO_VDDRF0V9_EXT_XTL5_EN |
		    //BIT_LDO_VDDRF0V9_EXT_XTL4_EN |
		    //BIT_LDO_VDDRF0V9_EXT_XTL3_EN |
		    BIT_LDO_VDDRF0V9_EXT_XTL2_EN |
		    //BIT_LDO_VDDRF0V9_EXT_XTL1_EN |
		    //BIT_LDO_VDDRF0V9_EXT_XTL0_EN |
		    //BIT_LDO_VDD28_EXT_XTL6_EN |
		    //BIT_LDO_VDD28_EXT_XTL5_EN |
		    //BIT_LDO_VDD28_EXT_XTL4_EN |
		    //BIT_LDO_VDD28_EXT_XTL3_EN |
		    //BIT_LDO_VDD28_EXT_XTL2_EN |
		    //BIT_LDO_VDD28_EXT_XTL1_EN |
		    //BIT_LDO_VDD28_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN1,
		    //BIT_LDO_VDDRF1V8_EXT_XTL6_EN |
		    //BIT_LDO_VDDRF1V8_EXT_XTL5_EN |
		    //BIT_LDO_VDDRF1V8_EXT_XTL4_EN |
		    //BIT_LDO_VDDRF1V8_EXT_XTL3_EN |
		    BIT_LDO_VDDRF1V8_EXT_XTL2_EN |
		    //BIT_LDO_VDDRF1V8_EXT_XTL1_EN |
		    //BIT_LDO_VDDRF1V8_EXT_XTL0_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL6_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL5_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL4_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL3_EN |
		    BIT_LDO_VDDRF1V1_EXT_XTL2_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL1_EN |
		    //BIT_LDO_VDDRF1V1_EXT_XTL0_EN |
		    0);

	if (adie_id == 0xa000) { /* AA */
		ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN2,
		    //BIT_LDO_VDDSIM0_EXT_XTL6_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL5_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL4_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL3_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL2_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL1_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL0_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL6_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL5_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL4_EN |
		    BIT_LDO_VDDSIM1_EXT_XTL3_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL2_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL1_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL0_EN |
		    0);
	} else {
		ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN2,
		    //BIT_LDO_VDDSIM0_EXT_XTL6_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL5_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL4_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL3_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL2_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL1_EN |
		    //BIT_LDO_VDDSIM0_EXT_XTL0_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL6_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL5_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL4_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL3_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL2_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL1_EN |
		    //BIT_LDO_VDDSIM1_EXT_XTL0_EN |
		    0);
	}

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN3,
		    //BIT_LDO_VDDSIM2_EXT_XTL6_EN |
		    //BIT_LDO_VDDSIM2_EXT_XTL5_EN |
		    //BIT_LDO_VDDSIM2_EXT_XTL4_EN |
		    BIT_LDO_VDDSIM2_EXT_XTL3_EN |
		    //BIT_LDO_VDDSIM2_EXT_XTL2_EN |
		    //BIT_LDO_VDDSIM2_EXT_XTL1_EN |
		    //BIT_LDO_VDDSIM2_EXT_XTL0_EN |
		    //BIT_LDO_AVDD12_EXT_XTL6_EN |
		    //BIT_LDO_AVDD12_EXT_XTL5_EN |
		    //BIT_LDO_AVDD12_EXT_XTL4_EN |
		    //BIT_LDO_AVDD12_EXT_XTL3_EN |
		    //BIT_LDO_AVDD12_EXT_XTL2_EN |
		    //BIT_LDO_AVDD12_EXT_XTL1_EN |
		    //BIT_LDO_AVDD12_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN4,
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMMOT0_EXT_XTL0_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMIO_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN5,
		    //BIT_LDO_VDDCAMA0_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMA0_EXT_XTL0_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMA1_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN6,
		    //BIT_LDO_VDDCAMD0_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMD0_EXT_XTL0_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMD1_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN7,
		    //BIT_LDO_VDDSDIO_EXT_XTL6_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL5_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL4_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL3_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL2_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL1_EN |
		    //BIT_LDO_VDDSDIO_EXT_XTL0_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL6_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL5_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL4_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL3_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL2_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL1_EN |
		    //BIT_LDO_VDDSDCORE_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN8,
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL6_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL5_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL4_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL3_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL2_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL1_EN |
		    //BIT_LDO_VDDEMMCCORE_EXT_XTL0_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL6_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL5_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL4_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL3_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL2_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL1_EN |
		    //BIT_LDO_VDDUSB33_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN9,
		    //BIT_LDO_VDDKPLED_EXT_XTL6_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL5_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL4_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL3_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL2_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL1_EN |
		    //BIT_LDO_VDDKPLED_EXT_XTL0_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL6_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL5_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL4_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL3_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL2_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL1_EN |
		    //BIT_LDO_VDDVIB_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN10,
		    //BIT_LDO_VDDWCN_EXT_XTL6_EN |
		    //BIT_LDO_VDDWCN_EXT_XTL5_EN |
		    //BIT_LDO_VDDWCN_EXT_XTL4_EN |
		    BIT_LDO_VDDWCN_EXT_XTL3_EN |
		    //BIT_LDO_VDDWCN_EXT_XTL2_EN |
		    //BIT_LDO_VDDWCN_EXT_XTL1_EN |
		    //BIT_LDO_VDDWCN_EXT_XTL0_EN |
		    //BIT_LDO_AVDD18_EXT_XTL6_EN |
		    //BIT_LDO_AVDD18_EXT_XTL5_EN |
		    //BIT_LDO_AVDD18_EXT_XTL4_EN |
		    //BIT_LDO_AVDD18_EXT_XTL3_EN |
		    //BIT_LDO_AVDD18_EXT_XTL2_EN |
		    //BIT_LDO_AVDD18_EXT_XTL1_EN |
		    //BIT_LDO_AVDD18_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN11,
		    //BIT_LDO_VDDLDO0_EXT_XTL6_EN |
		    //BIT_LDO_VDDLDO0_EXT_XTL5_EN |
		    //BIT_LDO_VDDLDO0_EXT_XTL4_EN |
		    //BIT_LDO_VDDLDO0_EXT_XTL3_EN |
		    BIT_LDO_VDDLDO0_EXT_XTL2_EN |
		    //BIT_LDO_VDDLDO0_EXT_XTL1_EN |
		    //BIT_LDO_VDDLDO0_EXT_XTL0_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL6_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL5_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL4_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL3_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL2_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL1_EN |
		    //BIT_LDO_VDDWIFIPA_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN12,
		    //BIT_LDO_VDDLDO2_EXT_XTL6_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL5_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL4_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL3_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL2_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL1_EN |
		    //BIT_LDO_VDDLDO2_EXT_XTL0_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL6_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL5_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL4_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL3_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL2_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL1_EN |
		    //BIT_LDO_VDDLDO1_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN13,
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMMOT1_EXT_XTL0_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMA2_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN14,
		    //BIT_LDO_VDDCAMD2_EXT_XTL6_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL5_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL4_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL3_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL2_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL1_EN |
		    //BIT_LDO_VDDCAMD2_EXT_XTL0_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL6_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL5_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL4_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL3_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL2_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL1_EN |
		    //BIT_LDO_VDDLDO3_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN15,
		    //BIT_LDO_VDDLDO4_EXT_XTL6_EN |
		    //BIT_LDO_VDDLDO4_EXT_XTL5_EN |
		    //BIT_LDO_VDDLDO4_EXT_XTL4_EN |
		    //BIT_LDO_VDDLDO4_EXT_XTL3_EN |
		    BIT_LDO_VDDLDO4_EXT_XTL2_EN |
		    //BIT_LDO_VDDLDO4_EXT_XTL1_EN |
		    //BIT_LDO_VDDLDO4_EXT_XTL0_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL6_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL5_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL4_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL3_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL2_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL1_EN |
		    //BIT_LDO_VDDUFS1V2_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_LDO_XTL_EN16,
		    //BIT_LDO_VDD18_DCXO_EXT_XTL6_EN |
		    //BIT_LDO_VDD18_DCXO_EXT_XTL5_EN |
		    //BIT_LDO_VDD18_DCXO_EXT_XTL4_EN |
		    BIT_LDO_VDD18_DCXO_EXT_XTL3_EN |
		    BIT_LDO_VDD18_DCXO_EXT_XTL2_EN |
		    //BIT_LDO_VDD18_DCXO_EXT_XTL1_EN |
		    //BIT_LDO_VDD18_DCXO_EXT_XTL0_EN |
		    0);

	/* CLOCK Control */
	ANA_REG_SET(ANA_REG_GLB_DCXO_XTL_EN,
		    //BIT_TSX_XO_EXT_XTL6_EN |
		    //BIT_TSX_XO_EXT_XTL5_EN |
		    //BIT_TSX_XO_EXT_XTL4_EN |
		    BIT_TSX_XO_EXT_XTL3_EN |
		    BIT_TSX_XO_EXT_XTL2_EN |
		    //BIT_TSX_XO_EXT_XTL1_EN |
		    //BIT_TSX_XO_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_TSX_CTRL1,
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL1_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL1_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL1_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL1_EN |
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL0_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL0_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL0_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL0_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_TSX_CTRL2,
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL3_EN |
		    BIT_DCXO_26M_REF_OUT2_EXT_XTL3_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL3_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL3_EN |
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL2_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL2_EN |
		    BIT_DCXO_26M_REF_OUT1_EXT_XTL2_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL2_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_TSX_CTRL3,
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL5_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL5_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL5_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL5_EN |
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL4_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL4_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL4_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL4_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_TSX_CTRL4,
		    //BIT_DCXO_26M_REF_OUT3_EXT_XTL6_EN |
		    //BIT_DCXO_26M_REF_OUT2_EXT_XTL6_EN |
		    //BIT_DCXO_26M_REF_OUT1_EXT_XTL6_EN |
		    //BIT_DCXO_26M_REF_OUT0_EXT_XTL6_EN |
		    0);

	ANA_REG_SET(ANA_REG_GLB_XTL_WAIT_CTRL0,
		    BIT_SLP_XTLBUF_PD_EN |
		    BIT_XTL_EN |
		    BIT_XTL_WAIT(0x32) |
		    0);

	ANA_REG_SET(ANA_REG_GLB_XTL_WAIT_CTRL1,
		    //BIT_EXT_XTL6_FOR_26M_EN |
		    //BIT_EXT_XTL5_FOR_26M_EN |
		    //BIT_EXT_XTL4_FOR_26M_EN |
		    BIT_EXT_XTL3_FOR_26M_EN |
		    BIT_EXT_XTL2_FOR_26M_EN |
		    BIT_EXT_XTL1_FOR_26M_EN |
		    BIT_EXT_XTL0_FOR_26M_EN |
		    0);

	ANA_REG_AND(REG_ANA_UMP9622_TSX_CTRL15, ~BIT_ANA_UMP9622_RTC_MODE); //RTC_MODE = 0 ==>32K

	ANA_REG_OR(REG_ANA_UMP9622_TSX_CTRL3, BIT_ANA_UMP9622_SLP_DCXO_LP_EN);

	ANA_REG_SET(REG_ANA_UMP9622_TSX_CTRL0,
		    BIT_ANA_UMP9622_SLP_DCXO_26M_REF_OUT3_EN |
		    BIT_ANA_UMP9622_SLP_DCXO_26M_REF_OUT2_EN |
		    BIT_ANA_UMP9622_SLP_DCXO_26M_REF_OUT1_EN |
		    BIT_ANA_UMP9622_SLP_DCXO_26M_REF_OUT0_EN |
		    BIT_ANA_UMP9622_DCXO_26M_REF_OUT_EN(REFOUT0_ON)|
		    0);
}
void sprd_pmu_lowpower_init(void)
{
#ifndef CONFIG_FPGA
	//Get Chip version
	uint32_t ddie_id;
	uint32_t adie_id;
	uint32_t value = 0U;

	ddie_id = CHIP_REG_GET(REG_AON_APB_DERIVED_ID);
	adie_id = ANA_REG_GET(ANA_REG_GLB_CHIP_ID_LOW);
	boot_mod= CHIP_REG_GET(REG_AON_APB_BOOT_MODE) & BOOT_MOD_MASK;
	//Power on dcdc/ldo
	dcdc_ldo_power_on();
#if defined(CONFIG_SUPPORT_LOWPOWER)
	//Config the ADIE lowpower
	pmic_lowpower_config(ddie_id,adie_id);
	//Config pmu paratmers
	CSP_Init(0);

	value = CHIP_REG_GET(REG_ANLG_PHY_G1_ANALOG_BB_TOP_SINE_DRV_CTRL) &
          		     ~(BIT_ANLG_PHY_G1_ANALOG_BB_TOP_SINDRV_52M_ENA_LVDSPHY);
	CHIP_REG_SET(REG_ANLG_PHY_G1_ANALOG_BB_TOP_SINE_DRV_CTRL, value); //not used
#else
	modules_force_on();
#endif
#endif
}
