#
# (C) Copyright 2000-2004
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= ums9620_3c10.o sdio_cfg.o sprd_kp.o ldo_sleep.o modem_entry.o pinmap.o sprd_bl.o regulator_init.o lcd_printf.o sprd_uart_matrix_cfg.o

obj-y	+= ufs_global_reg.o
