/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

#ifndef __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_MASK_H
#define __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_MASK_H

#define MASK_AON_APB_SERDES_DPHY_REF_EB                     0x100000
#define MASK_AON_APB_SERDES_DPHY_CFG_EB                     0x80000
#define MASK_AON_APB_LVDIS_PLL_DIV_EN                       0x40000
#define MASK_AON_APB_CSSYS_PUB_EB                           0x20000
#define MASK_AON_APB_CSSYS_APB_EB                           0x10000
#define MASK_AON_APB_CSSYS_EB                               0x8000
#define MASK_AON_APB_APCPU_DAP_EB                           0x4000
#define MASK_AON_APB_MSPI_EB                                0x1000
#define MASK_AON_APB_GPU_EB                                 0x0800
#define MASK_AON_APB_SP_AHB_CLK_SOFT_EB                     0x0400
#define MASK_AON_APB_MM_EB                                  0x0200
#define MASK_AON_APB_PROBE_EB                               0x0080
#define MASK_AON_APB_AUX2_EB                                0x0040
#define MASK_AON_APB_AUX1_EB                                0x0020
#define MASK_AON_APB_AUX0_EB                                0x0010
#define MASK_AON_APB_DJTAG_EB                               0x0008
#define MASK_AON_APB_DJTAG_TCK_EB                           0x0004
#define MASK_AON_APB_RFTI_EB                                0x0002
#define MASK_AON_APB_RC100M_CAL_EB                          0x0001
#define MASK_AON_APB_SCC_EB                                 0x100000
#define MASK_AON_APB_AON_IIS_EB                             0x80000
#define MASK_AON_APB_APB_BUSMON_EB                          0x40000
#define MASK_AON_APB_APCPU_TS0_EB                           0x20000
#define MASK_AON_APB_DJTAG_CTRL_EB                          0x10000
#define MASK_AON_APB_CPALL_EIC_EB                           0x8000
#define MASK_AON_APB_ETC_EB                                 0x4000
#define MASK_AON_APB_CKG_EB                                 0x2000
#define MASK_AON_APB_ANA_EB                                 0x1000
#define MASK_AON_APB_PIN_EB                                 0x0800
#define MASK_AON_APB_SPLK_EB                                0x0400
#define MASK_AON_APB_OTG_UTMI_EB                            0x0100
#define MASK_AON_APB_DVFS_TOP_EB                            0x0080
#define MASK_AON_APB_AON_TMR_EB                             0x0040
#define MASK_AON_APB_AP_SYST_EB                             0x0020
#define MASK_AON_APB_AON_SYST_EB                            0x0010
#define MASK_AON_APB_KPD_EB                                 0x0008
#define MASK_AON_APB_MBOX_EB                                0x0004
#define MASK_AON_APB_GPIO_EB                                0x0002
#define MASK_AON_APB_EFUSE_EB                               0x0001
#define MASK_AON_APB_SERDES_EB                              0x80000000
#define MASK_AON_APB_APCPU_WDG_EB                           0x40000000
#define MASK_AON_APB_AP_WDG_EB                              0x20000000
#define MASK_AON_APB_PWM3_EB                                0x10000000
#define MASK_AON_APB_PWM2_EB                                0x8000000
#define MASK_AON_APB_PWM1_EB                                0x4000000
#define MASK_AON_APB_PWM0_EB                                0x2000000
#define MASK_AON_APB_AP_TMR2_EB                             0x1000000
#define MASK_AON_APB_AP_TMR1_EB                             0x800000
#define MASK_AON_APB_AP_TMR0_EB                             0x400000
#define MASK_AON_APB_WTLCP_INTC_EB                          0x200000
#define MASK_AON_APB_WTLCP_LDSP_INTC_EB                     0x100000
#define MASK_AON_APB_WTLCP_TGDSP_INTC_EB                    0x80000
#define MASK_AON_APB_PUBCP_INTC_EB                          0x40000
#define MASK_AON_APB_AUDCP_INTC_EB                          0x20000
#define MASK_AON_APB_AP_INTC5_EB                            0x10000
#define MASK_AON_APB_AP_INTC4_EB                            0x8000
#define MASK_AON_APB_AP_INTC3_EB                            0x4000
#define MASK_AON_APB_AP_INTC2_EB                            0x2000
#define MASK_AON_APB_AP_INTC1_EB                            0x1000
#define MASK_AON_APB_AP_INTC0_EB                            0x0800
#define MASK_AON_APB_EIC_EB                                 0x0400
#define MASK_AON_APB_ADI_EB                                 0x0200
#define MASK_AON_APB_PMU_EB                                 0x0100
#define MASK_AON_APB_I2C_EB                                 0x0080
#define MASK_AON_APB_PUBCP_SIM2_AON_TOP_EB                  0x0040
#define MASK_AON_APB_PUBCP_SIM1_AON_TOP_EB                  0x0020
#define MASK_AON_APB_PUBCP_SIM0_AON_TOP_EB                  0x0010
#define MASK_AON_APB_AP_SIM_AON_TOP_EB                      0x0008
#define MASK_AON_APB_THM2_EB                                0x0004
#define MASK_AON_APB_THM1_EB                                0x0002
#define MASK_AON_APB_THM0_EB                                0x0001
#define MASK_AON_APB_PUBCP_SDIO0_SOFT_RST                   0x4000
#define MASK_AON_APB_AP_SDIO2_SOFT_RST                      0x2000
#define MASK_AON_APB_AP_SDIO1_SOFT_RST                      0x1000
#define MASK_AON_APB_AP_SDIO0_SOFT_RST                      0x0800
#define MASK_AON_APB_AP_EMMC_SOFT_RST                       0x0400
#define MASK_AON_APB_SERDES_DPHY_APB_SOFT_RST               0x0200
#define MASK_AON_APB_SERDES_DPHY_SOFT_RST                   0x0100
#define MASK_AON_APB_LVDSDIS_SOFT_RST                       0x0080
#define MASK_AON_APB_DAP_MTX_SOFT_RST                       0x0040
#define MASK_AON_APB_MSPI1_SOFT_RST                         0x0020
#define MASK_AON_APB_MSPI0_SOFT_RST                         0x0010
#define MASK_AON_APB_BB_CAL_SOFT_RST                        0x0008
#define MASK_AON_APB_DCXO_LC_SOFT_RST                       0x0004
#define MASK_AON_APB_RFTI_SOFT_RST                          0x0002
#define MASK_AON_APB_RC100M_CAL_SOFT_RST                    0x0001
#define MASK_AON_APB_SCC_SOFT_RST                           0x100000
#define MASK_AON_APB_AON_IIS_SOFT_RST                       0x80000
#define MASK_AON_APB_APB_BUSMON_SOFT_RST                    0x40000
#define MASK_AON_APB_APCPU_TS0_SOFT_RST                     0x20000
#define MASK_AON_APB_DJTAG_CTRL_SOFT_RST                    0x10000
#define MASK_AON_APB_CPALL_EIC_SOFT_RST                     0x8000
#define MASK_AON_APB_ETC_SOFT_RST                           0x4000
#define MASK_AON_APB_CKG_SOFT_RST                           0x2000
#define MASK_AON_APB_ANA_SOFT_RST                           0x1000
#define MASK_AON_APB_PIN_SOFT_RST                           0x0800
#define MASK_AON_APB_SPLK_SOFT_RST                          0x0400
#define MASK_AON_APB_OTG_PHY_SOFT_RST                       0x0200
#define MASK_AON_APB_OTG_UTMI_SOFT_RST                      0x0100
#define MASK_AON_APB_DVFS_TOP_SOFT_RST                      0x0080
#define MASK_AON_APB_AON_TMR_SOFT_RST                       0x0040
#define MASK_AON_APB_AP_SYST_SOFT_RST                       0x0020
#define MASK_AON_APB_AON_SYST_SOFT_RST                      0x0010
#define MASK_AON_APB_KPD_SOFT_RST                           0x0008
#define MASK_AON_APB_MBOX_SOFT_RST                          0x0004
#define MASK_AON_APB_GPIO_SOFT_RST                          0x0002
#define MASK_AON_APB_EFUSE_SOFT_RST                         0x0001
#define MASK_AON_APB_SERDES_SOFT_RST                        0x80000000
#define MASK_AON_APB_APCPU_WDG_SOFT_RST                     0x40000000
#define MASK_AON_APB_AP_WDG_SOFT_RST                        0x20000000
#define MASK_AON_APB_PWM3_SOFT_RST                          0x10000000
#define MASK_AON_APB_PWM2_SOFT_RST                          0x8000000
#define MASK_AON_APB_PWM1_SOFT_RST                          0x4000000
#define MASK_AON_APB_PWM0_SOFT_RST                          0x2000000
#define MASK_AON_APB_AP_TMR2_SOFT_RST                       0x1000000
#define MASK_AON_APB_AP_TMR1_SOFT_RST                       0x800000
#define MASK_AON_APB_AP_TMR0_SOFT_RST                       0x400000
#define MASK_AON_APB_WTLCP_INTC_SOFT_RST                    0x200000
#define MASK_AON_APB_WTLCP_LDSP_INTC_SOFT_RST               0x100000
#define MASK_AON_APB_WTLCP_TGDSP_INTC_SOFT_RST              0x80000
#define MASK_AON_APB_PUBCP_INTC_SOFT_RST                    0x40000
#define MASK_AON_APB_AUDCP_INTC_SOFT_RST                    0x20000
#define MASK_AON_APB_AP_INTC5_SOFT_RST                      0x10000
#define MASK_AON_APB_AP_INTC4_SOFT_RST                      0x8000
#define MASK_AON_APB_AP_INTC3_SOFT_RST                      0x4000
#define MASK_AON_APB_AP_INTC2_SOFT_RST                      0x2000
#define MASK_AON_APB_AP_INTC1_SOFT_RST                      0x1000
#define MASK_AON_APB_AP_INTC0_SOFT_RST                      0x0800
#define MASK_AON_APB_EIC_SOFT_RST                           0x0400
#define MASK_AON_APB_ADI_SOFT_RST                           0x0200
#define MASK_AON_APB_PMU_SOFT_RST                           0x0100
#define MASK_AON_APB_I2C_SOFT_RST                           0x0080
#define MASK_AON_APB_PUBCP_SIM2_AON_TOP_SOFT_RST            0x0040
#define MASK_AON_APB_PUBCP_SIM1_AON_TOP_SOFT_RST            0x0020
#define MASK_AON_APB_PUBCP_SIM0_AON_TOP_SOFT_RST            0x0010
#define MASK_AON_APB_AP_SIM_AON_TOP_SOFT_RST                0x0008
#define MASK_AON_APB_THM2_SOFT_RST                          0x0004
#define MASK_AON_APB_THM1_SOFT_RST                          0x0002
#define MASK_AON_APB_THM0_SOFT_RST                          0x0001
#define MASK_AON_APB_PUBCP_SDIO0_RTC_EB                     0x40000
#define MASK_AON_APB_AP_SDIO2_RTC_EB                        0x20000
#define MASK_AON_APB_AP_SDIO1_RTC_EB                        0x10000
#define MASK_AON_APB_AP_SDIO0_RTC_EB                        0x8000
#define MASK_AON_APB_AP_EMMC_RTC_EB                         0x4000
#define MASK_AON_APB_BB_CAL_RTC_EB                          0x2000
#define MASK_AON_APB_DCXO_LC_RTC_EB                         0x1000
#define MASK_AON_APB_AP_TMR2_RTC_EB                         0x0800
#define MASK_AON_APB_AP_TMR1_RTC_EB                         0x0400
#define MASK_AON_APB_AP_TMR0_RTC_EB                         0x0200
#define MASK_AON_APB_APCPU_WDG_RTC_EB                       0x0100
#define MASK_AON_APB_AP_WDG_RTC_EB                          0x0080
#define MASK_AON_APB_EIC_RTCDV5_EB                          0x0040
#define MASK_AON_APB_EIC_RTC_EB                             0x0020
#define MASK_AON_APB_AON_TMR_RTC_EB                         0x0010
#define MASK_AON_APB_AP_SYST_RTC_EB                         0x0008
#define MASK_AON_APB_AON_SYST_RTC_EB                        0x0004
#define MASK_AON_APB_KPD_RTC_EB                             0x0002
#define MASK_AON_APB_ARCH_RTC_EB                            0x0001
#define MASK_AON_APB_EFUSE_PWON_RD_END_FLAG                 0x0004
#define MASK_AON_APB_DBG_TRACE_CTRL_EN                      0x10000
#define MASK_AON_APB_EVENTACK_RESTARTREQ_TS01               0x0010
#define MASK_AON_APB_EVENT_RESTARTREQ_TS01                  0x0002
#define MASK_AON_APB_EVENT_HALTREQ_TS01                     0x0001
#define MASK_AON_APB_PTEST_FUNC_ATSPEED_SEL                 0x0100
#define MASK_AON_APB_PTEST_FUNC_MODE                        0x0080
#define MASK_AON_APB_FUNCTST_DMA_EB                         0x0040
#define MASK_AON_APB_PTEST_BIST_MODE                        0x0020
#define MASK_AON_APB_USB_DLOAD_EN                           0x0010
#define MASK_AON_APB_ARM_BOOT_MD3                           0x0008
#define MASK_AON_APB_ARM_BOOT_MD2                           0x0004
#define MASK_AON_APB_ARM_BOOT_MD1                           0x0002
#define MASK_AON_APB_ARM_BOOT_MD0                           0x0001
#define MASK_AON_APB_BB_BG_AUTO_PD_EN                       0x0008
#define MASK_AON_APB_BB_BG_SLP_PD_EN                        0x0004
#define MASK_AON_APB_BB_BG_FORCE_ON                         0x0002
#define MASK_AON_APB_BB_BG_FORCE_PD                         0x0001
#define MASK_AON_APB_AGCP_DSP_JTAG_MODE                     0x0008
#define MASK_AON_APB_CP_ARM_JTAG_PIN_SEL                    0x0007
#define MASK_AON_APB_DCXO_LC_FLAG                           0x0100
#define MASK_AON_APB_DCXO_LC_FLAG_CLR                       0x0002
#define MASK_AON_APB_DCXO_LC_CNT_CLR                        0x0001
#define MASK_AON_APB_DCXO_LC_CNT                            0xFFFFFFFF
#define MASK_AON_APB_AUDCP_BOOTCTRL_PROT                    0x80000000
#define MASK_AON_APB_AUDCP_REG_PROT_VAL                     0xFFFF
#define MASK_AON_APB_LDSP_CTRL_PROT                         0x80000000
#define MASK_AON_APB_REG_PROT_VAL                           0xFFFF
#define MASK_AON_APB_CGM_AON_APB_LP_SEL                     0x0007
#define MASK_AON_APB_DAP_DBGPWRUP_SOFT_EN                   0x0004
#define MASK_AON_APB_DAP_SYSPWRUP_SOFT_EN                   0x0002
#define MASK_AON_APB_DAP_DJTAG_EN                           0x0001
#define MASK_AON_APB_USER_RSV_FLAG1_B1                      0x0002
#define MASK_AON_APB_USER_RSV_FLAG1_B0                      0x0001
#define MASK_AON_APB_CM4_SYS_SOFT_RST                       0x0010
#define MASK_AON_APB_CM4_CORE_SOFT_RST                      0x0001
#define MASK_AON_APB_MDAR_SYS_HSDL_CFG                      0xFFFFFFFF
#define MASK_AON_APB_CGM_AP_AXI_APCPU_AUTO_GATE_SEL         0x80000000
#define MASK_AON_APB_CGM_AP_MM_AP_FORCE_EN                  0x40000000
#define MASK_AON_APB_CGM_AP_MM_AP_AUTO_GATE_SEL             0x20000000
#define MASK_AON_APB_CGM_EMC_FORCE_EN                       0x10000000
#define MASK_AON_APB_CGM_EMC_AUTO_GATE_SEL                  0x8000000
#define MASK_AON_APB_CGM_MM_ISP_RAW_FORCE_EN                0x4000000
#define MASK_AON_APB_CGM_MM_ISP_RAW_AUTO_GATE_SEL           0x2000000
#define MASK_AON_APB_CGM_MM_ISP_YUV_FORCE_EN                0x1000000
#define MASK_AON_APB_CGM_MM_ISP_YUV_AUTO_GATE_SEL           0x800000
#define MASK_AON_APB_CGM_AON_APB_PUB_FORCE_EN               0x400000
#define MASK_AON_APB_CGM_AON_APB_PUB_AUTO_GATE_SEL          0x200000
#define MASK_AON_APB_CGM_AON_APB_AUDCP_FORCE_EN             0x100000
#define MASK_AON_APB_CGM_AON_APB_AUDCP_AUTO_GATE_SEL        0x80000
#define MASK_AON_APB_CGM_AON_APB_PUBCP_FORCE_EN             0x40000
#define MASK_AON_APB_CGM_AON_APB_PUBCP_AUTO_GATE_SEL        0x20000
#define MASK_AON_APB_CGM_AON_APB_WTLCP_FORCE_EN             0x10000
#define MASK_AON_APB_CGM_AON_APB_WTLCP_AUTO_GATE_SEL        0x8000
#define MASK_AON_APB_CGM_AON_APB_AP_FORCE_EN                0x4000
#define MASK_AON_APB_CGM_AON_APB_AP_AUTO_GATE_SEL           0x2000
#define MASK_AON_APB_CGM_AP_AXI_FORCE_EN                    0x1000
#define MASK_AON_APB_CGM_AP_AXI_AUTO_GATE_SEL               0x0800
#define MASK_AON_APB_CGM_AP_MM_ROOT_FORCE_EN                0x0400
#define MASK_AON_APB_CGM_AP_MM_ROOT_AUTO_GATE_SEL           0x0200
#define MASK_AON_APB_CGM_AP_MM_MM_FORCE_EN                  0x0100
#define MASK_AON_APB_CGM_AP_MM_MM_AUTO_GATE_SEL             0x0080
#define MASK_AON_APB_CGM_AP_MM_GPU_FORCE_EN                 0x0040
#define MASK_AON_APB_CGM_AP_MM_GPU_AUTO_GATE_SEL            0x0020
#define MASK_AON_APB_CGM_GPU_MEM_FORCE_EN                   0x0010
#define MASK_AON_APB_CGM_GPU_MEM_AUTO_GATE_SEL              0x0008
#define MASK_AON_APB_CGM_APCPU_PMU_AUTO_GATE_SEL            0x0004
#define MASK_AON_APB_CGM_APCPU_PMU_FORCE_EN                 0x0002
#define MASK_AON_APB_MBOX_AUTO_GATE_SEL                     0x0001
#define MASK_AON_APB_CGM_PUB_CLK_ANLG_IO_APB_EN             0x0020
#define MASK_AON_APB_CGM_DMC_REF_AUTO_GATE_SEL              0x0010
#define MASK_AON_APB_CGM_TOP_DVFS_ROOT_AUTO_GATE_SEL        0x0008
#define MASK_AON_APB_CGM_TOP_DVFS_ROOT_FORCE_EN             0x0004
#define MASK_AON_APB_CGM_AP_AXI_AUTO_FREQ_DOWN_CTRL_SEL     0x0008
#define MASK_AON_APB_CGM_AP_AXI_AUTO_FREQ_DOWN_EN           0x0004
#define MASK_AON_APB_CGM_AP_AXI_SEL_IDLE                    0x0003
#define MASK_AON_APB_AON_CHIP_ID0                           0xFFFFFFFF
#define MASK_AON_APB_AON_CHIP_ID1                           0xFFFFFFFF
#define MASK_AON_APB_AON_PLAT_ID0                           0xFFFFFFFF
#define MASK_AON_APB_AON_PLAT_ID1                           0xFFFFFFFF
#define MASK_AON_APB_AON_IMPL_ID                            0xFFFFFFFF
#define MASK_AON_APB_AON_MFT_ID                             0xFFFFFFFF
#define MASK_AON_APB_AON_VER_ID                             0xFFFFFFFF
#define MASK_AON_APB_AON_CHIP_ID                            0xFFFFFFFF
#define MASK_AON_APB_ANALOG_PLL_RSV                         0xFFFF0000
#define MASK_AON_APB_ANALOG_TESTMUX                         0xFFFF
#define MASK_AON_APB_PLL_BG_RSV                             0x003F
#define MASK_AON_APB_LVDSDIS_LOG_SEL                        0x0006
#define MASK_AON_APB_LVDSDIS_DBG_SEL                        0x0001
#define MASK_AON_APB_CGM_WCDMA_ROOT_FORCE_EN                0x0020
#define MASK_AON_APB_CGM_WCDMA_ROOT_AUTO_GATE_SEL           0x0010
#define MASK_AON_APB_CGM_WCDMA_PUBCP_FORCE_EN               0x0008
#define MASK_AON_APB_CGM_WCDMA_PUBCP_AUTO_GATE_SEL          0x0004
#define MASK_AON_APB_CGM_WCDMA_WTLCP_FORCE_EN               0x0002
#define MASK_AON_APB_CGM_WCDMA_WTLCP_AUTO_GATE_SEL          0x0001
#define MASK_AON_APB_CGM_PERIPH_AUTO_GATE_EN                0x2000
#define MASK_AON_APB_CGM_GIC_AUTO_GATE_EN                   0x1000
#define MASK_AON_APB_CGM_ACP_AUTO_GATE_EN                   0x0800
#define MASK_AON_APB_CGM_AXI_PERIPH_AUTO_GATE_EN            0x0400
#define MASK_AON_APB_CGM_ACE_AUTO_GATE_EN                   0x0200
#define MASK_AON_APB_CGM_SCU_AUTO_GATE_EN                   0x0100
#define MASK_AON_APB_CGM_CORE7_AUTO_GATE_EN                 0x0080
#define MASK_AON_APB_CGM_CORE6_AUTO_GATE_EN                 0x0040
#define MASK_AON_APB_CGM_CORE5_AUTO_GATE_EN                 0x0020
#define MASK_AON_APB_CGM_CORE4_AUTO_GATE_EN                 0x0010
#define MASK_AON_APB_CGM_CORE3_AUTO_GATE_EN                 0x0008
#define MASK_AON_APB_CGM_CORE2_AUTO_GATE_EN                 0x0004
#define MASK_AON_APB_CGM_CORE1_AUTO_GATE_EN                 0x0002
#define MASK_AON_APB_CGM_CORE0_AUTO_GATE_EN                 0x0001
#define MASK_AON_APB_APCPU_CORE_WAKEUP_ACE_CLK_EN           0x0002
#define MASK_AON_APB_APCPU_CORE_WAKEUP_SCU_CLK_EN           0x0001
#define MASK_AON_APB_SP_AHB_CLK_SOFT_EN                     0x0080
#define MASK_AON_APB_CM4_SLEEPING_STAT                      0x0040
#define MASK_AON_APB_CM4_LOCKUP_STAT                        0x0020
#define MASK_AON_APB_CM4_SOFT_MPUDIS                        0x0010
#define MASK_AON_APB_MMTX_SLEEP_CM4_PUB_WR                  0x0008
#define MASK_AON_APB_MMTX_SLEEP_CM4_PUB_RD                  0x0004
#define MASK_AON_APB_INT_REQ_CM4_SOFT                       0x0002
#define MASK_AON_APB_SP_CFG_BUS_SLEEP                       0x0001
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_RESET_BAR       0x2000
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_DORMANT         0x1000
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_SEC_BIST_STRT   0x0800
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_PVDDOFFB_AON    0x0400
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_AVDDOFFB_AON    0x0200
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_AVDDISOB_AON    0x0100
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_DVDDOFFB_AON    0x0080
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_DVDDISOB_AON    0x0040
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_POR_ISOB_AON    0x0020
#define MASK_AON_APB_R2G_ANALOG_ETEK_ET8212_POR_ISO_AON     0x0010
#define MASK_AON_APB_G2R_ANALOG_ETEK_ET8212_ALARM_TOGGLE_INT 0x0008
#define MASK_AON_APB_G2R_ANALOG_ETEK_ET8212_ATCLIM_TOGGLE_INT 0x0004
#define MASK_AON_APB_G2R_ANALOG_ETEK_ET8212_SEC_BIST_DONE   0x0002
#define MASK_AON_APB_G2R_ANALOG_ETEK_ET8212_SEC_BIST_PASS   0x0001
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_RESET_BAR   0x0200
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_DORMANT     0x0100
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_SEC_BIST_STRT 0x0080
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_PVDDOFFB_AON 0x0040
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_AVDDOFFB_AON 0x0020
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_AVDDISOB_AON 0x0010
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_DVDDOFFB_AON 0x0008
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_DVDDISOB_AON 0x0004
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_POR_ISOB_AON 0x0002
#define MASK_AON_APB_DBG_SEL_ANALOG_ETEK_ET8212_POR_ISO_AON 0x0001
#define MASK_AON_APB_DJTAG_SOFT_RST                         0x0400
#define MASK_AON_APB_DJTAG_PUB0_SOFT_RST                    0x0200
#define MASK_AON_APB_DJTAG_AON_SOFT_RST                     0x0100
#define MASK_AON_APB_DJTAG_AUDCP_SOFT_RST                   0x0080
#define MASK_AON_APB_DJTAG_WTLCP_SOFT_RST                   0x0040
#define MASK_AON_APB_DJTAG_PUBCP_SOFT_RST                   0x0020
#define MASK_AON_APB_DJTAG_MM_SOFT_RST                      0x0010
#define MASK_AON_APB_DJTAG_CDMA2K_SOFT_RST                  0x0008
#define MASK_AON_APB_DJTAG_GPU_SOFT_RST                     0x0004
#define MASK_AON_APB_DJTAG_APCPU_SOFT_RST                   0x0002
#define MASK_AON_APB_DJTAG_AP_SOFT_RST                      0x0001
#define MASK_AON_APB_RTC_CAL_CTL                            0x1FC00000
#define MASK_AON_APB_RTC_CAL_SEL                            0x200000
#define MASK_AON_APB_RTC_CAL_PRECISION                      0x1FE000
#define MASK_AON_APB_RC100M_DIV                             0x1F80
#define MASK_AON_APB_RC100M_CAL_DONE                        0x0040
#define MASK_AON_APB_RC100M_CAL_START                       0x0020
#define MASK_AON_APB_RC100M_ANA_SOFT_RST                    0x0010
#define MASK_AON_APB_RC100M_FORCE_EN                        0x0002
#define MASK_AON_APB_RC100M_AUTO_GATE_EN                    0x0001
#define MASK_AON_APB_LTE_PCCSCC_RFTI_CLK_SW_CFG             0xFF000000
#define MASK_AON_APB_CGM_LPLL1_WTLCP_SEL                    0x200000
#define MASK_AON_APB_CGM_LPLL0_WTLCP_SEL                    0x100000
#define MASK_AON_APB_CGM_CM4_TMR2_EN                        0x80000
#define MASK_AON_APB_DET_32K_EB                             0x40000
#define MASK_AON_APB_CGM_DEBOUNCE_EN                        0x20000
#define MASK_AON_APB_CGM_RC100M_FDK_EN                      0x10000
#define MASK_AON_APB_CGM_RC100M_REF_EN                      0x8000
#define MASK_AON_APB_CGM_TMR_EN                             0x4000
#define MASK_AON_APB_CGM_TSEN_EN                            0x2000
#define MASK_AON_APB_CGM_OTG_REF_EN                         0x1000
#define MASK_AON_APB_CGM_DMC_REF_EN                         0x0800
#define MASK_AON_APB_CGM_DPHY_REF_EN                        0x0400
#define MASK_AON_APB_CGM_DJTAG_TCK_EN                       0x0200
#define MASK_AON_APB_CGM_DSI_CSI_TEST_EB                    0x0100
#define MASK_AON_APB_CGM_MDAR_CHK_EN                        0x0080
#define MASK_AON_APB_CGM_LVDSRF_CALI_EN                     0x0020
#define MASK_AON_APB_CGM_RFTI2_XO_EN                        0x0008
#define MASK_AON_APB_CGM_RFTI1_XO_EN                        0x0002
#define MASK_AON_APB_CGM_RFTI_SBI_EN                        0x0001
#define MASK_AON_APB_SOFT_DDR0_CKG_1X_EN                    0x4000000
#define MASK_AON_APB_SOFT_DDR0_DATA_RET                     0x800000
#define MASK_AON_APB_LIGHT_SLEEP_DDR0_DATA_RET_EN           0x200000
#define MASK_AON_APB_EMC0_CKG_SEL_LOAD                      0x80000
#define MASK_AON_APB_CLK_DEBUG_TS_EB                        0x40000
#define MASK_AON_APB_AAPC_CLK_TEST_EB                       0x10000
#define MASK_AON_APB_CGM_CPHY_CFG_EN                        0x8000
#define MASK_AON_APB_ALL_PLL_TEST_EB                        0x4000
#define MASK_AON_APB_CGM_WCDMA_ICI_EN                       0x2000
#define MASK_AON_APB_CGM_RFTI_RX_WD_EN                      0x1000
#define MASK_AON_APB_CGM_RFTI_TX_WD_EN                      0x0800
#define MASK_AON_APB_CGM_WCDMA_EN                           0x0400
#define MASK_AON_APB_CGM_EMMC_2X_EN                         0x0200
#define MASK_AON_APB_CGM_EMMC_1X_EN                         0x0100
#define MASK_AON_APB_CGM_SDIO2_1X_EN                        0x0080
#define MASK_AON_APB_CGM_SDIO2_2X_EN                        0x0040
#define MASK_AON_APB_CGM_SDIO1_1X_EN                        0x0020
#define MASK_AON_APB_CGM_SDIO1_2X_EN                        0x0010
#define MASK_AON_APB_CGM_SDIO0_1X_EN                        0x0008
#define MASK_AON_APB_CGM_SDIO0_2X_EN                        0x0004
#define MASK_AON_APB_CGM_AP_AXI_EN                          0x0002
#define MASK_AON_APB_CGM_CSSYS_EN                           0x0001
#define MASK_AON_APB_AUDCP_DSP_BOOT_VECTOR                  0xFFFFFFFF
#define MASK_AON_APB_AUDCP_STCK_DSP                         0x2000
#define MASK_AON_APB_AUDCP_STMS_DSP                         0x1000
#define MASK_AON_APB_AUDCP_STDO_DSP                         0x0800
#define MASK_AON_APB_AUDCP_STDI_DSP                         0x0400
#define MASK_AON_APB_AUDCP_STRTCK_DSP                       0x0200
#define MASK_AON_APB_AUDCP_SW_JTAG_ENA_DSP                  0x0100
#define MASK_AON_APB_AUDCP_DSP_EXTERNAL_WAIT                0x0002
#define MASK_AON_APB_AUDCP_DSP_BOOT                         0x0001
#define MASK_AON_APB_CM4_2_AUD_ACCESS_EN                    0x0040
#define MASK_AON_APB_AP_2_AUD_ACCESS_EN                     0x0020
#define MASK_AON_APB_CR5_2_AUD_ACCESS_EN                    0x0010
#define MASK_AON_APB_LDSP_2_AUD_ACCESS_EN                   0x0008
#define MASK_AON_APB_TGDSP_2_AUD_ACCESS_EN                  0x0004
#define MASK_AON_APB_AUDCP_FRC_CLK_DSP_EN                   0x0002
#define MASK_AON_APB_TOP_2_AUD_ACCESS_EN                    0x0001
#define MASK_AON_APB_WTLCP_LDSP_BOOT_VECTOR                 0xFFFFFFFF
#define MASK_AON_APB_WTLCP_STCK_LDSP                        0x2000
#define MASK_AON_APB_WTLCP_STMS_LDSP                        0x1000
#define MASK_AON_APB_WTLCP_STDO_LDSP                        0x0800
#define MASK_AON_APB_WTLCP_STDI_LDSP                        0x0400
#define MASK_AON_APB_WTLCP_STRTCK_LDSP                      0x0200
#define MASK_AON_APB_WTLCP_SW_JTAG_ENA_LDSP                 0x0100
#define MASK_AON_APB_WTLCP_LDSP_EXTERNAL_WAIT               0x0002
#define MASK_AON_APB_WTLCP_LDSP_BOOT                        0x0001
#define MASK_AON_APB_WTLCP_TDSP_BOOT_VECTOR                 0xFFFFFFFF
#define MASK_AON_APB_WTLCP_STCK_TDSP                        0x2000
#define MASK_AON_APB_WTLCP_STMS_TDSP                        0x1000
#define MASK_AON_APB_WTLCP_STDO_TDSP                        0x0800
#define MASK_AON_APB_WTLCP_STDI_TDSP                        0x0400
#define MASK_AON_APB_WTLCP_STRTCK_TDSP                      0x0200
#define MASK_AON_APB_WTLCP_SW_JTAG_ENA_TDSP                 0x0100
#define MASK_AON_APB_WTLCP_TDSP_EXTERNAL_WAIT               0x0002
#define MASK_AON_APB_WTLCP_TDSP_BOOT                        0x0001
#define MASK_AON_APB_WTLCP_EIC_SOFT_RST                     0x0100
#define MASK_AON_APB_WTLCP_EIC_EB                           0x0080
#define MASK_AON_APB_WTLCP_EIC_RTCDV5_EB                    0x0040
#define MASK_AON_APB_WTLCP_EIC_RTC_EB                       0x0020
#define MASK_AON_APB_WTLCP_AON_FRC_WSYS_LT_STOP             0x0010
#define MASK_AON_APB_WTLCP_AON_FRC_WSYS_STOP                0x0008
#define MASK_AON_APB_WTLCP_DSP_DEEP_SLEEP_EN                0x0004
#define MASK_AON_APB_WTLCP_WCMDA_EB                         0x10000
#define MASK_AON_APB_WCDMA_AUTO_GATE_EN                     0x0100
#define MASK_AON_APB_WTLCP_WTLSYS_RFTI_TX_EB                0x0002
#define MASK_AON_APB_WTLCP_WTLSYS_RFTI_RX_EB                0x0001
#define MASK_AON_APB_PUBCP_SYST_RTC_EB                      0x0800
#define MASK_AON_APB_PUBCP_TMR_EB                           0x0400
#define MASK_AON_APB_PUBCP_TMR_RTC_EB                       0x0200
#define MASK_AON_APB_PUBCP_SYST_EB                          0x0100
#define MASK_AON_APB_PUBCP_WDG_EB                           0x0080
#define MASK_AON_APB_PUBCP_WDG_RTC_EB                       0x0040
#define MASK_AON_APB_PUBCP_ARCH_RTC_EB                      0x0020
#define MASK_AON_APB_PUBCP_EIC_EB                           0x0010
#define MASK_AON_APB_PUBCP_EIC_RTCDV5_EB                    0x0008
#define MASK_AON_APB_PUBCP_EIC_RTC_EB                       0x0004
#define MASK_AON_APB_PUBCP_CR5_CORE_SOFT_RST                0x0400
#define MASK_AON_APB_PUBCP_CR5_DBG_SOFT_RST                 0x0200
#define MASK_AON_APB_PUBCP_CR5_ETM_SOFT_RST                 0x0100
#define MASK_AON_APB_PUBCP_CR5_MP_SOFT_RST                  0x0080
#define MASK_AON_APB_PUBCP_CR5_CS_DBG_SOFT_RST              0x0040
#define MASK_AON_APB_PUBCP_TMR_SOFT_RST                     0x0020
#define MASK_AON_APB_PUBCP_SYST_SOFT_RST                    0x0010
#define MASK_AON_APB_PUBCP_WDG_SOFT_RST                     0x0008
#define MASK_AON_APB_PUBCP_EIC_SOFT_RST                     0x0004
#define MASK_AON_APB_AON_ACCESS_PUBCP                       0x2000
#define MASK_AON_APB_PUBCP_CR5_STANDBYWFI_N                 0x1000
#define MASK_AON_APB_PUBCP_CR5_STANDBYWFE_N                 0x0800
#define MASK_AON_APB_PUBCP_CR5_CLKSTOPPED0_N                0x0400
#define MASK_AON_APB_PUBCP_CR5_L2IDLE                       0x0200
#define MASK_AON_APB_PUBCP_CR5_VALIRQ0_N                    0x0100
#define MASK_AON_APB_PUBCP_CR5_VALFIQ0_N                    0x0080
#define MASK_AON_APB_PUBCP_CR5_STOP                         0x0040
#define MASK_AON_APB_PUBCP_CR5_CSYSACK_ATB                  0x0020
#define MASK_AON_APB_PUBCP_CR5_CACTIVE_ATB                  0x0010
#define MASK_AON_APB_PUBCP_CR5_CSSYNC_REQ                   0x0008
#define MASK_AON_APB_PUBCP_CR5_CSYSREQ_ATB                  0x0004
#define MASK_AON_APB_PUBCP_CR5_NODBGCLK                     0x0002
#define MASK_AON_APB_PUBCP_CR5_CFGEE                        0x0001
#define MASK_AON_APB_WTLCP_FRC_STOP_ACK                     0x0100
#define MASK_AON_APB_WTLCP_FRC_STOP_REQ                     0x0001
#define MASK_AON_APB_PUBCP_FRC_STOP_ACK                     0x0100
#define MASK_AON_APB_PUBCP_FRC_STOP_REQ                     0x0001
#define MASK_AON_APB_USB_BUSCLK_SEL_SOC                     0x0004
#define MASK_AON_APB_USB_DIVN_MUX_SEL                       0x0002
#define MASK_AON_APB_AON_IIS_SEL                            0x0001
#define MASK_AON_APB_BSMTMR_SOFT_RST                        0x0080
#define MASK_AON_APB_RFTI2_LTH_SOFT_RST                     0x0040
#define MASK_AON_APB_RFTI1_LTH_SOFT_RST                     0x0020
#define MASK_AON_APB_CSSYS_SOFT_RST                         0x0010
#define MASK_AON_APB_RFTI_SBI_SOFT_RST                      0x0002
#define MASK_AON_APB_LVDSRF_CALI_SOFT_RST                   0x0001
#define MASK_AON_APB_INT_REQ_DCAM2_ARM_STAT                 0x0200
#define MASK_AON_APB_INT_REQ_DCAM1_ARM_STAT                 0x0100
#define MASK_AON_APB_INT_REQ_DCAM0_ARM_STAT                 0x0080
#define MASK_AON_APB_INT_REQ_ISP_CH1_STAT                   0x0040
#define MASK_AON_APB_INT_REQ_ISP_CH0_STAT                   0x0020
#define MASK_AON_APB_INT_REQ_DCAM2_ARM_MASK                 0x0010
#define MASK_AON_APB_INT_REQ_DCAM1_ARM_MASK                 0x0008
#define MASK_AON_APB_INT_REQ_DCAM0_ARM_MASK                 0x0004
#define MASK_AON_APB_INT_REQ_ISP_CH1_MASK                   0x0002
#define MASK_AON_APB_INT_REQ_ISP_CH0_MASK                   0x0001
#define MASK_AON_APB_BSM_TMR_EB                             0x0002
#define MASK_AON_APB_DBGSYS_CSSYS_STM_NSGUAREN              0x10000
#define MASK_AON_APB_DJTAG_SRC_MUX_SEL                      0x0001
#define MASK_AON_APB_FUSEBOX_SELECT_BUFFER_SW               0x0008
#define MASK_AON_APB_EFUSE_MUX_SEL_SW_DEFUALT0              0x0004
#define MASK_AON_APB_EFUSE_MUX_SEL_SW_DEFUALT1              0x0002
#define MASK_AON_APB_EFUSE_MUX_SEL_SW                       0x0001
#define MASK_AON_APB_OTG_TXPREEMPPULSETUNE                  0x100000
#define MASK_AON_APB_OTG_TXRESTUNE                          0xC0000
#define MASK_AON_APB_OTG_TXHSXVTUNE                         0x30000
#define MASK_AON_APB_OTG_TXVREFTUNE                         0xF000
#define MASK_AON_APB_OTG_TXPREEMPAMPTUNE                    0x0C00
#define MASK_AON_APB_OTG_TXRISETUNE                         0x0300
#define MASK_AON_APB_OTG_TXFSLSTUNE                         0x00F0
#define MASK_AON_APB_OTG_SQRXTUNE                           0x0007
#define MASK_AON_APB_OTG_ATERESET                           0x80000000
#define MASK_AON_APB_OTG_VBUS_VALID_PHYREG                  0x1000000
#define MASK_AON_APB_OTG_VBUS_VALID_PHYREG_SEL              0x800000
#define MASK_AON_APB_OTG_TESTBURNIN                         0x200000
#define MASK_AON_APB_OTG_LOOPBACKENB                        0x100000
#define MASK_AON_APB_OTG_TESTDATAOUT                        0xF0000
#define MASK_AON_APB_OTG_VATESTENB                          0xC000
#define MASK_AON_APB_USB2_CON_TESTMODE                      0x80000000
#define MASK_AON_APB_UTMI_WIDTH_SEL                         0x40000000
#define MASK_AON_APB_OTG_SS_SCALEDOWNMODE                   0x6000000
#define MASK_AON_APB_OTG_DMPULLDOWN                         0x200000
#define MASK_AON_APB_OTG_DPPULLDOWN                         0x100000
#define MASK_AON_APB_OTG_COMMONONN                          0x0100
#define MASK_AON_APB_USB2_PHY_IDDIG                         0x0008
#define MASK_AON_APB_OTG_FSEL                               0x0007
#define MASK_AON_APB_USB20_SAMPLER_SEL                      0x100000
#define MASK_AON_APB_HSIC_PLLON                             0x10000
#define MASK_AON_APB_USB20_S_ID                             0x4000
#define MASK_AON_APB_USB_REF_CLK_MUX_SEL                    0x0001
#define MASK_AON_APB_THM0_CALI_RSVD                         0x00FF
#define MASK_AON_APB_THM1_CALI_RSVD                         0x00FF
#define MASK_AON_APB_THM2_CALI_RSVD                         0x00FF
#define MASK_AON_APB_THM2_INT_ADIE_EN                       0x0400
#define MASK_AON_APB_THM1_INT_ADIE_EN                       0x0200
#define MASK_AON_APB_THM0_INT_ADIE_EN                       0x0100
#define MASK_AON_APB_THM2_OVERHEAT_ALARM_ADIE_EN            0x0040
#define MASK_AON_APB_THM1_OVERHEAT_ALARM_ADIE_EN            0x0020
#define MASK_AON_APB_THM0_OVERHEAT_ALARM_ADIE_EN            0x0010
#define MASK_AON_APB_THM2_OVERHEAT_RST_DDIE_EN              0x0004
#define MASK_AON_APB_THM1_OVERHEAT_RST_DDIE_EN              0x0002
#define MASK_AON_APB_THM0_OVERHEAT_RST_DDIE_EN              0x0001
#define MASK_AON_APB_CP_SIM1_CLK_PL                         0x0020
#define MASK_AON_APB_CP_SIM1_DETECT_EN                      0x0010
#define MASK_AON_APB_CP_BAT1_DETECT_EN                      0x0008
#define MASK_AON_APB_CP_SIM1_DETECT_POL                     0x0004
#define MASK_AON_APB_CP_BAT1_DETECT_POL                     0x0002
#define MASK_AON_APB_CP_SIM1_OFF_PD_EN                      0x0001
#define MASK_AON_APB_CP_SIM2_CLK_PL                         0x0020
#define MASK_AON_APB_CP_SIM2_DETECT_EN                      0x0010
#define MASK_AON_APB_CP_BAT2_DETECT_EN                      0x0008
#define MASK_AON_APB_CP_SIM2_DETECT_POL                     0x0004
#define MASK_AON_APB_CP_BAT2_DETECT_POL                     0x0002
#define MASK_AON_APB_CP_SIM2_OFF_PD_EN                      0x0001
#define MASK_AON_APB_CP_SIM3_CLK_PL                         0x0020
#define MASK_AON_APB_CP_SIM3_DETECT_EN                      0x0010
#define MASK_AON_APB_CP_BAT3_DETECT_EN                      0x0008
#define MASK_AON_APB_CP_SIM3_DETECT_POL                     0x0004
#define MASK_AON_APB_CP_BAT3_DETECT_POL                     0x0002
#define MASK_AON_APB_CP_SIM3_OFF_PD_EN                      0x0001
#define MASK_AON_APB_AP_SIM_CLK_PL                          0x0020
#define MASK_AON_APB_AP_SIM_DETECT_EN                       0x0010
#define MASK_AON_APB_AP_BAT_DETECT_EN                       0x0008
#define MASK_AON_APB_AP_SIM_DETECT_POL                      0x0004
#define MASK_AON_APB_AP_BAT_DETECT_POL                      0x0002
#define MASK_AON_APB_AP_SIM_OFF_PD_EN                       0x0001
#define MASK_AON_APB_PU_NUM_AON_MTX_M3                      0xFF000000
#define MASK_AON_APB_PU_NUM_AON_MTX_M2                      0xFF0000
#define MASK_AON_APB_PU_NUM_AON_MTX_M1                      0xFF00
#define MASK_AON_APB_PU_NUM_AON_MTX_M0                      0x00FF
#define MASK_AON_APB_PU_NUM_AON_MTX_MAIN                    0xFF000000
#define MASK_AON_APB_PU_NUM_AON_MTX_M6                      0xFF0000
#define MASK_AON_APB_PU_NUM_AON_MTX_M5                      0xFF00
#define MASK_AON_APB_PU_NUM_AON_MTX_M4                      0x00FF
#define MASK_AON_APB_PU_NUM_AON_MTX_S3                      0xFF000000
#define MASK_AON_APB_PU_NUM_AON_MTX_S2                      0xFF0000
#define MASK_AON_APB_PU_NUM_AON_MTX_S1                      0xFF00
#define MASK_AON_APB_PU_NUM_AON_MTX_S0                      0x00FF
#define MASK_AON_APB_PU_NUM_AON_MTX_S7                      0xFF000000
#define MASK_AON_APB_PU_NUM_AON_MTX_S6                      0xFF0000
#define MASK_AON_APB_PU_NUM_AON_MTX_S5                      0xFF00
#define MASK_AON_APB_PU_NUM_AON_MTX_S4                      0x00FF
#define MASK_AON_APB_PU_NUM_AXI_CM4_TO_AON                  0xFF000000
#define MASK_AON_APB_PU_NUM_AON2DDR_ASYNC_BRIDGE_W          0xFF0000
#define MASK_AON_APB_PU_NUM_AON_MTX_S9                      0xFF00
#define MASK_AON_APB_PU_NUM_AON_MTX_S8                      0x00FF
#define MASK_AON_APB_PU_NUM_WCDMA_REGSLICE                  0xFF000000
#define MASK_AON_APB_PU_NUM_APCPU_AP_REGSLICE               0xFF0000
#define MASK_AON_APB_PU_NUM_AP_MM_REGSLICE                  0xFF00
#define MASK_AON_APB_PU_NUM_AP_GPU_REGSLICE                 0x00FF
#define MASK_AON_APB_PU_NUM_ISP2DDR_REGSLICE                0xFF000000
#define MASK_AON_APB_PU_NUM_AP2DDR_REGSLICE                 0xFF0000
#define MASK_AON_APB_PU_NUM_DPU2DDR_REGSLICE                0xFF00
#define MASK_AON_APB_PU_NUM_GPU2DDR_REGSLICE                0x00FF
#define MASK_AON_APB_PU_NUM_PUBCP2WTLCP_REGSLICE            0xFF000000
#define MASK_AON_APB_PU_NUM_APCPU2DDR_REGSLICE              0xFF0000
#define MASK_AON_APB_PU_NUM_AUDCP2DDR_REGSLICE              0xFF00
#define MASK_AON_APB_PU_NUM_DCAM2DDR_REGSLICE               0x00FF
#define MASK_AON_APB_PU_NUM_VDSP2DDR_REGSLICE               0xFF00
#define MASK_AON_APB_PU_NUM_PUBCP2WTL_ASYNC_BRIDGE          0x00FF
#define MASK_AON_APB_MONITOR_GATE_AUTO_EN_STATUS            0x00F0
#define MASK_AON_APB_MONITOR_WAIT_EN_STATUS                 0x000F
#define MASK_AON_APB_APCPU_LP_NUM_DEBUG_PWR                 0x1FFFE
#define MASK_AON_APB_APCPU_LP_EB_DEBUG_PWR                  0x0001
#define MASK_AON_APB_APCPU_LP_NUM_GIC_COL                   0x1FFFE
#define MASK_AON_APB_APCPU_LP_EB_GIC_COL                    0x0001
#define MASK_AON_APB_APCPU_CLUSTER_ATB_LP_NUM               0x1FFFE
#define MASK_AON_APB_APCPU_CLUSTER_ATB_LP_EB                0x0001
#define MASK_AON_APB_APCPU_CLUSTER_APB_LP_NUM               0x1FFFE
#define MASK_AON_APB_APCPU_CLUSTER_APB_LP_EB                0x0001
#define MASK_AON_APB_APCPU_CLUSTER_GIC_LP_NUM               0x1FFFE
#define MASK_AON_APB_APCPU_CLUSTER_GIC_LP_EB                0x0001
#define MASK_AON_APB_APCPU_GIC600_GIC_LP_NUM                0x1FFFE
#define MASK_AON_APB_APCPU_GIC600_GIC_LP_EB                 0x0001
#define MASK_AON_APB_APCPU_DBG_BLK_LP_NUM                   0x1FFFE
#define MASK_AON_APB_APCPU_DBG_BLK_LP_EB                    0x0001
#define MASK_AON_APB_APCPU_TOP_MTX_LP_NUM                   0x1FFFE00
#define MASK_AON_APB_APCPU_TOP_MTX_MIAN_LP_EB               0x0100
#define MASK_AON_APB_APCPU_TOP_MTX_S3_LP_EB                 0x0080
#define MASK_AON_APB_APCPU_TOP_MTX_S2_LP_EB                 0x0040
#define MASK_AON_APB_APCPU_TOP_MTX_S1_LP_EB                 0x0020
#define MASK_AON_APB_APCPU_TOP_MTX_S0_LP_EB                 0x0010
#define MASK_AON_APB_APCPU_TOP_MTX_M3_LP_EB                 0x0008
#define MASK_AON_APB_APCPU_TOP_MTX_M2_LP_EB                 0x0004
#define MASK_AON_APB_APCPU_TOP_MTX_M1_LP_EB                 0x0002
#define MASK_AON_APB_APCPU_TOP_MTX_M0_LP_EB                 0x0001
#define MASK_AON_APB_APCPU_ACE_PU_NUM                       0xFF00
#define MASK_AON_APB_APCPU_MTX_PU_NUM                       0x00FF
#define MASK_AON_APB_APCPU_CLUSTER_SCU_LP_NUM               0x1FFFE
#define MASK_AON_APB_APCPU_CLUSTER_SCU_LP_EB                0x0001
#define MASK_AON_APB_APCPU_DDR_AB_LP_NUM                    0x1FFFE
#define MASK_AON_APB_APCPU_DDR_AB_LP_EB                     0x0001
#define MASK_AON_APB_QOS_DAP_APCPU                          0xF00000
#define MASK_AON_APB_QOS_ETR_APCPU                          0xF0000
#define MASK_AON_APB_ARQOS_THRESHOLD_APCPU                  0xF000
#define MASK_AON_APB_AWQOS_THRESHOLD_APCPU                  0x0F00
#define MASK_AON_APB_ARQOS_APCPU                            0x00F0
#define MASK_AON_APB_AWQOS_APCPU                            0x000F
#define MASK_AON_APB_CGM_MPLL0_APCPU_FORCE_EN               0x0200
#define MASK_AON_APB_CGM_MPLL0_APCPU_AUTO_GATE_SEL          0x0100
#define MASK_AON_APB_MPLL0_WAIT_FORCE_EN                    0x0004
#define MASK_AON_APB_MPLL0_WAIT_AUTO_GATE_SEL               0x0002
#define MASK_AON_APB_MPLL0_SOFT_CNT_DONE                    0x0001
#define MASK_AON_APB_CGM_MPLL1_APCPU_FORCE_EN               0x0200
#define MASK_AON_APB_CGM_MPLL1_APCPU_AUTO_GATE_SEL          0x0100
#define MASK_AON_APB_MPLL1_WAIT_FORCE_EN                    0x0004
#define MASK_AON_APB_MPLL1_WAIT_AUTO_GATE_SEL               0x0002
#define MASK_AON_APB_MPLL1_SOFT_CNT_DONE                    0x0001
#define MASK_AON_APB_CGM_MPLL2_APCPU_FORCE_EN               0x0200
#define MASK_AON_APB_CGM_MPLL2_APCPU_AUTO_GATE_SEL          0x0100
#define MASK_AON_APB_MPLL2_WAIT_FORCE_EN                    0x0004
#define MASK_AON_APB_MPLL2_WAIT_AUTO_GATE_SEL               0x0002
#define MASK_AON_APB_MPLL2_SOFT_CNT_DONE                    0x0001
#define MASK_AON_APB_CGM_DPLL1_1600M_PUB_FORCE_EN           0x0200
#define MASK_AON_APB_CGM_DPLL0_2666M_PUB_FORCE_EN           0x0100
#define MASK_AON_APB_CGM_DPLL1_1600M_PUB_AUTO_GATE_SEL      0x0080
#define MASK_AON_APB_CGM_DPLL0_2666M_PUB_AUTO_GATE_SEL      0x0040
#define MASK_AON_APB_DPLL1_WAIT_FORCE_EN                    0x0020
#define MASK_AON_APB_DPLL0_WAIT_FORCE_EN                    0x0010
#define MASK_AON_APB_DPLL1_WAIT_AUTO_GATE_SEL               0x0008
#define MASK_AON_APB_DPLL0_WAIT_AUTO_GATE_SEL               0x0004
#define MASK_AON_APB_DPLL1_SOFT_CNT_DONE                    0x0002
#define MASK_AON_APB_DPLL0_SOFT_CNT_DONE                    0x0001
#define MASK_AON_APB_PUB_APB_FW_EB                          0x20000
#define MASK_AON_APB_PUB_REG_EB                             0x10000
#define MASK_AON_APB_DMC_EB                                 0x8000
#define MASK_AON_APB_PHY_VREF_ADJ                           0x03FC
#define MASK_AON_APB_PHY_VREF_PD                            0x0002
#define MASK_AON_APB_PHY_VREF_HI_C                          0x0001
#define MASK_AON_APB_VDSP2DDR_SLICE_LP_NUM                  0x1FFFE
#define MASK_AON_APB_VDSP2DDR_SLICE_LP_EB                   0x0001
#define MASK_AON_APB_PUBCP2WTL_ASYNC_BRIDGE_LP_NUM          0x1FFFE
#define MASK_AON_APB_PUBCP2WTL_ASYNC_BRIDGE_LP_EB           0x0001
#define MASK_AON_APB_CM4_TO_AON_AXI_LP_NUM                  0x1FFFE
#define MASK_AON_APB_CM4_TO_AON_AXI_LP_EB                   0x0001
#define MASK_AON_APB_AON_MTX_MAIN_LP_NUM                    0x1FFFE
#define MASK_AON_APB_AON_MTX_MAIN_LP_EB                     0x0001
#define MASK_AON_APB_AON_MTX_M0_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M0_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M1_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M1_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M2_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M2_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M3_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M3_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M4_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M4_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M5_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M5_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_M6_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_M6_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S0_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S0_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S1_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S1_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S2_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S2_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S3_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S3_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S4_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S4_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S5_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S5_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S6_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S6_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S7_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S7_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S8_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S8_LP_EB                       0x0001
#define MASK_AON_APB_AON_MTX_S9_LP_NUM                      0x1FFFE
#define MASK_AON_APB_AON_MTX_S9_LP_EB                       0x0001
#define MASK_AON_APB_AP2GPU_SLICE_LP_NUM                    0x1FFFE
#define MASK_AON_APB_AP2GPU_SLICE_LP_EB                     0x0001
#define MASK_AON_APB_AP2MM_SLICE_LP_NUM                     0x1FFFE
#define MASK_AON_APB_AP2MM_SLICE_LP_EB                      0x0001
#define MASK_AON_APB_WTLCP2DDR_SLICE_LP_NUM                 0x1FFFE
#define MASK_AON_APB_WTLCP2DDR_SLICE_LP_EB                  0x0001
#define MASK_AON_APB_APCPU2AP_SLICE_LP_NUM                  0x1FFFE
#define MASK_AON_APB_APCPU2AP_SLICE_LP_EB                   0x0001
#define MASK_AON_APB_AUDCP2DDR_SLICE_LP_NUM                 0x1FFFE
#define MASK_AON_APB_AUDCP2DDR_SLICE_LP_EB                  0x0001
#define MASK_AON_APB_APCPU2DDR_SLICE_LP_NUM                 0x1FFFE
#define MASK_AON_APB_APCPU2DDR_SLICE_LP_EB                  0x0001
#define MASK_AON_APB_AON2DDR_ASYNC_BRIDGE_LP_NUM            0x1FFFE
#define MASK_AON_APB_AON2DDR_ASYNC_BRIDGE_LP_EB             0x0001
#define MASK_AON_APB_PUBCP2WTLCP_SLICE_LP_NUM               0x1FFFE
#define MASK_AON_APB_PUBCP2WTLCP_SLICE_LP_EB                0x0001
#define MASK_AON_APB_DCAM2DDR_SLICE_LP_NUM                  0x1FFFE
#define MASK_AON_APB_DCAM2DDR_SLICE_LP_EB                   0x0001
#define MASK_AON_APB_DPU2DDR_SLICE_LP_NUM                   0x1FFFE
#define MASK_AON_APB_DPU2DDR_SLICE_LP_EB                    0x0001
#define MASK_AON_APB_GPU2DDR_SLICE_LP_NUM                   0x1FFFE
#define MASK_AON_APB_GPU2DDR_SLICE_LP_EB                    0x0001
#define MASK_AON_APB_ISP2DDR_SLICE_LP_NUM                   0x1FFFE
#define MASK_AON_APB_ISP2DDR_SLICE_LP_EB                    0x0001
#define MASK_AON_APB_AP2DDR_SLICE_LP_NUM                    0x1FFFE
#define MASK_AON_APB_AP2DDR_SLICE_LP_EB                     0x0001
#define MASK_AON_APB_AON_APB_MASTER_BUSY                    0x00FC
#define MASK_AON_APB_AON_APB_FREQ_CTRL_EN                   0x0002
#define MASK_AON_APB_AON_APB_IDLE_EN                        0x0001
#define MASK_AON_APB_CLK_26MHZ_AUD_CP_ADC_EN                0x0010
#define MASK_AON_APB_CLK_26MHZ_AUD_AP_ADC_EN                0x0008
#define MASK_AON_APB_CLK_26MHZ_AUD_CAL_EN                   0x0004
#define MASK_AON_APB_CLK_26MHZ_AUD_DVFS_EN                  0x0002
#define MASK_AON_APB_CLK_26MHZ_AUD_EN                       0x0001
#define MASK_AON_APB_ANALOG_BB_TOP_SINDRV_ENA_AUTO_EN       0x0040
#define MASK_AON_APB_R2G_ANALOG_BB_TOP_SINDRV_ENA           0x0020
#define MASK_AON_APB_M2G_ANALOG_BB_TOP_SINDRV_ENA           0x0010
#define MASK_AON_APB_R2G_ANALOG_BB_TOP_SINDRV_ENA_SQUARE    0x0008
#define MASK_AON_APB_R2G_ANALOG_BB_TOP_SINDRV_ENA_ADC       0x0004
#define MASK_AON_APB_R2G_ANALOG_BB_TOP_SINDRV_ENA_DVFS      0x0002
#define MASK_AON_APB_R2G_ANALOG_BB_TOP_SINDRV_ENA_CAL       0x0001
#define MASK_AON_APB_AP_EMMC_IO_POWER_OFF_DELAY             0x2000000
#define MASK_AON_APB_AP_EMMC_IO_POWER_OFF                   0x1000000
#define MASK_AON_APB_AP_EMMC_CARDDET_DBNC_THD_32K           0xFF0000
#define MASK_AON_APB_AP_EMMC_BATTERY_DBNC_THD_32K           0xFF00
#define MASK_AON_APB_AP_EMMC_CARDDET_DBNC_EN_32K            0x0080
#define MASK_AON_APB_AP_EMMC_BATTERY_DBNC_EN_32K            0x0040
#define MASK_AON_APB_AP_EMMC_BATTERY_DEB_EN_32K             0x0020
#define MASK_AON_APB_AP_EMMC_BATTERY_PRESENT_32K            0x0010
#define MASK_AON_APB_AP_EMMC_CARD_PROTECT_32K               0x0008
#define MASK_AON_APB_AP_EMMC_CARD_PRESENT_32K               0x0004
#define MASK_AON_APB_AP_EMMC_BATTERY_DET                    0x0002
#define MASK_AON_APB_AP_EMMC_CARD_DET                       0x0001
#define MASK_AON_APB_AP_SDIO0_IO_POWER_OFF_DELAY            0x2000000
#define MASK_AON_APB_AP_SDIO0_IO_POWER_OFF                  0x1000000
#define MASK_AON_APB_AP_SDIO0_CARDDET_DBNC_THD_32K          0xFF0000
#define MASK_AON_APB_AP_SDIO0_BATTERY_DBNC_THD_32K          0xFF00
#define MASK_AON_APB_AP_SDIO0_CARDDET_DBNC_EN_32K           0x0080
#define MASK_AON_APB_AP_SDIO0_BATTERY_DBNC_EN_32K           0x0040
#define MASK_AON_APB_AP_SDIO0_BATTERY_DEB_EN_32K            0x0020
#define MASK_AON_APB_AP_SDIO0_BATTERY_PRESENT_32K           0x0010
#define MASK_AON_APB_AP_SDIO0_CARD_PROTECT_32K              0x0008
#define MASK_AON_APB_AP_SDIO0_CARD_PRESENT_32K              0x0004
#define MASK_AON_APB_AP_SDIO0_BATTERY_DET                   0x0002
#define MASK_AON_APB_AP_SDIO0_CARD_DET                      0x0001
#define MASK_AON_APB_AP_SDIO1_IO_POWER_OFF_DELAY            0x2000000
#define MASK_AON_APB_AP_SDIO1_IO_POWER_OFF                  0x1000000
#define MASK_AON_APB_AP_SDIO1_CARDDET_DBNC_THD_32K          0xFF0000
#define MASK_AON_APB_AP_SDIO1_BATTERY_DBNC_THD_32K          0xFF00
#define MASK_AON_APB_AP_SDIO1_CARDDET_DBNC_EN_32K           0x0080
#define MASK_AON_APB_AP_SDIO1_BATTERY_DBNC_EN_32K           0x0040
#define MASK_AON_APB_AP_SDIO1_BATTERY_DEB_EN_32K            0x0020
#define MASK_AON_APB_AP_SDIO1_BATTERY_PRESENT_32K           0x0010
#define MASK_AON_APB_AP_SDIO1_CARD_PROTECT_32K              0x0008
#define MASK_AON_APB_AP_SDIO1_CARD_PRESENT_32K              0x0004
#define MASK_AON_APB_AP_SDIO1_BATTERY_DET                   0x0002
#define MASK_AON_APB_AP_SDIO1_CARD_DET                      0x0001
#define MASK_AON_APB_AP_SDIO2_IO_POWER_OFF_DELAY            0x2000000
#define MASK_AON_APB_AP_SDIO2_IO_POWER_OFF                  0x1000000
#define MASK_AON_APB_AP_SDIO2_CARDDET_DBNC_THD_32K          0xFF0000
#define MASK_AON_APB_AP_SDIO2_BATTERY_DBNC_THD_32K          0xFF00
#define MASK_AON_APB_AP_SDIO2_CARDDET_DBNC_EN_32K           0x0080
#define MASK_AON_APB_AP_SDIO2_BATTERY_DBNC_EN_32K           0x0040
#define MASK_AON_APB_AP_SDIO2_BATTERY_DEB_EN_32K            0x0020
#define MASK_AON_APB_AP_SDIO2_BATTERY_PRESENT_32K           0x0010
#define MASK_AON_APB_AP_SDIO2_CARD_PROTECT_32K              0x0008
#define MASK_AON_APB_AP_SDIO2_CARD_PRESENT_32K              0x0004
#define MASK_AON_APB_AP_SDIO2_BATTERY_DET                   0x0002
#define MASK_AON_APB_AP_SDIO2_CARD_DET                      0x0001
#define MASK_AON_APB_PUBCP_SDIO0_IO_POWER_OFF_DELAY         0x2000000
#define MASK_AON_APB_PUBCP_SDIO0_IO_POWER_OFF               0x1000000
#define MASK_AON_APB_PUBCP_SDIO0_CARDDET_DBNC_THD_32K       0xFF0000
#define MASK_AON_APB_PUBCP_SDIO0_BATTERY_DBNC_THD_32K       0xFF00
#define MASK_AON_APB_PUBCP_SDIO0_CARDDET_DBNC_EN_32K        0x0080
#define MASK_AON_APB_PUBCP_SDIO0_BATTERY_DBNC_EN_32K        0x0040
#define MASK_AON_APB_PUBCP_SDIO0_BATTERY_DEB_EN_32K         0x0020
#define MASK_AON_APB_PUBCP_SDIO0_BATTERY_PRESENT_32K        0x0010
#define MASK_AON_APB_PUBCP_SDIO0_CARD_PROTECT_32K           0x0008
#define MASK_AON_APB_PUBCP_SDIO0_CARD_PRESENT_32K           0x0004
#define MASK_AON_APB_PUBCP_SDIO0_BATTERY_DET                0x0002
#define MASK_AON_APB_PUBCP_SDIO0_CARD_DET                   0x0001
#define MASK_AON_APB_APCPU_INT_EN_31                        0x80000000
#define MASK_AON_APB_APCPU_INT_EN_30                        0x40000000
#define MASK_AON_APB_APCPU_INT_EN_29                        0x20000000
#define MASK_AON_APB_APCPU_INT_EN_28                        0x10000000
#define MASK_AON_APB_APCPU_INT_EN_27                        0x8000000
#define MASK_AON_APB_APCPU_INT_EN_26                        0x4000000
#define MASK_AON_APB_APCPU_INT_EN_25                        0x2000000
#define MASK_AON_APB_APCPU_INT_EN_24                        0x1000000
#define MASK_AON_APB_APCPU_INT_EN_23                        0x800000
#define MASK_AON_APB_APCPU_INT_EN_22                        0x400000
#define MASK_AON_APB_APCPU_INT_EN_21                        0x200000
#define MASK_AON_APB_APCPU_INT_EN_20                        0x100000
#define MASK_AON_APB_APCPU_INT_EN_19                        0x80000
#define MASK_AON_APB_APCPU_INT_EN_18                        0x40000
#define MASK_AON_APB_APCPU_INT_EN_17                        0x20000
#define MASK_AON_APB_APCPU_INT_EN_16                        0x10000
#define MASK_AON_APB_APCPU_INT_EN_15                        0x8000
#define MASK_AON_APB_APCPU_INT_EN_14                        0x4000
#define MASK_AON_APB_APCPU_INT_EN_13                        0x2000
#define MASK_AON_APB_APCPU_INT_EN_12                        0x1000
#define MASK_AON_APB_APCPU_INT_EN_11                        0x0800
#define MASK_AON_APB_APCPU_INT_EN_10                        0x0400
#define MASK_AON_APB_APCPU_INT_EN_9                         0x0200
#define MASK_AON_APB_APCPU_INT_EN_8                         0x0100
#define MASK_AON_APB_APCPU_INT_EN_7                         0x0080
#define MASK_AON_APB_APCPU_INT_EN_6                         0x0040
#define MASK_AON_APB_APCPU_INT_EN_5                         0x0020
#define MASK_AON_APB_APCPU_INT_EN_4                         0x0010
#define MASK_AON_APB_APCPU_INT_EN_3                         0x0008
#define MASK_AON_APB_APCPU_INT_EN_2                         0x0004
#define MASK_AON_APB_APCPU_INT_EN_1                         0x0002
#define MASK_AON_APB_APCPU_INT_EN_0                         0x0001
#define MASK_AON_APB_APCPU_INT_EN_63                        0x80000000
#define MASK_AON_APB_APCPU_INT_EN_62                        0x40000000
#define MASK_AON_APB_APCPU_INT_EN_61                        0x20000000
#define MASK_AON_APB_APCPU_INT_EN_60                        0x10000000
#define MASK_AON_APB_APCPU_INT_EN_59                        0x8000000
#define MASK_AON_APB_APCPU_INT_EN_58                        0x4000000
#define MASK_AON_APB_APCPU_INT_EN_57                        0x2000000
#define MASK_AON_APB_APCPU_INT_EN_56                        0x1000000
#define MASK_AON_APB_APCPU_INT_EN_55                        0x800000
#define MASK_AON_APB_APCPU_INT_EN_54                        0x400000
#define MASK_AON_APB_APCPU_INT_EN_53                        0x200000
#define MASK_AON_APB_APCPU_INT_EN_52                        0x100000
#define MASK_AON_APB_APCPU_INT_EN_51                        0x80000
#define MASK_AON_APB_APCPU_INT_EN_50                        0x40000
#define MASK_AON_APB_APCPU_INT_EN_49                        0x20000
#define MASK_AON_APB_APCPU_INT_EN_48                        0x10000
#define MASK_AON_APB_APCPU_INT_EN_47                        0x8000
#define MASK_AON_APB_APCPU_INT_EN_46                        0x4000
#define MASK_AON_APB_APCPU_INT_EN_45                        0x2000
#define MASK_AON_APB_APCPU_INT_EN_44                        0x1000
#define MASK_AON_APB_APCPU_INT_EN_43                        0x0800
#define MASK_AON_APB_APCPU_INT_EN_42                        0x0400
#define MASK_AON_APB_APCPU_INT_EN_41                        0x0200
#define MASK_AON_APB_APCPU_INT_EN_40                        0x0100
#define MASK_AON_APB_APCPU_INT_EN_39                        0x0080
#define MASK_AON_APB_APCPU_INT_EN_38                        0x0040
#define MASK_AON_APB_APCPU_INT_EN_37                        0x0020
#define MASK_AON_APB_APCPU_INT_EN_36                        0x0010
#define MASK_AON_APB_APCPU_INT_EN_35                        0x0008
#define MASK_AON_APB_APCPU_INT_EN_34                        0x0004
#define MASK_AON_APB_APCPU_INT_EN_33                        0x0002
#define MASK_AON_APB_APCPU_INT_EN_32                        0x0001
#define MASK_AON_APB_APCPU_INT_EN_95                        0x80000000
#define MASK_AON_APB_APCPU_INT_EN_94                        0x40000000
#define MASK_AON_APB_APCPU_INT_EN_93                        0x20000000
#define MASK_AON_APB_APCPU_INT_EN_92                        0x10000000
#define MASK_AON_APB_APCPU_INT_EN_91                        0x8000000
#define MASK_AON_APB_APCPU_INT_EN_90                        0x4000000
#define MASK_AON_APB_APCPU_INT_EN_89                        0x2000000
#define MASK_AON_APB_APCPU_INT_EN_88                        0x1000000
#define MASK_AON_APB_APCPU_INT_EN_87                        0x800000
#define MASK_AON_APB_APCPU_INT_EN_86                        0x400000
#define MASK_AON_APB_APCPU_INT_EN_85                        0x200000
#define MASK_AON_APB_APCPU_INT_EN_84                        0x100000
#define MASK_AON_APB_APCPU_INT_EN_83                        0x80000
#define MASK_AON_APB_APCPU_INT_EN_82                        0x40000
#define MASK_AON_APB_APCPU_INT_EN_81                        0x20000
#define MASK_AON_APB_APCPU_INT_EN_80                        0x10000
#define MASK_AON_APB_APCPU_INT_EN_79                        0x8000
#define MASK_AON_APB_APCPU_INT_EN_78                        0x4000
#define MASK_AON_APB_APCPU_INT_EN_77                        0x2000
#define MASK_AON_APB_APCPU_INT_EN_76                        0x1000
#define MASK_AON_APB_APCPU_INT_EN_75                        0x0800
#define MASK_AON_APB_APCPU_INT_EN_74                        0x0400
#define MASK_AON_APB_APCPU_INT_EN_73                        0x0200
#define MASK_AON_APB_APCPU_INT_EN_72                        0x0100
#define MASK_AON_APB_APCPU_INT_EN_71                        0x0080
#define MASK_AON_APB_APCPU_INT_EN_70                        0x0040
#define MASK_AON_APB_APCPU_INT_EN_69                        0x0020
#define MASK_AON_APB_APCPU_INT_EN_68                        0x0010
#define MASK_AON_APB_APCPU_INT_EN_67                        0x0008
#define MASK_AON_APB_APCPU_INT_EN_66                        0x0004
#define MASK_AON_APB_APCPU_INT_EN_65                        0x0002
#define MASK_AON_APB_APCPU_INT_EN_64                        0x0001
#define MASK_AON_APB_APCPU_INT_EN_127                       0x80000000
#define MASK_AON_APB_APCPU_INT_EN_126                       0x40000000
#define MASK_AON_APB_APCPU_INT_EN_125                       0x20000000
#define MASK_AON_APB_APCPU_INT_EN_124                       0x10000000
#define MASK_AON_APB_APCPU_INT_EN_123                       0x8000000
#define MASK_AON_APB_APCPU_INT_EN_122                       0x4000000
#define MASK_AON_APB_APCPU_INT_EN_121                       0x2000000
#define MASK_AON_APB_APCPU_INT_EN_120                       0x1000000
#define MASK_AON_APB_APCPU_INT_EN_119                       0x800000
#define MASK_AON_APB_APCPU_INT_EN_118                       0x400000
#define MASK_AON_APB_APCPU_INT_EN_117                       0x200000
#define MASK_AON_APB_APCPU_INT_EN_116                       0x100000
#define MASK_AON_APB_APCPU_INT_EN_115                       0x80000
#define MASK_AON_APB_APCPU_INT_EN_114                       0x40000
#define MASK_AON_APB_APCPU_INT_EN_113                       0x20000
#define MASK_AON_APB_APCPU_INT_EN_112                       0x10000
#define MASK_AON_APB_APCPU_INT_EN_111                       0x8000
#define MASK_AON_APB_APCPU_INT_EN_110                       0x4000
#define MASK_AON_APB_APCPU_INT_EN_109                       0x2000
#define MASK_AON_APB_APCPU_INT_EN_108                       0x1000
#define MASK_AON_APB_APCPU_INT_EN_107                       0x0800
#define MASK_AON_APB_APCPU_INT_EN_106                       0x0400
#define MASK_AON_APB_APCPU_INT_EN_105                       0x0200
#define MASK_AON_APB_APCPU_INT_EN_104                       0x0100
#define MASK_AON_APB_APCPU_INT_EN_103                       0x0080
#define MASK_AON_APB_APCPU_INT_EN_102                       0x0040
#define MASK_AON_APB_APCPU_INT_EN_101                       0x0020
#define MASK_AON_APB_APCPU_INT_EN_100                       0x0010
#define MASK_AON_APB_APCPU_INT_EN_99                        0x0008
#define MASK_AON_APB_APCPU_INT_EN_98                        0x0004
#define MASK_AON_APB_APCPU_INT_EN_97                        0x0002
#define MASK_AON_APB_APCPU_INT_EN_96                        0x0001
#define MASK_AON_APB_APCPU_INT_EN_159                       0x80000000
#define MASK_AON_APB_APCPU_INT_EN_158                       0x40000000
#define MASK_AON_APB_APCPU_INT_EN_157                       0x20000000
#define MASK_AON_APB_APCPU_INT_EN_156                       0x10000000
#define MASK_AON_APB_APCPU_INT_EN_155                       0x8000000
#define MASK_AON_APB_APCPU_INT_EN_154                       0x4000000
#define MASK_AON_APB_APCPU_INT_EN_153                       0x2000000
#define MASK_AON_APB_APCPU_INT_EN_152                       0x1000000
#define MASK_AON_APB_APCPU_INT_EN_151                       0x800000
#define MASK_AON_APB_APCPU_INT_EN_150                       0x400000
#define MASK_AON_APB_APCPU_INT_EN_149                       0x200000
#define MASK_AON_APB_APCPU_INT_EN_148                       0x100000
#define MASK_AON_APB_APCPU_INT_EN_147                       0x80000
#define MASK_AON_APB_APCPU_INT_EN_146                       0x40000
#define MASK_AON_APB_APCPU_INT_EN_145                       0x20000
#define MASK_AON_APB_APCPU_INT_EN_144                       0x10000
#define MASK_AON_APB_APCPU_INT_EN_143                       0x8000
#define MASK_AON_APB_APCPU_INT_EN_142                       0x4000
#define MASK_AON_APB_APCPU_INT_EN_141                       0x2000
#define MASK_AON_APB_APCPU_INT_EN_140                       0x1000
#define MASK_AON_APB_APCPU_INT_EN_139                       0x0800
#define MASK_AON_APB_APCPU_INT_EN_138                       0x0400
#define MASK_AON_APB_APCPU_INT_EN_137                       0x0200
#define MASK_AON_APB_APCPU_INT_EN_136                       0x0100
#define MASK_AON_APB_APCPU_INT_EN_135                       0x0080
#define MASK_AON_APB_APCPU_INT_EN_134                       0x0040
#define MASK_AON_APB_APCPU_INT_EN_133                       0x0020
#define MASK_AON_APB_APCPU_INT_EN_132                       0x0010
#define MASK_AON_APB_APCPU_INT_EN_131                       0x0008
#define MASK_AON_APB_APCPU_INT_EN_130                       0x0004
#define MASK_AON_APB_APCPU_INT_EN_129                       0x0002
#define MASK_AON_APB_APCPU_INT_EN_128                       0x0001
#define MASK_AON_APB_APCPU_INT_EN_191                       0x80000000
#define MASK_AON_APB_APCPU_INT_EN_190                       0x40000000
#define MASK_AON_APB_APCPU_INT_EN_189                       0x20000000
#define MASK_AON_APB_APCPU_INT_EN_188                       0x10000000
#define MASK_AON_APB_APCPU_INT_EN_187                       0x8000000
#define MASK_AON_APB_APCPU_INT_EN_186                       0x4000000
#define MASK_AON_APB_APCPU_INT_EN_185                       0x2000000
#define MASK_AON_APB_APCPU_INT_EN_184                       0x1000000
#define MASK_AON_APB_APCPU_INT_EN_183                       0x800000
#define MASK_AON_APB_APCPU_INT_EN_182                       0x400000
#define MASK_AON_APB_APCPU_INT_EN_181                       0x200000
#define MASK_AON_APB_APCPU_INT_EN_180                       0x100000
#define MASK_AON_APB_APCPU_INT_EN_179                       0x80000
#define MASK_AON_APB_APCPU_INT_EN_178                       0x40000
#define MASK_AON_APB_APCPU_INT_EN_177                       0x20000
#define MASK_AON_APB_APCPU_INT_EN_176                       0x10000
#define MASK_AON_APB_APCPU_INT_EN_175                       0x8000
#define MASK_AON_APB_APCPU_INT_EN_174                       0x4000
#define MASK_AON_APB_APCPU_INT_EN_173                       0x2000
#define MASK_AON_APB_APCPU_INT_EN_172                       0x1000
#define MASK_AON_APB_APCPU_INT_EN_171                       0x0800
#define MASK_AON_APB_APCPU_INT_EN_170                       0x0400
#define MASK_AON_APB_APCPU_INT_EN_169                       0x0200
#define MASK_AON_APB_APCPU_INT_EN_168                       0x0100
#define MASK_AON_APB_APCPU_INT_EN_167                       0x0080
#define MASK_AON_APB_APCPU_INT_EN_166                       0x0040
#define MASK_AON_APB_APCPU_INT_EN_165                       0x0020
#define MASK_AON_APB_APCPU_INT_EN_164                       0x0010
#define MASK_AON_APB_APCPU_INT_EN_163                       0x0008
#define MASK_AON_APB_APCPU_INT_EN_162                       0x0004
#define MASK_AON_APB_APCPU_INT_EN_161                       0x0002
#define MASK_AON_APB_APCPU_INT_EN_160                       0x0001
#define MASK_AON_APB_AP_WDG_RST_FLAG                        0x0040
#define MASK_AON_APB_PCP_WDG_RST_FLAG                       0x0020
#define MASK_AON_APB_WTLCP_LTE_WDG_RST_FLAG                 0x0010
#define MASK_AON_APB_WTLCP_TG_WDG_RST_FLAG                  0x0008
#define MASK_AON_APB_AUDCP_WDG_RST_FLAG                     0x0004
#define MASK_AON_APB_APCPU_WDG_RST_FLAG                     0x0002
#define MASK_AON_APB_SEC_WDG_RST_FLAG                       0x0001
#define MASK_AON_APB_BOND_OPTION0                           0xFFFFFFFF
#define MASK_AON_APB_BOND_OPTION1                           0xFFFFFFFF
#define MASK_AON_APB_RES_REG0                               0xFFFFFFFF
#define MASK_AON_APB_RES_REG1                               0xFFFFFFFF
#define MASK_AON_APB_RES_REG2                               0xFFFFFFFF
#define MASK_AON_APB_RES_REG3                               0xFFFFFFFF
#define MASK_AON_APB_RES_REG4                               0xFFFFFFFF
#define MASK_AON_APB_HPROT_DMAW                             0x00F0
#define MASK_AON_APB_HPROT_DMAR                             0x000F
#define MASK_AON_APB_REC_26MHZ_0_BUF_PD                     0x0100
#define MASK_AON_APB_SLEEP_PLLLOCK_SEL                      0x0080
#define MASK_AON_APB_PLL_LOCK_SEL                           0x0070
#define MASK_AON_APB_SLEEP_DBG_SEL                          0x000F
#define MASK_AON_APB_CPU2DDR_BRIDGE_DEBUG_SIGNAL_R          0xFFFFFFFF
#define MASK_AON_APB_AON2DDR_BRIDGE_DEBUG_SIGNAL_R          0xFFFFFFFF
#define MASK_AON_APB_AON2DDR_AXI_DETECTOR_OVERFLOW          0x0004
#define MASK_AON_APB_AON2DDR_RST_SUBSYS                     0x0002
#define MASK_AON_APB_AON2DDR_BRIDGE_TRANS_IDLE              0x0001
#define MASK_AON_APB_AUD2DDR_BRIDGE_DEBUG_SIGNAL_R          0xFFFFFFFF
#define MASK_AON_APB_WTL2DDR_BRIDGE_DEBUG_SIGNAL_R          0xFFFFFFFF
#define MASK_AON_APB_PUBCP2WTL_BRIDGE_DEBUG_SIGNAL_R        0xFFFFFFFF
#define MASK_AON_APB_LEAKAGE_MAGIC_WORD                     0xFFFFFFFF
#define MASK_AON_APB_LEAKAGE_SWITCH                         0x0001
#define MASK_AON_APB_FUNC_TEST_BOOT_ADDR                    0xFFFFFFFF
#define MASK_AON_APB_CGM_RESCUE                             0xFFFFFFFF
#define MASK_AON_APB_SDIO2_SLICE_EN                         0x0008
#define MASK_AON_APB_CP_SDIO_ENABLE                         0x0004
#define MASK_AON_APB_AP_SDIO_ENABLE                         0x0002
#define MASK_AON_APB_SDIO_MODULE_SEL                        0x0001
#define MASK_AON_APB_SP_INT_REQ_BUSMON_PUBCP_WAKEUP_EN      0x80000000
#define MASK_AON_APB_SP_INT_REQ_BUSMON_AUDCP_WAKEUP_EN      0x40000000
#define MASK_AON_APB_SP_INT_REQ_ADI_WAKEUP_EN               0x20000000
#define MASK_AON_APB_SP_INT_REQ_PCP_WDG_WAKEUP_EN           0x10000000
#define MASK_AON_APB_SP_INT_REQ_PWR_DOWN_ALL_WAKEUP_EN      0x8000000
#define MASK_AON_APB_SP_INT_REQ_PWR_UP_ALL_WAKEUP_EN        0x4000000
#define MASK_AON_APB_SP_INT_REQ_AP_WDG_RST_WAKEUP_EN        0x2000000
#define MASK_AON_APB_SP_INT_REQ_APCPU_WDG_RST_WAKEUP_EN     0x1000000
#define MASK_AON_APB_SP_INT_REQ_SEC_EIC_WAKEUP_EN           0x800000
#define MASK_AON_APB_SP_INT_REQ_SEC_TMR_WAKEUP_EN           0x400000
#define MASK_AON_APB_SP_INT_REQ_SEC_WDG_WAKEUP_EN           0x200000
#define MASK_AON_APB_SP_INT_REQ_SEC_RTC_WAKEUP_EN           0x100000
#define MASK_AON_APB_SP_INT_REQ_SEC_GPIO_WAKEUP_EN          0x80000
#define MASK_AON_APB_SP_INT_REQ_MBOX_SRC_SIPC_SP_CM4_WAKEUP_EN 0x40000
#define MASK_AON_APB_SP_INT_REQ_MBOX_SRC_CM4_WAKEUP_EN      0x20000
#define MASK_AON_APB_SP_INT_REQ_MBOX_TAR_CM4_WAKEUP_EN      0x10000
#define MASK_AON_APB_SP_INT_REQ_CM4_SOFT_WAKEUP_EN          0x8000
#define MASK_AON_APB_SP_INT_FPU_EXCEPTION_WAKEUP_EN         0x4000
#define MASK_AON_APB_SP_INT_REQ_EIC_GPIO_NON_LAT_WAKEUP_EN  0x2000
#define MASK_AON_APB_SP_INT_REQ_EIC_GPIO_LAT_WAKEUP_EN      0x1000
#define MASK_AON_APB_SP_INT_REQ_EIC_NON_LAT_WAKEUP_EN       0x0800
#define MASK_AON_APB_SP_INT_REQ_EIC_LAT_WAKEUP_EN           0x0400
#define MASK_AON_APB_SP_INT_REQ_CM4_DMA_WAKEUP_EN           0x0200
#define MASK_AON_APB_SP_INT_REQ_CM4_GPIO_WAKEUP_EN          0x0100
#define MASK_AON_APB_SP_INT_REQ_CM4_SYST_WAKEUP_EN          0x0080
#define MASK_AON_APB_SP_INT_REQ_CM4_I2C0_SLV_WAKEUP_EN      0x0040
#define MASK_AON_APB_SP_INT_REQ_CM4_WDG_WAKEUP_EN           0x0020
#define MASK_AON_APB_SP_INT_REQ_CM4_SPI_WAKEUP_EN           0x0010
#define MASK_AON_APB_SP_INT_REQ_CM4_UART1_WAKEUP_EN         0x0008
#define MASK_AON_APB_SP_INT_REQ_CM4_UART0_WAKEUP_EN         0x0004
#define MASK_AON_APB_SP_INT_REQ_CM4_I3C1_WAKEUP_EN          0x0002
#define MASK_AON_APB_SP_INT_REQ_CM4_I3C0_WAKEUP_EN          0x0001
#define MASK_AON_APB_SP_INT_REQ_AUDCP_VBC_AUDRCD_WAKEUP_EN  0x80000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_MCDT_WAKEUP_EN        0x40000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_DMA_WAKEUP_EN         0x20000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_CHN_START_CHN3_WAKEUP_EN 0x10000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_CHN_START_CHN2_WAKEUP_EN 0x8000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_CHN_START_CHN1_WAKEUP_EN 0x4000000
#define MASK_AON_APB_SP_INT_REQ_AUDCP_CHN_START_CHN0_WAKEUP_EN 0x2000000
#define MASK_AON_APB_SP_INT_REQ_ANA_WAKEUP_EN               0x1000000
#define MASK_AON_APB_SP_INT_REQ_WTLCP_LTE_WDG_RST_WAKEUP_EN 0x800000
#define MASK_AON_APB_SP_INT_REQ_WTLCP_TG_WDG_RST_WAKEUP_EN  0x400000
#define MASK_AON_APB_SP_INT_REQ_GSP_WAKEUP_EN               0x200000
#define MASK_AON_APB_SP_INT_REQ_SLV_FW_AP_WAKEUP_EN         0x100000
#define MASK_AON_APB_SP_INT_REQ_DISPC_WAKEUP_EN             0x80000
#define MASK_AON_APB_SP_INT_REQ_PUB_DFS_DENY_EN             0x40000
#define MASK_AON_APB_SP_INT_REQ_PUB_DMC_MPU_VIO_WAKEUP_EN   0x20000
#define MASK_AON_APB_SP_INT_REQ_MEM_FW_PUB_WAKEUP_EN        0x10000
#define MASK_AON_APB_SP_INT_REQ_PUB_DFI_BUSMON_WAKEUP_EN    0x8000
#define MASK_AON_APB_SP_INT_REQ_PUB_PTM_WAKEUP_EN           0x4000
#define MASK_AON_APB_SP_INT_REQ_PUB_HARDWARE_DFS_EXIT_WAKEUP_EN 0x2000
#define MASK_AON_APB_SP_INT_REQ_PUB_DFS_COMPLETE_WAKEUP_EN  0x1000
#define MASK_AON_APB_SP_INT_REQ_PUB_DFS_ERROR_WAKEUP_EN     0x0800
#define MASK_AON_APB_SP_INT_REQ_PUB_DFS_GIVEUP_EN           0x0400
#define MASK_AON_APB_SP_INT_REQ_CLK_32K_DET_WAKEUP_EN       0x0200
#define MASK_AON_APB_SP_INT_REQ_AON_I2C_WAKEUP_EN           0x0100
#define MASK_AON_APB_SP_INT_REQ_THM0_WAKEUP_EN              0x0080
#define MASK_AON_APB_SP_INT_REQ_PWR_UP_PUB_WAKEUP_EN        0x0040
#define MASK_AON_APB_SP_INT_REQ_PWR_UP_AP_WAKEUP_EN         0x0020
#define MASK_AON_APB_SP_INT_REQ_SLV_FW_AON_WAKEUP_EN        0x0010
#define MASK_AON_APB_SP_INT_REQ_MEM_FW_AON_WAKEUP_EN        0x0008
#define MASK_AON_APB_SP_INT_REQ_BUSMON_USB_WAKEUP_EN        0x0004
#define MASK_AON_APB_SP_INT_REQ_BUSMON_AP_WAKEUP_EN         0x0002
#define MASK_AON_APB_SP_INT_REQ_BUSMON_WTLCP_WAKEUP_EN      0x0001
#define MASK_AON_APB_SP_INT_REQ_ICACHE_SP_WAKEUP_EN         0x1000
#define MASK_AON_APB_SP_INT_REQ_DCACHE_SP_WAKEUP_EN         0x0800
#define MASK_AON_APB_SP_INT_REQ_BUSMON_CM4_SP_WAKEUP_EN     0x0400
#define MASK_AON_APB_SP_INT_REQ_DFS_VOTE_DONE_WAKEUP_EN     0x0200
#define MASK_AON_APB_SP_INT_REQ_THM2_WAKEUP_EN              0x0100
#define MASK_AON_APB_SP_INT_REQ_THM1_WAKEUP_EN              0x0080
#define MASK_AON_APB_SP_INT_REQ_CM4_TMR2_WAKEUP_EN          0x0040
#define MASK_AON_APB_SP_INT_REQ_CM4_TMR1_WAKEUP_EN          0x0020
#define MASK_AON_APB_SP_INT_REQ_CM4_TMR0_WAKEUP_EN          0x0010
#define MASK_AON_APB_SP_INT_REQ_EXT_RSTB_SPCPU_WAKEUP_EN    0x0008
#define MASK_AON_APB_SP_INT_REQ_DBG_AXI_MON_WAKEUP_EN       0x0004
#define MASK_AON_APB_SP_INT_REQ_AUDCP_WDG_RST_WAKEUP_EN     0x0002
#define MASK_AON_APB_SP_INT_REQ_AUDCP_VBC_AUDPLY_WAKEUP_EN  0x0001
#define MASK_AON_APB_DBG_BUS_DATA_WTLCP                     0xFFFFFFFF
#define MASK_AON_APB_DBG_BUS_DATA_PUBCP                     0xFFFFFFFF
#define MASK_AON_APB_DBG_BUS_DATA_AUDCP                     0xFFFFFFFF
#define MASK_AON_APB_SCC_DBG_BUS                            0xFFFFFFFF
#define MASK_AON_APB_AON_FUNC_CTRL_0                        0xFFFFFFFF
#define MASK_AON_APB_AON_FUNC_CTRL_1                        0xFFFFFFFF

#endif /* __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_MASK_H */
