/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

#ifndef __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_REGS_H
#define __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_REGS_H

#define REG_AON_APB_APB_EB0                                 0x0000
#define REG_AON_APB_APB_EB1                                 0x0004
#define REG_AON_APB_APB_EB2                                 0x0008
#define REG_AON_APB_APB_RST0                                0x000C
#define REG_AON_APB_APB_RST1                                0x0010
#define REG_AON_APB_APB_RST2                                0x0014
#define REG_AON_APB_APB_RTC_EB0                             0x0018
#define REG_AON_APB_PWR_CTRL                                0x0024
#define REG_AON_APB_TS_CFG                                  0x0028
#define REG_AON_APB_BOOT_MODE                               0x002C
#define REG_AON_APB_BB_BG_CTRL                              0x0030
#define REG_AON_APB_CP_ARM_JTAG_CTRL                        0x0034
#define REG_AON_APB_DCXO_LC_REG0                            0x003C
#define REG_AON_APB_DCXO_LC_REG1                            0x0040
#define REG_AON_APB_AUDCP_BOOT_PROT                         0x0078
#define REG_AON_APB_AON_REG_PROT                            0x007C
#define REG_AON_APB_AON_APB_CLK_SEL                         0x0080
#define REG_AON_APB_DAP_DJTAG_SEL                           0x0084
#define REG_AON_APB_USER_RSV_FLAG1                          0x0088
#define REG_AON_APB_CM4_SYS_SOFT_RST                        0x008C
#define REG_AON_APB_MDAR_SYS_HSDL_CFG                       0x00C0
#define REG_AON_APB_AUTO_GATE_CTRL0                         0x00D0
#define REG_AON_APB_AUTO_GATE_CTRL1                         0x00D4
#define REG_AON_APB_AP_AXI_CTRL                             0x00D8
#define REG_AON_APB_AON_CHIP_ID0                            0x00E0
#define REG_AON_APB_AON_CHIP_ID1                            0x00E4
#define REG_AON_APB_AON_PLAT_ID0                            0x00E8
#define REG_AON_APB_AON_PLAT_ID1                            0x00EC
#define REG_AON_APB_AON_IMPL_ID                             0x00F0
#define REG_AON_APB_AON_MFT_ID                              0x00F4
#define REG_AON_APB_AON_VER_ID                              0x00F8
#define REG_AON_APB_AON_CHIP_ID                             0x00FC
#define REG_AON_APB_CCIR_RCVR_CFG                           0x0100
#define REG_AON_APB_PLL_BG_CFG                              0x0108
#define REG_AON_APB_LVDSDIS_SEL                             0x010C
#define REG_AON_APB_AUTO_GATE_CTRL2                         0x0114
#define REG_AON_APB_AUTO_GATE_CTRL3                         0x0118
#define REG_AON_APB_APCPU_CLK_CTRL0                         0x011C
#define REG_AON_APB_SP_CFG_BUS                              0x0124
#define REG_AON_APB_ETC_CTRL0                               0x0128
#define REG_AON_APB_ETC_CTRL1                               0x012C
#define REG_AON_APB_APB_RST3                                0x0130
#define REG_AON_APB_RC100M_CFG                              0x0134
#define REG_AON_APB_CGM_REG1                                0x0138
#define REG_AON_APB_CGM_CLK_TOP_REG1                        0x013C
#define REG_AON_APB_AUDCP_DSP_CTRL0                         0x0140
#define REG_AON_APB_AUDCP_DSP_CTRL1                         0x0144
#define REG_AON_APB_AUDCP_CTRL                              0x014C
#define REG_AON_APB_WTLCP_LDSP_CTRL0                        0x0150
#define REG_AON_APB_WTLCP_LDSP_CTRL1                        0x0154
#define REG_AON_APB_WTLCP_TDSP_CTRL0                        0x0158
#define REG_AON_APB_WTLCP_TDSP_CTRL1                        0x015C
#define REG_AON_APB_WTLCP_CTRL                              0x0164
#define REG_AON_APB_WTL_WCDMA_EB                            0x0168
#define REG_AON_APB_PCP_AON_EB                              0x0170
#define REG_AON_APB_PCP_SOFT_RST                            0x0174
#define REG_AON_APB_PUBCP_CTRL                              0x0178
#define REG_AON_APB_WTLCP_LPC_CTRL                          0x0180
#define REG_AON_APB_PUBCP_LPC_CTRL                          0x0184
#define REG_AON_APB_AON_SOC_USB_CTRL                        0x0190
#define REG_AON_APB_SOFT_RST_AON_ADD1                       0x01A0
#define REG_AON_APB_VDSP_INT_CTRL                           0x01A4
#define REG_AON_APB_EB_AON_ADD1                             0x01B0
#define REG_AON_APB_DBG_DJTAG_CTRL                          0x01C0
#define REG_AON_APB_MBIST_EFUSE_CTRL                        0x01FC
#define REG_AON_APB_OTG_PHY_TUNE                            0x0200
#define REG_AON_APB_OTG_PHY_TEST                            0x0204
#define REG_AON_APB_OTG_PHY_CTRL                            0x0208
#define REG_AON_APB_OTG_CTRL0                               0x020C
#define REG_AON_APB_OTG_CTRL1                               0x0210
#define REG_AON_APB_USB_CLK_REF_SEL                         0x0214
#define REG_AON_APB_LVDSRF_CTRL                             0x0218
#define REG_AON_APB_THM0_CTRL                               0x021C
#define REG_AON_APB_THM1_CTRL                               0x0220
#define REG_AON_APB_THM2_CTRL                               0x0224
#define REG_AON_APB_OVERHEAT_CTRL                           0x022C
#define REG_AON_APB_PUBCP_SIM1_TOP_CTRL                     0x0230
#define REG_AON_APB_PUBCP_SIM2_TOP_CTRL                     0x0234
#define REG_AON_APB_PUBCP_SIM3_TOP_CTRL                     0x0238
#define REG_AON_APB_AP_SIM_TOP_CTRL                         0x023C
#define REG_AON_APB_TOP_PU_NUM_CTRL1                        0x0250
#define REG_AON_APB_TOP_PU_NUM_CTRL2                        0x0254
#define REG_AON_APB_TOP_PU_NUM_CTRL3                        0x0258
#define REG_AON_APB_TOP_PU_NUM_CTRL4                        0x025C
#define REG_AON_APB_TOP_PU_NUM_CTRL5                        0x0260
#define REG_AON_APB_TOP_PU_NUM_CTRL6                        0x0264
#define REG_AON_APB_TOP_PU_NUM_CTRL7                        0x0268
#define REG_AON_APB_TOP_PU_NUM_CTRL8                        0x026C
#define REG_AON_APB_TOP_PU_NUM_CTRL9                        0x0270
#define REG_AON_APB_APCPU_MONITOR_STATUS                    0x0280
#define REG_AON_APB_APCPU_DEBUG_PWR_LP_CTRL                 0x0284
#define REG_AON_APB_APCPU_GIC_COL_LP_CTRL                   0x0288
#define REG_AON_APB_APCPU_CLUSTER_ATB_LPC_CTRL              0x028C
#define REG_AON_APB_APCPU_CLUSTER_APB_LPC_CTRL              0x0290
#define REG_AON_APB_APCPU_CLUSTER_GIC_LPC_CTRL              0x0294
#define REG_AON_APB_APCPU_GIC600_GIC_LPC_CTRL               0x0298
#define REG_AON_APB_APCPU_DBG_BLK_LPC_CTRL                  0x029C
#define REG_AON_APB_APCPU_TOP_MTX_M0_LPC_CTRL               0x0300
#define REG_AON_APB_APCPU_PU_NUM_CTRL                       0x0304
#define REG_AON_APB_APCPU_CLUSTER_SCU_LPC_CTRL              0x0320
#define REG_AON_APB_APCPU_DDR_AB_LPC_CTRL                   0x0324
#define REG_AON_APB_APCPU_QOS_CTRL                          0x0328
#define REG_AON_APB_MPLL0_CTRL                              0x032C
#define REG_AON_APB_MPLL1_CTRL                              0x0330
#define REG_AON_APB_MPLL2_CTRL                              0x0334
#define REG_AON_APB_DPLL_CTRL                               0x0340
#define REG_AON_APB_PUB_CLK_GATING_CTRL                     0x0344
#define REG_AON_APB_DDRPHY_VREP                             0x0348
#define REG_AON_APB_VDSP2DDR_SLI_LPC_CTRL                   0x034C
#define REG_AON_APB_PUBCP2WTL_ASYNC_BRIDGE_LPC_CTRL         0x037C
#define REG_AON_APB_CM42AON_LPC_CTRL                        0x0380
#define REG_AON_APB_AON_MTX_MAIN_LPC_CTRL                   0x0384
#define REG_AON_APB_AON_MTX_M0_LPC_CTRL                     0x0388
#define REG_AON_APB_AON_MTX_M1_LPC_CTRL                     0x038C
#define REG_AON_APB_AON_MTX_M2_LPC_CTRL                     0x0390
#define REG_AON_APB_AON_MTX_M3_LPC_CTRL                     0x0394
#define REG_AON_APB_AON_MTX_M4_LPC_CTRL                     0x0398
#define REG_AON_APB_AON_MTX_M5_LPC_CTRL                     0x039C
#define REG_AON_APB_AON_MTX_M6_LPC_CTRL                     0x03A0
#define REG_AON_APB_AON_MTX_S0_LPC_CTRL                     0x03A4
#define REG_AON_APB_AON_MTX_S1_LPC_CTRL                     0x03A8
#define REG_AON_APB_AON_MTX_S2_LPC_CTRL                     0x03AC
#define REG_AON_APB_AON_MTX_S3_LPC_CTRL                     0x03B0
#define REG_AON_APB_AON_MTX_S4_LPC_CTRL                     0x03B4
#define REG_AON_APB_AON_MTX_S5_LPC_CTRL                     0x03B8
#define REG_AON_APB_AON_MTX_S6_LPC_CTRL                     0x03BC
#define REG_AON_APB_AON_MTX_S7_LPC_CTRL                     0x03C0
#define REG_AON_APB_AON_MTX_S8_LPC_CTRL                     0x03C4
#define REG_AON_APB_AON_MTX_S9_LPC_CTRL                     0x03C8
#define REG_AON_APB_AP2GPU_SLI_LPC_CTRL                     0x03CC
#define REG_AON_APB_AP2MM_SLI_LPC_CTRL                      0x03D0
#define REG_AON_APB_WTLCP2DDR_SLI_LPC_CTRL                  0x03D4
#define REG_AON_APB_APCPU2AP_SLI_LPC_CTRL                   0x03D8
#define REG_AON_APB_AUDCP2DDR_SLI_LPC_CTRL                  0x03DC
#define REG_AON_APB_APCPU2DDR_SLI_LPC_CTRL                  0x03E0
#define REG_AON_APB_AON2DDR_BRG_LPC_CTRL                    0x03E4
#define REG_AON_APB_PUBCP2WTLCP_SLI_LPC_CTRL                0x03E8
#define REG_AON_APB_DCAM2DDR_SLI_LPC_CTRL                   0x03EC
#define REG_AON_APB_DPU2DDR_SLI_LPC_CTRL                    0x03F0
#define REG_AON_APB_GPU2DDR_SLI_LPC_CTRL                    0x03F4
#define REG_AON_APB_ISP2DDR_SLI_LPC_CTRL                    0x03F8
#define REG_AON_APB_AP2DDR_SLI_LPC_CTRL                     0x03FC
#define REG_AON_APB_AON_APB_FREQ_CTRL                       0x0400
#define REG_AON_APB_C2G_ANALOG_BB_TOP_CLK26MHZ_AUD_EN       0x0404
#define REG_AON_APB_MIPI_CSI_POWER_CTRL                     0x0408
#define REG_AON_APB_SINDRV_POWER_CTRL                       0x040C
#define REG_AON_APB_AP_EMMC_PHY_CTRL                        0x0440
#define REG_AON_APB_AP_SDIO0_PHY_CTRL                       0x0444
#define REG_AON_APB_AP_SDIO1_PHY_CTRL                       0x0448
#define REG_AON_APB_AP_SDIO2_PHY_CTRL                       0x044C
#define REG_AON_APB_PUBCP_SDIO0_PHY_CTRL                    0x0450
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL0                  0x0500
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL1                  0x0504
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL2                  0x0508
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL3                  0x050C
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL4                  0x0510
#define REG_AON_APB_APCPU_INT_ENABLE_CTRL5                  0x0514
#define REG_AON_APB_WDG_RST_FLAG                            0x0824
#define REG_AON_APB_BOND_OPT0                               0x083C
#define REG_AON_APB_DEVICE_LIFE_CYCLE                       0x0840
#define REG_AON_APB_RES_REG0                                0x0844
#define REG_AON_APB_RES_REG1                                0x0848
#define REG_AON_APB_RES_REG2                                0x084C
#define REG_AON_APB_RES_REG3                                0x0850
#define REG_AON_APB_RES_REG4                                0x0854
#define REG_AON_APB_AON_MTX_PROT_CFG                        0x0858
#define REG_AON_APB_PLL_LOCK_OUT_SEL                        0x0864
#define REG_AON_APB_CPU2DDR_BRIDGE_DEBUG_SIGNAL_R           0x0870
#define REG_AON_APB_AON2DDR_BRIDGE_DEBUG_SIGNAL_W           0x0874
#define REG_AON_APB_AON2DDR_BRIDGE_DEBUG_SIGNAL_LIST        0x0878
#define REG_AON_APB_AUD2DDR_BRIDGE_DEBUG_SIGNAL_R           0x087C
#define REG_AON_APB_WTL2DDR_BRIDGE_DEBUG_SIGNAL_R           0x0880
#define REG_AON_APB_PUBCP2WTL_BRIDGE_DEBUG_SIGNAL_R         0x0884
#define REG_AON_APB_LEAKAGE_MAGIC_WORD                      0x0900
#define REG_AON_APB_LEAKAGE_SWITCH                          0x0904
#define REG_AON_APB_FUNC_TEST_BOOT_ADDR                     0x0910
#define REG_AON_APB_CGM_RESCUE                              0x0914
#define REG_AON_APB_AON_SDIO                                0x092C
#define REG_AON_APB_SP_WAKEUP_MASK_EN0                      0x0984
#define REG_AON_APB_SP_WAKEUP_MASK_EN1                      0x0988
#define REG_AON_APB_SP_WAKEUP_MASK_EN2                      0x098C
#define REG_AON_APB_DBG_BUS_DATA_WTLCP                      0x0990
#define REG_AON_APB_DBG_BUS_DATA_PUBCP                      0x0994
#define REG_AON_APB_DBG_BUS_DATA_AUDCP                      0x0998
#define REG_AON_APB_SCC_DBG_BUS                             0x0A00
#define REG_AON_APB_AON_FUNC_CTRL_0                         0x0A04
#define REG_AON_APB_AON_FUNC_CTRL_1                         0x0A08

#endif /* __DT_BINDINGS_SPRD_SHARKL5PRO_AON_APB_REGS_H */
