/*
 * Copyright (C) 2018 Unigroup Spreadtrum & RDA Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

#ifndef __DT_BINDINGS_SPRD_SHARKL5PRO_PMU_APB_REGS_H
#define __DT_BINDINGS_SPRD_SHARKL5PRO_PMU_APB_REGS_H

#define REG_PMU_APB_PD_APCPU_TOP_CFG                        0x0000
#define REG_PMU_APB_PD_APCPU_C0_CFG                         0x0004
#define REG_PMU_APB_PD_APCPU_C1_CFG                         0x0008
#define REG_PMU_APB_PD_APCPU_C2_CFG                         0x000C
#define REG_PMU_APB_PD_APCPU_TOP_CFG2                       0x0014
#define REG_PMU_APB_PD_AP_VSP_CFG                           0x0018
#define REG_PMU_APB_PD_AP_SYS_CFG                           0x001C
#define REG_PMU_APB_PD_MM_TOP_CFG                           0x0024
#define REG_PMU_APB_PD_GPU_RGX_DUST_CFG0                    0x0028
#define REG_PMU_APB_PD_GPU_RGX_DUST_CFG1                    0x002C
#define REG_PMU_APB_PD_GPU_TOP_CFG0                         0x0030
#define REG_PMU_APB_PD_WTLCP_LTE_CE_CFG                     0x0034
#define REG_PMU_APB_PD_WTLCP_LTE_DPFEC_CFG                  0x0038
#define REG_PMU_APB_PD_WTLCP_LDSP_CFG                       0x003C
#define REG_PMU_APB_PD_WTLCP_TGDSP_CFG                      0x0040
#define REG_PMU_APB_PD_WTLCP_HU3GE_A_CFG                    0x0044
#define REG_PMU_APB_PD_WTLCP_HU3GE_B_CFG                    0x0048
#define REG_PMU_APB_PD_WTLCP_LTE_PROC_CFG                   0x004C
#define REG_PMU_APB_PD_WTLCP_TD_PROC_CFG                    0x0050
#define REG_PMU_APB_PD_WTLCP_SYS_CFG                        0x0054
#define REG_PMU_APB_PD_PUBCP_SYS_CFG                        0x0058
#define REG_PMU_APB_PD_AUDCP_AUDDSP_CFG                     0x005C
#define REG_PMU_APB_PD_AUDCP_SYS_CFG                        0x0060
#define REG_PMU_APB_PUBCP_FRC_STOP_REQ_FOR_WTL              0x0064
#define REG_PMU_APB_PD_CDMA_SYS_CFG                         0x0068
#define REG_PMU_APB_PD_PUB_SYS_CFG                          0x006C
#define REG_PMU_APB_AP_WAKEUP_POR_CFG                       0x0070
#define REG_PMU_APB_XTL_WAIT_CNT                            0x0074
#define REG_PMU_APB_PLL_WAIT_CNT0                           0x0078
#define REG_PMU_APB_PLL_WAIT_CNT1                           0x007C
#define REG_PMU_APB_PLL_WAIT_CNT2                           0x0080
#define REG_PMU_APB_XTL0_REL_CFG                            0x0084
#define REG_PMU_APB_XTL1_REL_CFG                            0x0088
#define REG_PMU_APB_ISPPLL_REL_CFG                          0x008C
#define REG_PMU_APB_XTLBUF0_REL_CFG                         0x0090
#define REG_PMU_APB_XTLBUF1_REL_CFG                         0x0094
#define REG_PMU_APB_DPLL0_REL_CFG                           0x0098
#define REG_PMU_APB_DPLL1_REL_CFG                           0x009C
#define REG_PMU_APB_LTEPLL_REL_CFG                          0x00A0
#define REG_PMU_APB_TWPLL_REL_CFG                           0x00A4
#define REG_PMU_APB_GPLL_REL_CFG                            0x00A8
#define REG_PMU_APB_RPLL_REL_CFG                            0x00AC
#define REG_PMU_APB_CP_SOFT_RST                             0x00B0
#define REG_PMU_APB_CP_SLP_STATUS_DBG0                      0x00B4
#define REG_PMU_APB_PWR_STATUS4_DBG                         0x00B8
#define REG_PMU_APB_PWR_STATUS0_DBG                         0x00BC
#define REG_PMU_APB_PWR_STATUS1_DBG                         0x00C0
#define REG_PMU_APB_PWR_STATUS2_DBG                         0x00C4
#define REG_PMU_APB_PUB_SYS_AUTO_LIGHT_SLEEP_ENABLE         0x00C8
#define REG_PMU_APB_SLEEP_CTRL                              0x00CC
#define REG_PMU_APB_DDR_SLEEP_CTRL                          0x00D0
#define REG_PMU_APB_SLEEP_STATUS                            0x00D4
#define REG_PMU_APB_PUB_SYS_SLEEP_BYPASS_CFG                0x00D8
#define REG_PMU_APB_PUB_SYS_DEEP_SLEEP_POLL0                0x00DC
#define REG_PMU_APB_PUB_SYS_DEEP_SLEEP_POLL1                0x00E0
#define REG_PMU_APB_CPPLL_REL_CFG                           0x00E4
#define REG_PMU_APB_CPPLL_RST_CTRL_CFG                      0x00E8
#define REG_PMU_APB_DDR_CHN_SLEEP_CTRL0                     0x00F8
#define REG_PMU_APB_DDR_CHN_SLEEP_CTRL1                     0x00FC
#define REG_PMU_APB_PWR_STATUS3_DBG                         0x010C
#define REG_PMU_APB_DDR_OP_MODE_CFG                         0x012C
#define REG_PMU_APB_DDR_PHY_RET_CFG                         0x0130
#define REG_PMU_APB_CLK26M_SEL_CFG                          0x0134
#define REG_PMU_APB_BISR_DONE_STATUS                        0x0138
#define REG_PMU_APB_BISR_BUSY_STATUS                        0x013C
#define REG_PMU_APB_BISR_BYP_CFG                            0x0140
#define REG_PMU_APB_BISR_EN_CFG                             0x0144
#define REG_PMU_APB_CGM_AUTO_GATE_SEL_CFG0                  0x0148
#define REG_PMU_APB_CGM_AUTO_GATE_SEL_CFG1                  0x014C
#define REG_PMU_APB_CGM_AUTO_GATE_SEL_CFG2                  0x0150
#define REG_PMU_APB_CGM_AUTO_GATE_SEL_CFG3                  0x0154
#define REG_PMU_APB_CGM_FORCE_EN_CFG0                       0x0158
#define REG_PMU_APB_CGM_FORCE_EN_CFG1                       0x015C
#define REG_PMU_APB_CGM_FORCE_EN_CFG2                       0x0160
#define REG_PMU_APB_CGM_FORCE_EN_CFG3                       0x0164
#define REG_PMU_APB_SLEEP_XTLON_CTRL                        0x0168
#define REG_PMU_APB_MEM_SLP_CFG                             0x016C
#define REG_PMU_APB_MEM_SD_CFG                              0x0170
#define REG_PMU_APB_APCPU_CORE_WAKEUP_EN                    0x0174
#define REG_PMU_APB_SP_SYS_HOLD_CGM_EN                      0x0178
#define REG_PMU_APB_PWR_CNT_WAIT_CFG0                       0x017C
#define REG_PMU_APB_PWR_CNT_WAIT_CFG1                       0x0180
#define REG_PMU_APB_RCO_REL_CFG                             0x0184
#define REG_PMU_APB_RCO_CNT_WAIT_CFG                        0x018C
#define REG_PMU_APB_MPLL0_REL_CFG                           0x0190
#define REG_PMU_APB_MPLL1_REL_CFG                           0x0194
#define REG_PMU_APB_MPLL2_REL_CFG                           0x0198
#define REG_PMU_APB_MEM_AUTO_SLP_CFG                        0x019C
#define REG_PMU_APB_MEM_AUTO_SD_CFG                         0x01A0
#define REG_PMU_APB_WAKEUP_LOCK_EN                          0x01A4
#define REG_PMU_APB_AUDCP_SYS_CORE_INT_DISABLE              0x01A8
#define REG_PMU_APB_WTLCP_TGDSP_CORE_INT_DISABLE            0x01B0
#define REG_PMU_APB_WTLCP_LDSP_CORE_INT_DISABLE             0x01B4
#define REG_PMU_APB_PUBCP_CORE_INT_DISABLE                  0x01B8
#define REG_PMU_APB_APCPU_C0_CORE_INT_DISABLE               0x01BC
#define REG_PMU_APB_APCPU_C1_CORE_INT_DISABLE               0x01C0
#define REG_PMU_APB_APCPU_C2_CORE_INT_DISABLE               0x01C4
#define REG_PMU_APB_APCPU_C7_CORE_INT_DISABLE               0x01D8
#define REG_PMU_APB_APCPU_C7_DSLP_ENA                       0x01E8
#define REG_PMU_APB_CDMA_DSLP_ENA                           0x01EC
#define REG_PMU_APB_WTLCP_TGDSP_DSLP_ENA                    0x0200
#define REG_PMU_APB_WTLCP_LDSP_DSLP_ENA                     0x0204
#define REG_PMU_APB_AP_DSLP_ENA                             0x0208
#define REG_PMU_APB_PUBCP_DSLP_ENA                          0x020C
#define REG_PMU_APB_WTLCP_DSLP_ENA                          0x0210
#define REG_PMU_APB_APCPU_TOP_DSLP_ENA                      0x0214
#define REG_PMU_APB_SP_SYS_DSLP_ENA                         0x0218
#define REG_PMU_APB_PUB_DEEP_SLEEP_ENA                      0x021C
#define REG_PMU_APB_PUB_DEEP_SLEEP_WAKEUP_EN                0x0220
#define REG_PMU_APB_LIGHT_SLEEP_WAKEUP_EN                   0x0224
#define REG_PMU_APB_LIGHT_SLEEP_ENABLE                      0x0230
#define REG_PMU_APB_LIGHT_SLEEP_MON                         0x0234
#define REG_PMU_APB_DOZE_SLEEP_ENABLE                       0x0238
#define REG_PMU_APB_DOZE_SLEEP_MON                          0x023C
#define REG_PMU_APB_DOZE_FORCE_SLEEP_CTRL                   0x0240
#define REG_PMU_APB_AUDCP_SYS_DSLP_ENA                      0x0244
#define REG_PMU_APB_AUDCP_AUDDSP_DSLP_ENA                   0x0248
#define REG_PMU_APB_PUB_ACC_RDY                             0x0250
#define REG_PMU_APB_PUB_CLK_RDY                             0x0254
#define REG_PMU_APB_EIC_SEL                                 0x0258
#define REG_PMU_APB_AXI_LP_CTRL_DISABLE                     0x0260
#define REG_PMU_APB_PMU_DEBUG                               0x0270
#define REG_PMU_APB_SLEEP_CNT_CLR                           0x0274
#define REG_PMU_APB_LVDSRFPLL_REL_CFG                       0x0280
#define REG_PMU_APB_EXT_XTL_EN_CTRL                         0x0284
#define REG_PMU_APB_PAD_OUT_CHIP_SLEEP_CFG                  0x0288
#define REG_PMU_APB_PAD_OUT_XTL_EN0_CFG                     0x028C
#define REG_PMU_APB_PAD_OUT_XTL_EN1_CFG                     0x0290
#define REG_PMU_APB_PAD_OUT_DCDC_ARM0_EN_CFG                0x0294
#define REG_PMU_APB_PAD_OUT_DCDC_ARM1_EN_CFG                0x0298
#define REG_PMU_APB_DCXO_LP_DEEP_SLEEP_CFG                  0x029C
#define REG_PMU_APB_BISR_FORCE_SEL                          0x0300
#define REG_PMU_APB_AON_MEM_CTRL                            0x0330
#define REG_PMU_APB_PWR_DOMAIN_INT_CLR                      0x0334
#define REG_PMU_APB_DDR_SLP_WAIT_CNT                        0x0338
#define REG_PMU_APB_PMU_CLK_DIV_CFG                         0x033C
#define REG_PMU_APB_CGM_PMU_SEL                             0x0340
#define REG_PMU_APB_PWR_DGB_PARAMETER                       0x0344
#define REG_PMU_APB_APCPU_C0_DSLP_ENA                       0x0348
#define REG_PMU_APB_APCPU_C1_DSLP_ENA                       0x034C
#define REG_PMU_APB_APCPU_C2_DSLP_ENA                       0x0350
#define REG_PMU_APB_APCPU_GIC_RST_EN                        0x0358
#define REG_PMU_APB_ANALOG_PHY_PD_CFG                       0x035C
#define REG_PMU_APB_PUB_SYS_DEEP_SLEEP_SEL                  0x0360
#define REG_PMU_APB_PD_APCPU_C7_CFG                         0x0370
#define REG_PMU_APB_PD_APCPU_TOP_CFG3                       0x0374
#define REG_PMU_APB_APCU_PWR_STATE0                         0x0378
#define REG_PMU_APB_APCU_PWR_STATE1                         0x037C
#define REG_PMU_APB_APCPU_TOP_CFG                           0x0380
#define REG_PMU_APB_APCPU_C0_CFG                            0x0384
#define REG_PMU_APB_APCPU_C1_CFG                            0x0388
#define REG_PMU_APB_APCPU_C2_CFG                            0x038C
#define REG_PMU_APB_APCPU_DSLP_ENA_SRST_MASK_CFG            0x0390
#define REG_PMU_APB_APCPU_C7_CFG                            0x03A0
#define REG_PMU_APB_GIC_CFG                                 0x03A8
#define REG_PMU_APB_FIREWALL_WAKEUP_PUB                     0x03AC
#define REG_PMU_APB_APCPU_TOP_RMA_CTRL                      0x03B0
#define REG_PMU_APB_APCPU_MODE_ST_CFG                       0x03B4
#define REG_PMU_APB_APCPU_C0_SIMD_RET_MODE                  0x03B8
#define REG_PMU_APB_APCPU_C1_SIMD_RET_MODE                  0x03BC
#define REG_PMU_APB_APCPU_C2_SIMD_RET_MODE                  0x03C0
#define REG_PMU_APB_APCPU_CORE_FORCE_STOP                   0x03D4
#define REG_PMU_APB_APCU_MODE_STATE0                        0x03D8
#define REG_PMU_APB_APCU_MODE_STATE1                        0x03DC
#define REG_PMU_APB_PD_GPU_TOP_CFG1                         0x03E0
#define REG_PMU_APB_MPLL_WAIT_CLK_DIV_CFG                   0x03E4
#define REG_PMU_APB_MPLL0_RST_CTRL_CFG                      0x03E8
#define REG_PMU_APB_MPLL1_RST_CTRL_CFG                      0x03EC
#define REG_PMU_APB_MPLL2_RST_CTRL_CFG                      0x03F0
#define REG_PMU_APB_DPLL0_RST_CTRL_CFG                      0x03F8
#define REG_PMU_APB_DPLL1_RST_CTRL_CFG                      0x03FC
#define REG_PMU_APB_TWPLL_RST_CTRL_CFG                      0x0400
#define REG_PMU_APB_LTEPLL_RST_CTRL_CFG                     0x0404
#define REG_PMU_APB_GPLL_RST_CTRL_CFG                       0x0408
#define REG_PMU_APB_RPLL_RST_CTRL_CFG                       0x040C
#define REG_PMU_APB_ISPPLL_RST_CTRL_CFG                     0x0410
#define REG_PMU_APB_PLL_RST_CTRL_STATE0                     0x0414
#define REG_PMU_APB_PLL_RST_CTRL_STATE1                     0x0418
#define REG_PMU_APB_DUAL_RAIL_MEM_POWER_CTRL                0x0420
#define REG_PMU_APB_WTLCP_HU3GE_NEST_DOMAIN_CTRL            0x0424
#define REG_PMU_APB_DEBUG_RECOV_TYPE_CFG                    0x0428
#define REG_PMU_APB_APCPU_MODE_ST_CFG1                      0x042C
#define REG_PMU_APB_APCPU_MODE_ST_CFG2                      0x0430
#define REG_PMU_APB_APCPU_MODE_ST_CFG3                      0x0434
#define REG_PMU_APB_DEBUG_STATE_MARK                        0x0438
#define REG_PMU_APB_ANANKELITE_MEM_POWER_CFG                0x043C
#define REG_PMU_APB_APCPU_MODE_ST_FRC_ON_CFG                0x0440
#define REG_PMU_APB_APCPU_SOFT_RST_TYPE_CFG                 0x0444
#define REG_PMU_APB_APCPU_CORINTH_SCU_CLK_GATE_CFG          0x0448
#define REG_PMU_APB_APCPU_PCHANNEL_STATE0                   0x044C
#define REG_PMU_APB_APCPU_PCHANNEL_STATE1                   0x0450
#define REG_PMU_APB_APCPU_SOFT_INT_GEN                      0x0454
#define REG_PMU_APB_DUAL_RAIL_RAM_FORCE_PD_CFG              0x0458
#define REG_PMU_APB_DUAL_RAIL_RAM_FORCE_SLP_CFG             0x045C
#define REG_PMU_APB_PUB_DFS_FRQ_SEL                         0x0460
#define REG_PMU_APB_APCPU_CORE0_SW_PACTIVE                  0x0464
#define REG_PMU_APB_APCPU_CORE1_SW_PACTIVE                  0x0468
#define REG_PMU_APB_APCPU_CORE2_SW_PACTIVE                  0x046C
#define REG_PMU_APB_APCPU_CORE7_SW_PACTIVE                  0x0480
#define REG_PMU_APB_APCPU_CLUSTER_SW_PACTIVE                0x0484
#define REG_PMU_APB_SOFTWARE_APCPU_PACTIVE_ENABLE           0x0488
#define REG_PMU_APB_SOFTWARE_APCPU_PCHANNEL_HANDSHAKE_ENABLE 0x048C
#define REG_PMU_APB_APCPU_CORE0_SW_PCHANNEL_HANDSHAKE       0x0490
#define REG_PMU_APB_APCPU_CORE1_SW_PCHANNEL_HANDSHAKE       0x0494
#define REG_PMU_APB_APCPU_CORE2_SW_PCHANNEL_HANDSHAKE       0x0498
#define REG_PMU_APB_APCPU_CORE7_SW_PCHANNEL_HANDSHAKE       0x04AC
#define REG_PMU_APB_APCPU_CLUSTER_SW_PCHANNEL_HANDSHAKE     0x04B0
#define REG_PMU_APB_WTLCP_DPFEC_NEST_DOMAIN_CTRL            0x04B4
#define REG_PMU_APB_GPIO_FORCE_GATING_PLL_CFG               0x04B8
#define REG_PMU_APB_ANALOG_PHY_PWRON_CFG                    0x04BC
#define REG_PMU_APB_APCPU_MODE_ST_CGM_EN_CFG                0x04C0
#define REG_PMU_APB_APCPU_DENY_TIME_THRESHOLD_CFG           0x04C4
#define REG_PMU_APB_INT_REQ_APCPU_MODE_ST_ENABLE            0x04C8
#define REG_PMU_APB_INT_REQ_APCPU_MODE_ST_CLR               0x04CC
#define REG_PMU_APB_INT_REQ_MODE_ST_RECORD                  0x04D0
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE0_INF         0x04D4
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE1_INF         0x04D8
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE2_INF         0x04DC
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE7_INF         0x04F0
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CLUSTER_INF       0x04F4
#define REG_PMU_APB_APCPU_CSYSPWRUP_WAKEUP_EN_CFG           0x04F8
#define REG_PMU_APB_DVFS_BLOCK_SHUTDOWN_CFG                 0x04FC
#define REG_PMU_APB_OFF_EMU_CLR_IN_DISABLE_CFG              0x0500
#define REG_PMU_APB_ANANKE_LITE_DUAL_RAIL_RAM_FORCE_ON_CFG  0x0504
#define REG_PMU_APB_OFF_EMU_TO_OFF_CFG                      0x0508
#define REG_PMU_APB_ALL_PLL_PD_RCO_BYP                      0x050C
#define REG_PMU_APB_SP_CLK_GATE_BYP_CFG                     0x0510
#define REG_PMU_APB_DPLL1_CNT_DONE_BYP                      0x0514
#define REG_PMU_APB_SRAM_DLY_CTRL_CFG                       0x0518
#define REG_PMU_APB_WDG_TRIG_DBG_RECOV_CFG                  0x051C
#define REG_PMU_APB_PD_CDMA_SYS_SHUTDOWN_MARK_STATUS        0x0600
#define REG_PMU_APB_CDMA_DEEP_SLEEP_CNT                     0x0610
#define REG_PMU_APB_CDMA_DEEP_SLEEP_CFG                     0x0620
#define REG_PMU_APB_CDMA_WAKEUP_CFG                         0x0624
#define REG_PMU_APB_CDMA_PROC1_PWR_CFG                      0x0630
#define REG_PMU_APB_PD_APCPU_C0_SHUTDOWN_MARK_STATUS        0x0700
#define REG_PMU_APB_PD_APCPU_C1_SHUTDOWN_MARK_STATUS        0x0704
#define REG_PMU_APB_PD_APCPU_C2_SHUTDOWN_MARK_STATUS        0x0708
#define REG_PMU_APB_PD_APCPU_TOP_SHUTDOWN_MARK_STATUS       0x070C
#define REG_PMU_APB_PD_AP_SYS_SHUTDOWN_MARK_STATUS          0x0710
#define REG_PMU_APB_PD_GPU_TOP_SHUTDOWN_MARK_STATUS         0x0714
#define REG_PMU_APB_PD_MM_TOP_SHUTDOWN_MARK_STATUS          0x0718
#define REG_PMU_APB_PD_WTLCP_LTE_CE_SHUTDOWN_MARK_STATUS    0x071C
#define REG_PMU_APB_PD_WTLCP_LTE_DPFEC_SHUTDOWN_MARK_STATUS 0x0720
#define REG_PMU_APB_PD_AP_VSP_SHUTDOWN_MARK_STATUS          0x0724
#define REG_PMU_APB_PD_WTLCP_LDSP_SHUTDOWN_MARK_STATUS      0x0728
#define REG_PMU_APB_PD_WTLCP_TGDSP_SHUTDOWN_MARK_STATUS     0x072C
#define REG_PMU_APB_PD_WTLCP_HU3GE_A_SHUTDOWN_MARK_STATUS   0x0730
#define REG_PMU_APB_PD_WTLCP_HU3GE_B_SHUTDOWN_MARK_STATUS   0x0734
#define REG_PMU_APB_PD_WTLCP_SYS_SHUTDOWN_MARK_STATUS       0x0738
#define REG_PMU_APB_PD_PUBCP_SYS_SHUTDOWN_MARK_STATUS       0x073C
#define REG_PMU_APB_PD_WTLCP_LTE_PROC_SHUTDOWN_MARK_STATUS  0x0740
#define REG_PMU_APB_PD_WTLCP_TD_PROC_SHUTDOWN_MARK_STATUS   0x0744
#define REG_PMU_APB_PD_AUDCP_SYS_SHUTDOWN_MARK_STATUS       0x0748
#define REG_PMU_APB_PD_PUB_SYS_SHUTDOWN_MARK_STATUS         0x074C
#define REG_PMU_APB_PD_AUDCP_AUDDSP_SHUTDOWN_MARK_STATUS    0x0750
#define REG_PMU_APB_PD_GPU_RGX_DUST_SHUTDOWN_MARK_STATUS    0x0754
#define REG_PMU_APB_APCPU_TOP_SLEEP_CNT                     0x0758
#define REG_PMU_APB_AP_SYS_SLEEP_CNT                        0x075C
#define REG_PMU_APB_WTLCP_SYS_SLEEP_CNT                     0x0760
#define REG_PMU_APB_PUBCP_SYS_SLEEP_CNT                     0x0764
#define REG_PMU_APB_AUDCP_SYS_SLEEP_CNT                     0x0768
#define REG_PMU_APB_PUB_SYS_LIGHT_SLEEP_CNT                 0x076C
#define REG_PMU_APB_AP_DEEP_SLEEP_CNT                       0x0770
#define REG_PMU_APB_SP_SYS_DEEP_SLEEP_CNT                   0x0774
#define REG_PMU_APB_WTLCP_DEEP_SLEEP_CNT                    0x0778
#define REG_PMU_APB_PUBCP_DEEP_SLEEP_CNT                    0x077C
#define REG_PMU_APB_AUDCP_SYS_DEEP_SLEEP_CNT                0x0780
#define REG_PMU_APB_PUB_SYS_DEEP_SLEEP_CNT                  0x0784
#define REG_PMU_APB_AP_LIGHT_SLEEP_CNT                      0x0788
#define REG_PMU_APB_WTLCP_LIGHT_SLEEP_CNT                   0x078C
#define REG_PMU_APB_PUBCP_LIGHT_SLEEP_CNT                   0x0790
#define REG_PMU_APB_AUDCP_SYS_LIGHT_SLEEP_CNT               0x0794
#define REG_PMU_APB_AON_SYS_LIGHT_SLEEP_CNT                 0x0798
#define REG_PMU_APB_SYS_SOFT_RST_BUSY                       0x079C
#define REG_PMU_APB_REG_SYS_SRST_FRC_LP_ACK                 0x07A0
#define REG_PMU_APB_SOFT_RST_SEL                            0x07A4
#define REG_PMU_APB_REG_SYS_DDR_PWR_HS_ACK                  0x07A8
#define REG_PMU_APB_CSI_DSI_PWR_CNT_DONE                    0x07AC
#define REG_PMU_APB_PD_AP_SYS_DBG_SHUTDOWN_EN               0x07B0
#define REG_PMU_APB_EIC_SYS_SEL                             0x07B4
#define REG_PMU_APB_DDR_SLP_CTRL_STATE                      0x07B8
#define REG_PMU_APB_PD_APCPU_C7_SHUTDOWN_MARK_STATUS        0x07BC
#define REG_PMU_APB_APCPU_TOP_DEEP_SLEEP_CNT                0x07C0
#define REG_PMU_APB_APCPU_TOP_LIGHT_SLEEP_CNT               0x07C4
#define REG_PMU_APB_AP_DOZE_SLEEP_CNT                       0x07C8
#define REG_PMU_APB_WTLCP_DOZE_SLEEP_CNT                    0x07CC
#define REG_PMU_APB_PUBCP_DOZE_SLEEP_CNT                    0x07D0
#define REG_PMU_APB_AUDCP_DOZE_SLEEP_CNT                    0x07D4
#define REG_PMU_APB_PD_APCPU_C3_CFG                         0x07D8
#define REG_PMU_APB_PD_APCPU_C4_CFG                         0x07DC
#define REG_PMU_APB_PD_APCPU_C5_CFG                         0x07E0
#define REG_PMU_APB_PD_AP_VDSP_CFG                          0x07E4
#define REG_PMU_APB_APCPU_C3_CORE_INT_DISABLE               0x07E8
#define REG_PMU_APB_APCPU_C4_CORE_INT_DISABLE               0x07EC
#define REG_PMU_APB_APCPU_C5_CORE_INT_DISABLE               0x07F0
#define REG_PMU_APB_APCPU_C6_CORE_INT_DISABLE               0x07F4
#define REG_PMU_APB_AP_VDSP_CORE_INT_DISABLE                0x07F8
#define REG_PMU_APB_APCPU_WFI_MARK                          0x07FC
#define REG_PMU_APB_APCPU_C6_DSLP_ENA                       0x0800
#define REG_PMU_APB_AP_VDSP_DSLP_ENA                        0x0804
#define REG_PMU_APB_APCPU_C3_DSLP_ENA                       0x0808
#define REG_PMU_APB_APCPU_C4_DSLP_ENA                       0x080C
#define REG_PMU_APB_APCPU_C5_DSLP_ENA                       0x0810
#define REG_PMU_APB_PD_APCPU_C6_CFG                         0x0814
#define REG_PMU_APB_PD_APCPU_CPU1_CFG1                      0x0818
#define REG_PMU_APB_PD_APCPU_CPU1_CFG2                      0x081C
#define REG_PMU_APB_APCU_PWR_STATE_FIG                      0x0820
#define REG_PMU_APB_APCPU_C3_CFG                            0x0824
#define REG_PMU_APB_APCPU_C4_CFG                            0x0828
#define REG_PMU_APB_APCPU_C5_CFG                            0x082C
#define REG_PMU_APB_APCPU_C6_CFG                            0x0830
#define REG_PMU_APB_APCPU_C3_SIMD_RET_MODE                  0x0834
#define REG_PMU_APB_APCPU_C4_SIMD_RET_MODE                  0x0838
#define REG_PMU_APB_APCPU_C5_SIMD_RET_MODE                  0x083C
#define REG_PMU_APB_APCU_MODE_STATE_FIG                     0x0840
#define REG_PMU_APB_APCPU_CORE3_SW_PACTIVE                  0x0844
#define REG_PMU_APB_APCPU_CORE4_SW_PACTIVE                  0x0848
#define REG_PMU_APB_APCPU_CORE5_SW_PACTIVE                  0x084C
#define REG_PMU_APB_APCPU_CORE6_SW_PACTIVE                  0x0850
#define REG_PMU_APB_APCPU_CORE3_SW_PCHANNEL_HANDSHAKE       0x0854
#define REG_PMU_APB_APCPU_CORE4_SW_PCHANNEL_HANDSHAKE       0x0858
#define REG_PMU_APB_APCPU_CORE5_SW_PCHANNEL_HANDSHAKE       0x085C
#define REG_PMU_APB_APCPU_CORE6_SW_PCHANNEL_HANDSHAKE       0x0860
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE3_INF         0x0864
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE4_INF         0x0868
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE5_INF         0x086C
#define REG_PMU_APB_INT_REQ_MODE_ST_APCPU_CORE6_INF         0x0870
#define REG_PMU_APB_PD_APCPU_C3_SHUTDOWN_MARK_STATUS        0x0874
#define REG_PMU_APB_PD_APCPU_C4_SHUTDOWN_MARK_STATUS        0x0878
#define REG_PMU_APB_PD_APCPU_C5_SHUTDOWN_MARK_STATUS        0x087C
#define REG_PMU_APB_PD_AP_VDSP_SHUTDOWN_MARK_STATUS         0x0880
#define REG_PMU_APB_PD_APCPU_C6_SHUTDOWN_MARK_STATUS        0x0884
#define REG_PMU_APB_MEM_AUTO_SLP_CFG_FIG                    0x0888
#define REG_PMU_APB_MEM_AUTO_SD_CFG_FIG                     0x088C
#define REG_PMU_APB_MEM_SLP_CFG_FIG                         0x0890
#define REG_PMU_APB_MEM_SD_CFG_FIG                          0x0894
#define REG_PMU_APB_PD_GPU_CORE_CFG0                        0x0898
#define REG_PMU_APB_EPPLL_REL_CFG                           0x089C
#define REG_PMU_APB_EPPLL_RST_CTRL_CFG                      0x08A0
#define REG_PMU_APB_EPPLL_DELAY_CTRL_CFG0                   0x08A4
#define REG_PMU_APB_EPPLL_DELAY_CTRL_CFG1                   0x08A8
#define REG_PMU_APB_EPPLL_DELAY_CTRL_CFG2                   0x08AC
#define REG_PMU_APB_EPPLL_DELAY_CTRL_CFG3                   0x08B0
#define REG_PMU_APB_EPPLL_PLL_SEL_CFG                       0x08B4

#endif /* __DT_BINDINGS_SPRD_SHARKL5PRO_PMU_APB_REGS_H */
