obj-y	+= common.o
obj-y	+= gate.o
obj-y	+= mux.o
obj-y	+= div.o
obj-y	+= composite.o
obj-y	+= pll.o
obj-y	+= fixed-factor.o
obj-y	+= fixed-rate.o

## SoC support
obj-$(CONFIG_SPRD_CLK_SC9832E)		+= sc9832e-clk.o
obj-$(CONFIG_SPRD_CLK_SC7731E)		+= sc7731e-clk.o
obj-$(CONFIG_SPRD_CLK_SC9863A)		+= sc9863a-clk.o
obj-$(CONFIG_SPRD_CLK_SHARKL5PRO)	+= sharkl5pro-clk.o
obj-$(CONFIG_SPRD_CLK_UMS9230)		+= ums9230-clk.o
obj-$(CONFIG_SPRD_CLK_UMS9620)          += ums9620-clk.o
