#
# Copyright (C) 2015 Samsung Electronics
# Przemyslaw Marczak <p.marczak@samsung.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-$(CONFIG_DM_REGULATOR) += regulator-uclass.o
obj-$(CONFIG_DM_REGULATOR_SC2721) += sc2721-regulator.o
obj-$(CONFIG_DM_REGULATOR_SC2720) += sc2720-regulator.o
obj-$(CONFIG_DM_REGULATOR_SC2730) += sc2730-regulator.o
obj-$(CONFIG_DM_REGULATOR_MAX77686) += max77686.o
obj-$(CONFIG_DM_REGULATOR_FIXED) += fixed.o
obj-$(CONFIG_DM_REGULATOR_SANDBOX) += sandbox.o
